### ISSUE TITLE
Convert: Maxing out CPU on hardened kernel

### ISSUE THREAD

**Issue by choopm** [ImageMagick/ImageMagick#111]
Using GrSecurity/PaX on ArchLinux results in an infinite loop for `convert pic.png -blur 0x3 picnew.png`
Here's the trimmed strace:

`open("/proc/self/maps", O_RDONLY)       = 9
fstat(9, {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x36be3571000
read(9, "00400000-00401000 r-xp 00000000 "..., 1024) = 1024
close(9)                                = 0
munmap(0x36be3571000, 4096)             = 0
mmap(0x200000000, 25769803776, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x365d9162000
munmap(0x365d9162000, 25769803776)      = 0`

See https://github.com/thestinger/paxd/pull/55

**Comment by dlemstra** [comment]
Which version of ImageMagick are you using?

**Comment by choopm** [comment]
6.9.3-0 Q16 x86_64 2016-01-15

**Comment by dlemstra** [comment]
Where can we find pic.png so we can try to reproduce the issue?

**Comment by choopm** [comment]
You can take any picture. I've tested with [1].
[1]: http://www.imagemagick.org/image/wizard.png

**Comment by urban-warrior** [comment]
Can you identify this problem as a bug in ImageMagick and not a problem in Arch Linux?  Unfortunately we do have access to Arch Linux so we cannot reproduce the problem.

The problem appears related to memory-mapping.  Edit magick/magick-baseconfig.h and comment out

    #define MAGICKCORE_HAVE_MMAP 1

rebuild, reinstall, and run your command.  If it completes, we know the problem is memory-mapped related. The code that supports memory-mapping has been in use for 10+ years without any reported problems so we'll need your help in identifying a potential fix for Arch Linux.

**Comment by choopm** [comment]
I did some further investigations:
On ArchLinux: If using the PaX-Flags "PEMRS" or "pemrs" for convert everything works fine. The moment I disable MPROTECT ("PEmRS") it behaves like described above.
However, I'm unable to reproduce this issue on Gentoo or Debian.

**Comment by dlemstra** [comment]
@choopm We would like to close this issue because we are unable to assist you further. Is that okay with you?

**Comment by choopm** [comment]
Closing it.

For everyone experiencing the same issue: Disabling MPROTECT seems to trigger this, so try the default flags: "PeMrs" or disable RANDMMAP too.
