### ISSUE TITLE
Resizing image increase image size

### ISSUE THREAD

**Issue by arnaudlewis** [ImageMagick/ImageMagick#1128]
Version: ImageMagick 7.0.5-4

Issue: When I try to resize an already optimized image by 50%, the size of the picture increase from 20kB to 31kB
I tried with `resize`: `convert ~/test_image_compression.png -resize 50.000% ~/test.png`

You can try with the following image:
![test_image_compression](https://user-images.githubusercontent.com/5988959/39824183-0eb366a4-53af-11e8-8e13-527c181fb144.png)

Thanks for your help!

**Comment by fmw42** [comment]
If your input is type palette with 256 colors or less, when you resize, new colors are created by the interpolation/resampling. So you could get millions of colors via the new type being truecolor. You should reduce your colors using -type palette or PNG8:output.png or -colors X.

**Comment by arnaudlewis** [comment]
Alright, I’ll try that and I’ll get back to you. Thanks for the quick answer ;)

**Comment by fmw42** [comment]
try

convert 39824183-0eb366a4-53af-11e8-8e13-527c181fb144.png -resize 50% -type palettealpha tmp.png

This produces a palette type with alpha, but the size is a bit larger. That could be due to the compression values or that another png optimization tool such as pngcrush is needed to optimize further

**Comment by arnaudlewis** [comment]
Thanks for the help @fmw42 but I tried this with different images and sometimes the output is bigger, sometimes, the image is really ugly. it does not happen without the palette option but it's way too large.
Can you enlighten me on how a png optimization work? Why an optimized image should be reoptimized after a resize?

**Comment by palaiyacw** [comment]
@arnaudlewis I am also getting the similar issue. While resizing the png images output image comes out to be larger than the original image. Did you figure out any solution to this?

**Comment by saqibceoblogger-hub** [comment]
If your image looks too small or loses clarity after resizing, you’re definitely not alone—this is a very common issue.

When you try to [increase image size](https://increaseimagesize.net/), most tools simply stretch the pixels, which can make the image look blurry or pixelated. The real trick is not just resizing, but keeping quality intact while scaling up.

A better approach is to use smart upscaling tools that add detail instead of just stretching. These tools analyze the image and rebuild missing pixels so the result looks sharper and more natural. It works especially well for logos, social media graphics, and product images.

So instead of just “making it bigger,” focus on quality-first resizing methods. That’s how you get clean, professional results without losing clarity

**Comment by fmw42** [comment]
@saqibceoblogger-hub. and can you tell us algorithms for doing this without AI or even how to do AI to get these results?  Imagemagick is an image processor and not an AI tool. So it does not have these approaches. If you would like to add such tools to Imagemagick that would be great. Please contribute them
