### ISSUE TITLE
Why do some functions(Save Raw Data and Sharpen ) in ImageMagick V7 perform much worse than that in V6?

### ISSUE THREAD

**Issue by shelvsky** [ImageMagick/ImageMagick#1240]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

I tested functions of Saving RGB data and Sharpening with 2 jpeg image, but apparently the time consuming in IMv7 seemed much longer than that in IMv6. (My friend report to me that Resize seems to have the same problem, but I haven't tested personally yet) . the result listed below:( repeated 10 times each )

- testing Save RGB data with a 10000*10000 jpg, Average time consuming is 850ms for IMv7 and 640ms for IMv6
- testing Sharpen with a 1280*1024 jpg, Average time consuming is 1905ms for IMv7 and yet 842ms for IMv6

### Steps to Reproduce

- install ImageMagick 6.9.3-10 and ImageMagick 7.0.7-32 respectively with configuration command below:
./configure --with-jpeg=yes --with-webp=yes --disable-openmp --disable-opencl --disable-hdri --without-bzlib --with-quantum-depth=8 

- test saving rgb function with command below:
time /opt/ImageMagick7.0/bin/convert image.jpg image.rgb
time /opt/ImageMagick6.9/bin/convert image.jpg image.rgb

- test sharpening function with command below:
time /opt/ImageMagick6.9/bin/convert image.jpg -sharpen 0x3 out_image.jpg
time /opt/ImageMagick7.0/bin/convert image.jpg -sharpen 0x3 out_image.jpg

### System Configuration

- ImageMagick version: 6.9.3-10 and 7.0.7-32
- Environment (Operating system, version and so on): centos 7.2, CPU frequency 3.3GHz
- Additional information:

**Comment by urban-warrior** [comment]
See https://www.imagemagick.org/script/porting.php#hdri.  Disable HDRI to match the performance of ImageMagick version 6.

**Comment by shelvsky** [comment]
I have done that actually.
![_15336089539715](https://user-images.githubusercontent.com/3603525/43750822-bedeefee-9a2c-11e8-9d0c-793e251e5b7c.png)
But still, it didn't work. So am I doing that wrong?

**Comment by urban-warrior** [comment]
ImageMagick version 7, for some command-line options, has slower performance than ImageMagick version 6.  The reason is the an additional inner loop to support variable pixel channels with traits and masks.  See https://www.imagemagick.org/script/porting.php#channels.  IMv6 has a fixed 4 channels per pixel, whereas, IMv7 might have 1, 2, 3, 4, etc. channels.  IMv7 also checks the traits associated with a particular channel.  A channel might be copied, skipped, updated, or blended with alpha.  Our internal benchmark shows comparable performance for most of the command-line options but can be up to 15% slower for certain options such as -sharpen.
