### ISSUE TITLE
Annotate appears to disrespect parentheses

### ISSUE THREAD

**Issue by contentfree** [ImageMagick/ImageMagick#1244]
I'm trying to blur just one image in a set (for a drop shadow… and yes I know there's a specific `-shadow` option for this but still…)

These two commands should, in my opinion, output (roughly) the same thing (with respect to which images in the set get treated with blur & rotate):

```
convert -respect-parentheses -size 200x200 \( xc:transparent \) \
  \( -gravity center -background transparent caption:Testing \) \
  \( -gravity center -background transparent -rotate 45 caption:Testing \) \
  \( -gravity center -background transparent -blur 0x5 caption:Testing \) \
  -layers merge /tmp/test.png
```
and
```
convert -respect-parentheses -size 200x200 \( xc:transparent \) \
  \( -gravity center -background transparent -annotate +0+0 Testing \) \
  \( -gravity center -background transparent -rotate 45 -annotate +0+0 Testing \) \
  \( -gravity center -background transparent -blur 0x5 -annotate +0+0 Testing \) \
  -layers merge /tmp/test2.png
```

The first test correctly applies the blur and rotation to only the appropriate, specific images. However, the second test applies the rotation and the blur to every image prior to the rotate or blur operator and disregards the `-respect-parentheses` flag.

Is there some weird interaction with `-annotate` and `-respect-parentheses`?

**Comment by fmw42** [comment]
You misunderstand. 

caption: creates its own image from the -size and background color. Your first command using caption will make the image larger due to the rotation of the second caption image. 

Annotate does not. So you must make the annotate size larger to correspond. Also, it will do all processing on the one image, which in this case is -size 200x200 xc:transparent. -respect-parenthesis will not stop the -blur from blurring everything before it, since your parentheses are not working on separate images. Annotate also needs to know the pointsize, whereas caption: creates an appropriate pointsize. To make annotate work on separate images, you need to clone the relevant images. To rotate using -annotate, you do not use -rotate, but add the angles to the -annotate argument.

See 

The correct and minimally sufficient syntax for both your command is as follows:

```
convert -size 200x200 -gravity center -background transparent \
\( caption:"Testing" \) \
\( -rotate 45 caption:"Testing" \) \
\( -blur 0x5 caption:"Testing" \) \
-layers merge test.png

```

```
convert \( -size 284x284 xc:transparent \) \
-gravity center -pointsize 62 \
\( -clone 0 -annotate +0+0 "Testing" \) \
\( -clone 1 -blur 0x5 -annotate +0+0 "Testing" \) \
\( -clone 0 -annotate 45x45+0+0 "Testing" \) \
-background transparent -layers merge test2.png

```

**Comment by contentfree** [comment]
Hmm. Always something new to learn with ImageMagick. I've certainly spent a lot of time in the docs. Some things remain opaque. Thanks for the information and examples. 

Regarding your second example: Do you put parentheses around the initial xc:transparent so that it becomes clonable with `-clone 0`? Why do you `-clone 1` for the blur?
