### ISSUE TITLE
Assertion failed: id < (int) cache_view->number_threads (MagickCore/cache-view.c: QueueCacheViewAuthenticPixels: 989)

### ISSUE THREAD

**Issue by woody712** [ImageMagick/ImageMagick#1272]
In docker container

System: alpine 3.8
ImageMagick 7.0.7
PHP 7.2.8

Just do this,

`$img = new \Imagick(dirname(__FILE__)."/test.svg");` 

the error occur

**Comment by urban-warrior** [comment]
Download the latest ImageMagick release, 7.0.8-11.  Let us know if the problem persists with 7.0.8-11 and we will investigate further.

**Comment by csandanov** [comment]
As was originally reported at https://bugs.alpinelinux.org/issues/9190 the issue caused when imagemagick compiled with openmp, this option was disabled in edge repository and it solves the problem, and here's a PR to disable openmp in 3.8 https://github.com/alpinelinux/aports/pull/5402. 

But maybe it was a known issue that was fixed in 7.0.8.
