### ISSUE TITLE
Conditional resizing creates new image even if condition is unsatisfied

### ISSUE THREAD

**Issue by mallniya** [ImageMagick/ImageMagick#134]
Hello,

```
# convert -version
Version: ImageMagick 6.8.9-9 Q16 x86_64 2015-08-06 http://www.imagemagick.org
```

notice a lot of people complaining about inability to the following (assuming we have 5kx4000k jpg):
`convert test.jpg -resize 3840x3840\> test-0.jpg`
Naturally this will create test-0.jpg with size 3840x3072.
Expectations of running this command second time falls short:
`convert test-0.jpg -resize 3840x3840\> test-1.jpg`
This will create new file(with slighty different size and modification time) which I assume a bug.

Yeah, I know this can be solved with scripting, but why then ">" condition is even exist?

**Comment by mikayla-grace** [comment]
Not a bug, its a feature.  Conditional resize is useful, for example, if you are creating icons from a bunch of files.  You specify the maximum icon size and all images are conditionally resized to ensure its fits within a maximum size.  If the maximum size is, for example, is 128x128, a 256x256 image is resized to 128x128, but an image of size 64x64 remains at that size, 64x64.  The convert program, by design, always creates an output image or images.  For special use cases, such as yours, scripting is the proper solution.

**Comment by mallniya** [comment]
Alrighty then, just wanted to make this clear, thank you for prompt answer, @mikayla-grace. Still, it's strange, that not resized images is modified for whatever reason instead of just copying (if copy is a feature).

**Comment by sergeevabc** [comment]
Conditional resizing leaves much to be desired. Naturally one thinks ```$ magick 100x100.png -filter RobidouxSharp -resize "1000x>" -quality 100 -strip out.png``` will not distort small ```100x100.png```, because resizing criteria is not met. Yet ```-filter RobidouxSharp``` is applied in any case. Caveat [exists][1], but it’s hardly a consolation. So one has to invent a truly conditional pace within a batch/script as follows
```
...
set imgResize=-filter RobidouxSharp -distort Resize 1000x
for /f %%a in ('magick identify -format %%W "%~1"') do set imgWidth=%%a
if %imgWidth% leq 1000 set "imgResize="
magick "%~1" ... %imgResize% ... out.png
...
```

[1]: http://www.imagemagick.org/Usage/resize/
