### ISSUE TITLE
only 1 image converted from multiple image HEIC format

### ISSUE THREAD

**Issue by theBusterben** [ImageMagick/ImageMagick#1391]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
only 1 image converted from multiple image HEIC format

### Steps to Reproduce
-downloaded heic below, should contain multiple images (dynamic wallpaper)
-`# convert Jupiter.heic jupiter.jpg` gives only 1 image

### System Configuration
- ImageMagick version:
```
# identify -version
Version: ImageMagick 7.0.8-14 Q16 x86_64 2018-10-25 https://imagemagick.org
Copyright: © 1999-2018 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules OpenCL OpenMP 
Delegates (built-in): bzlib cairo fontconfig freetype gslib heic jbig jng jp2 jpeg lcms lqr ltdl lzma openexr pangocairo png ps raw rsvg tiff webp wmf x xml zlib
```
- Environment (Operating system, version and so on):
```
Arch, x86_64 GNU/Linux
```
- Additional information:
libheif 1.3.2
[testfile used](http://dynwalls.com/wallpapers/Jupiter.heic)

**Comment by urban-warrior** [comment]
ImageMagick reads only *one* image from an HEIC container.  Supporting multiple frames in the container is on our development schedule but we currently do not have an ETA.  In the mean-time, you are welcome to post a pull request with patches to support multiple HEIC frames.

**Comment by theBusterben** [comment]
thanks urban for the comment. Alas I didn't know it was on the dev schedule already. Afraid i'm not too savvy on the subject so i don't think i can be of much more help other than reporting it.

**Comment by dlemstra** [comment]
Support for this will be available in ` 7.0.8-50`.

**Comment by rprieto** [comment]
Hi @dlemstra,

Thank you for implementing this. I noticed this commit changes the default behaviour when processing HEIC files.

With version 7.0.8-49

```bash
$ magick convert burst.heic output.jpg
$ ls
# burst.heic output.jpg
```

With version 7.0.8-50

```bash
$ magick convert burst.heic output.jpg
$ ls
# burst.heic output-0.jpg output-1.jpg output-2.jpg output-3.jpg
```

This was a surprise working on http://thumbsup.github.io because we call ImageMagick the same way for all HEIC (burst or not). Since version 7.0.8-50 the `output.jpg` file is missing in the case of burst shots. Is this the expected default behaviour?

One way I found to get the old behaviour back:

```bash
$ magick convert -delete 1--1 burst.heic output.jpg
$ ls
# burst.heic output.jpg
```

Would this be your recommendation for opting-out of the multi-image processing? Is there any downside to always specifying the `-delete 1--1` flag when processing HEIC images?

Many thanks

**Comment by dlemstra** [comment]
You are no longer getting `output.jpg` because the file contains multiple images and that is why a number is added for each image. In your case `output.jpg` is now called `output-0.jpg`. If you want to opt out of this behavior and only get the first image you could specify reading the file as `burst.heic[0]` and only read the first image of the sequence. This should also be a bit more efficient because only the first image is read completely.

**Comment by rprieto** [comment]
Thank you for your very fast reply, and for confirming it's the expected new behaviour. I tried `[0]` and it works perfectly.
