### ISSUE TITLE
Inconsistent default background color

### ISSUE THREAD

**Issue by mlocati** [ImageMagick/ImageMagick#1400]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am using the latest version of ImageMagick
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When loading a PNG image and saving it as JPG, the background color is white. But if we resize it with MagickResizeImage the background color is black.

### Steps to Reproduce

```c
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <malloc.h>
#include <MagickWand/MagickWand.h>
    
void process(int scale)
{
   MagickWand *magick_wand;
   MagickWandGenesis();
   magick_wand = NewMagickWand();
   MagickReadImage(magick_wand, "./input.png");
   if (scale) {
      MagickResizeImage(magick_wand, 300, 106, UndefinedFilter);
   }
   MagickWriteImages(magick_wand, scale ? "./output-scaled.jpg" : "./output-unscaled.jpg", MagickTrue);
   MagickWandTerminus();
}

int main(int argc,char **argv) {
   process(0);
   process(1);
   return 0;
}
```

Where `input.png` is
![input](https://user-images.githubusercontent.com/928116/49241781-2d7f4a80-f409-11e8-81a4-d7f7605e5b1b.png)

The generated `output-unscaled.jpg` is
![output-unscaled](https://user-images.githubusercontent.com/928116/49241809-3c65fd00-f409-11e8-8373-999ba33039e4.jpg)

The generated `output-scaled.jpg` is
![output-scaled](https://user-images.githubusercontent.com/928116/49241815-425bde00-f409-11e8-9fc8-2a6b4d1920b2.jpg)

### System Configuration
- ImageMagick version: `master` branch (commit f51a75a129e5a260c49c7625446328f9f64000ed)
- Environment: `gcc:4.8` docker image
- Additional information:

**Comment by Danack** [comment]
Just to clarify, the issue is "sometimes when converting a png, the background looks white, other times like when it's resized it changes to black. Shouldn't it be consistent?" right?

**Comment by fmw42** [comment]
OK. I tested with IM 6.9.10.14 Q16 Mac OSX Sierra on the command line and can reproduce your results. Without scaling

`convert 49241781-2d7f4a80-f409-11e8-81a4-d7f7605e5b1b.png tmp.jpg
`
produces a white background where your original is transparent.

With scaling gives a black background.

`convert 49241781-2d7f4a80-f409-11e8-81a4-d7f7605e5b1b.png -resize 300x106 tmp.jpg
`
The reason it seems to happen is that your background colors is transparent white. So since JPG does not support transparency it just removes the alpha channel leaving your original white background.

You can see that by doing

`convert 49241781-2d7f4a80-f409-11e8-81a4-d7f7605e5b1b.png -alpha off tmp.png
`

Also identify -verbose on your input PNG shows

`Alpha: srgba(255,255,255,0)   #FFFFFF00`

I am not sure why the -resize changes the background color for the transparent region to black.

So I will leave a proper explanation to the IM developers.

**Comment by urban-warrior** [comment]
This is expected behavior.  When you resize with an alpha channel, the resizing blends each pixel channel with the corresponding alpha value.  See https://imagemagick.org/Usage/masking/.  One solution would be to turn off the alpha channel before resizing:

`convert 49241781-2d7f4a80-f409-11e8-81a4-d7f7605e5b1b.png -alpha off -resize 300x106 tmp.jpg`

Another solution is to composite the transparent image into a white background before resizing.
