### ISSUE TITLE
ImageMagick generating improper output image colors

### ISSUE THREAD

**Issue by DigneshGoyal** [ImageMagick/ImageMagick#142]
i have used below command
convert.exe test.ai -alpha off -resize 1024x768 -quality 95 -strip -auto-orient  output.jpg

Please find the problematic files in the attached zip

[Downloads.zip](https://github.com/ImageMagick/ImageMagick/files/152245/Downloads.zip)

**Comment by DigneshGoyal** [comment]
Can anyone help me on this.

**Comment by fmw42** [comment]
Your .ai input image is CMYK colorspace. I believe that you need to convert to sRGB before resizing. Try putting -colorspace sRGB before test.ai in your command above. Otherwise, use profiles after test.ai to convert it to sRGB. Note that Imagemagick does not know about spot colors or pantone colors. So there may still be some color differences.

**Comment by DigneshGoyal** [comment]
Thank you very much ...!!!  it worked
