### ISSUE TITLE
Undefined behavior for C++ drawing methods

### ISSUE THREAD

**Issue by jeroen** [ImageMagick/ImageMagick#1439]
The repository maintainers for the R bindings have complained that IM7 shows undefined behavior when running unit tests. Below are log files containing a stack trace leading to the ASAN error:

 - [clang-ASAN](https://www.stats.ox.ac.uk/pub/bdr/memtests/clang-ASAN/magick/00check.log)
 - [gcc-ASAN](https://www.stats.ox.ac.uk/pub/bdr/memtests/gcc-ASAN/magick/00check.log)

Unfortunately it's difficult to create a simple reproducible C++ example because the behavior appears after a few drawing operations. I hope the stack traces above can give a hint.

**Comment by urban-warrior** [comment]
We have a possible fix for the heap buffer overflow but cannot identify the memcpy problem in gcc-ASAN because there are no line numbers provided.  Can you download the ImageMagick master @ https://github.com/ImageMagick/ImageMagick/ and verify the heap buffer overflow patch and post the line number associated with the memcpy overlap?  We did try to replicate the problem but could not get our MagickToMime() call to fail.

**Comment by jeroen** [comment]
Thanks, I'll ask the admin to rebuild when the next version of IM is released.
