### ISSUE TITLE
Unable to render complex Text for Hindi

### ISSUE THREAD

**Issue by DontKnowMe** [ImageMagick/ImageMagick#1487]
## Configuration
OS: Ubuntu 16.04
Ram: 16 GB
Processor: Intel i7 4th generation

## Description
I am not able to produce Devanagari text properly, though it is mentioned in the ImageMagick description that it supports complex text layout. 

### Steps to Reproduce
convert -fill dodgerblue -background black -font 'Noto-Sans' -pointsize 72           label:'प्रतिक्रिया ' -bordercolor black -border 30x30           \( +clone -blur 0x25 -level 0%,50% \)           -compose screen -composite    neon_sign.gif

It is rendering like. But it should and must not render like this.
![image](https://user-images.githubusercontent.com/38942641/53121961-6b5cbc80-357b-11e9-8104-93582cf37a8a.png)

### System Configuration

- ImageMagick version: convert -version
Version: ImageMagick 6.8.9-9 Q16 x86_64 2018-09-28 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2014 ImageMagick Studio LLC
Features: DPC Modules OpenMP
Delegates: bzlib cairo djvu fftw fontconfig freetype jbig jng jpeg lcms lqr ltdl lzma openexr pangocairo png rsvg tiff wmf x xml zlib
- Environment (Operating system, version and so on):
- Additional information:

**Comment by fmw42** [comment]
I do not think you can just type your text as label:'प्रतिक्रिया '. You will need to write your text into a UTF-8 compatible text file, save the file, then use label:@textfile.txt to load your text so that IM can process. See https://imagemagick.org/Usage/text/#unicode. You may have to edit your policy.xml file to relax the restriction on the use of the @ notation. See policy.xml at https://imagemagick.org/script/resources.php

**Comment by DontKnowMe** [comment]
@fmw42 It is not working by passing through file also. I have tried with text 'एक बिलखती माँ' by keeping it in a file hindi.utf8 but I am getting 
![image](https://user-images.githubusercontent.com/38942641/53145422-2742d980-35c6-11e9-848a-bf63db47a2c2.png)
## How can I make sure that ImageMagick is using harfbuzz for supporting complex text layout?

**Comment by fmw42** [comment]
Your result above, looks like the characters that  you wrote as your text in your message. So what is wrong with it. Nevertheless, the noto sans font may not have those glyphs. Your characters are in what language?

**Comment by DontKnowMe** [comment]
They are not the same see the second word starting, It is not able to render it properly, it is misplacing matra, that's the indication that complex text layout is not working.

**Comment by fmw42** [comment]
I suspect that the noto sans font does not support those glyphs properly. But you did not answer my question about what keystrokes are needed to produce your characters in noto sans or any other font.  Does it work with other fonts?. 

I do not think you can just cut and past into the UTF-8 text file. You have to type the keystroked to create those characters in the UTF-8 compatible text file. So unless you provide information so that I can try to duplicated using a UTF-8 text file, I cannot help further. I am not a font expert.

**Comment by DontKnowMe** [comment]
Actually font does not have an issue.
![image](https://user-images.githubusercontent.com/38942641/53154936-eb1d7200-35e1-11e9-99ee-98eaea951831.png)

I have resolved the issue.
The imagemagick on it's own in basic text does not support complex Text layout.
For complex text layout we have to use pango.
Something like,
convert -background lightblue pango:"विकिपीडिया" pango.gif
