### ISSUE TITLE
AppImage distributions not fully self-contained

### ISSUE THREAD

**Issue by sagebind** [ImageMagick/ImageMagick#1592]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

The AppImage distributions of ImageMagick are not quite as self-contained as I'd think they should be. We'd like to use the AppImage files as a means of distributing the exact versions of ImageMagick we want to use in our server application.

Just downloading and inspecting the binaries in the AppImage in a vanilla Ubuntu Docker container, I see the following libraries missing that have to be installed separately in order for ImageMagick to run:

- libfontconfig.so.1
- libfreetype.so.6
- libX11.so.6
- libharfbuzz.so.0
- libfribidi.so.0
- libglib-2.0.so.0
- libexpat.so.1

I'd expect the AppImages to bundle these dependencies.

### Steps to Reproduce

Download recent AppImage from releases and attempt to run on a barebones Ubuntu server.

### System Configuration

- ImageMagick version: 7.0.8-49
- Environment (Operating system, version and so on): Ubuntu 18.04
- Additional information:

**Comment by probonopd** [comment]
We generally recommend not to privately bundle libraries which can be assumed to be part of every desktop distribution, because this might be perceived "bloated". As a result, most AppImages do not bundle _everything_ but only _everything that cannot reasonably be expected to be in the default desktop installation of every targeted distribution_.

You can see the list of libraries recommended not to bundle (because we assume that every desktop distribution has them) here:
https://github.com/AppImage/pkg2appimage/blob/master/excludelist

So it's a feature, not a bug.

That being said, some applications do bundle _everything_, but it's the exception rather than the rule.

**Comment by sagebind** [comment]
Fair enough, that exclude list should help us make sure we aren't missing any dependencies.

I do realize that a server environment isn't exactly the target use case for AppImages, but we want to use pre-compiled ImageMagick distributions for the time being (for specific versions indefinitely) because package repositories tend to drop off old versions, and the AppImages built and uploaded here seemed like a reasonable path for us.

**Comment by probonopd** [comment]
You should be able to install the remaining libraries from your distribution.
