### ISSUE TITLE
convert xc:white canvas.pnm creates a black image

### ISSUE THREAD

**Issue by cjmayo** [ImageMagick/ImageMagick#1632]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

`convert xc:white canvas.pnm` has been producing a white image for me with up to and including 7.0.8-46, since 7.0.8-50 it is producing a black image.

`convert xc:white canvas.pgm` works as expected.

(I see there where pnm fixes assigned to 7.0.8-50 #1612, #1613, #1614)
### Steps to Reproduce

1) ```convert -size 100x100 xc:white canvas.pnm```
2) View `canvas.pnm` and see it is black instead of the expected white

### System Configuration

- ImageMagick version: 7.0.8-50, 7.0.8-51, 7.0.8-53
- Environment (Operating system, version and so on): Gentoo Linux
- Additional information:

**Comment by fmw42** [comment]
This command works fine for me on IM 7.0.8.53 Q16 HDRI Mac OSX Sierra

`magick -size 100x100 xc:white canvas.pgm`

`magick display canvas.pgm`

For IM 7, use magick not convert, unless you have an alias set up.

**Comment by cjmayo** [comment]
> `magick -size 100x100 xc:white canvas.pgm`

works for me as above, the issue is with the ".pnm" extension.

Fair point about convert, mine is a symbolic link to magick.

**Comment by fmw42** [comment]
PNM is not a real format. It allows NetPBM to choose itself. The two proper formats are PGM and PPM and PBM. Both work for me. See https://en.wikipedia.org/wiki/Netpbm_format and http://netpbm.sourceforge.net/doc/pnm.html. Your command with suffix .pnm is ending up as PBM (portable bit map). From the latter, it says:

> Each bit represents a pixel: 1 is black, 0 is white

This may be the reason it turns out black.

I do not know if this is a feature of PBM format or a bug.

You should generally use the most appropriate format of PPM or PGM, in my opinion, and not rely upon NetPBM PNM to choose for you.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
