### ISSUE TITLE
Load more Memory & Cpu Usage

### ISSUE THREAD

**Issue by mukeshcp** [ImageMagick/ImageMagick#164]
Hi,
   I am using ImageMagick 6.8.

   While add below command to convert pdf file to png, It take more memory & cpu usage. And finally down the system (linux or window).

convert -density 300 -depth 8 -quality 85 655382767_1460008284.pdf[0-9] 655382767_1460008284.png

Please find attachment of pdf file & try to the above command.

Please let me know if found any solution.

[655382767_1460008284.pdf](https://github.com/ImageMagick/ImageMagick/files/208302/655382767_1460008284.pdf)

**Comment by mikayla-grace** [comment]
ImageMagick utilizes delegates for certain image / document types.  PDF is processed with Ghostscript and it may be consuming your memory.  To ensure, ImageMagick consumes minimal memory, add -limit area 0 to your command line.  This option forces ImageMagick to read / write pixels from and to disk rather than memory.  Its slower, but does ensure a significant reduction in memory consumption.
