### ISSUE TITLE
Preserving Exif header when converting TIFF --> TIFF

### ISSUE THREAD

**Issue by whugemann** [ImageMagick/ImageMagick#1674]
### Description

If you convert a TIFF file that contains Exif data to a TIFF file, the Exif data gets lost, even when you perform no operation at all, i.e. just copy the TIFF, say

magick input.tiff output.tiff

This cannot be influenced by the corresponding -set or -define options which should preserve the data.

See also my comment on https://www.imagemagick.org/discourse-server/viewtopic.php?f=1&t=36378&start=15

### System Configuration

- ImageMagick version: ImageMagick 7.0.8-23 Q16 x64 2019-01-02
- Environment (Operating system, version and so on): Windows 10 64bit

**Comment by urban-warrior** [comment]
The TIFF delegate library has support for EXIF but we found it to be buggy.  It often caused faults and exposed a security vector.  We eventually disabled EXIF.  Until we see improved support for EXIF in the TIFF delegate library, you will instead need to rely on post EXIF tools to copy, edit, or inject EXIF data.

**Comment by marsie321** [comment]
Are there any improvements. Which "TIFF delegate library" does IM use, because I would like to test it.

Thanks,

**Comment by fmw42** [comment]
Image magick uses libtif.  If there are features in libtif, your can customize the tiff delegate in delegates.xml to use those features.

**Comment by marsie321** [comment]
Thank you.

Tested libtiff via libtiff. And it does not read all the meta data, especially the GPSInfo/GPS directory is not translated/printed.
So if I understand your post correctly. Imagamagick would work, if libtiff is displaying all meta-info? I am not giving up and try to find a solution. Might it be possible to use exiv2 lib instead of libtiff?

Thanks, and below the commands and results.

**tiffinfo -j DJI_0018-7.tif**
TIFF Directory at offset 0x8 (8)
  Image Width: 640 Image Length: 512
  Resolution: 72, 72 pixels/inch
  Bits/Sample: 8
  Compression Scheme: None
  Photometric Interpretation: min-is-black
  Samples/Pixel: 1
  Rows/Strip: 12
  Planar Configuration: single image plane
  Software: LIBFORMAT (c) Pierre-e Gougelet
  XMLPacket (XMP Metadata):
<?xpacket begin="" id="W5M0MpCehiHzreSzNTczkc9d"?>
<x:xmpmeta xmlns:x="adobe:ns:meta/">
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
<rdf:Description rdf:about="DJI Meta Data"
xmlns:drone-dji="http://www.dji.com/drone-dji/1.0/"
xmlns:FLIR="http://www.dji.com/FLIR/1.0/"
><drone-dji:AbsoluteAltitude>620.353088</drone-dji:AbsoluteAltitude><drone-dji:RelativeAltitude>50.000000</drone-dji:RelativeAltitude><drone-dji:GimbalRollDegree>0.000000</drone-dji:GimbalRollDegree><drone-dji:GimbalYawDegree>-82.599998</drone-dji:GimbalYawDegree><drone-dji:GimbalPitchDegree>-90.000000</drone-dji:GimbalPitchDegree><drone-dji:FlightRollDegree>-0.400000</drone-dji:FlightRollDegree><drone-dji:FlightYawDegree>-55.700001</drone-dji:FlightYawDegree><drone-dji:FlightPitchDegree>1.100000</drone-dji:FlightPitchDegree><drone-dji:CamReverse>0</drone-dji:CamReverse><drone-dji:GimbalReverse>0</drone-dji:GimbalReverse><drone-dji:RtkFlag>0</drone-dji:RtkFlag><FLIR:TlinearGain>0.40</FLIR:TlinearGain>
<FLIR:BandName>
<rdf:Seq>
<rdf:li>LWIR</rdf:li>
</rdf:Seq>
</FLIR:BandName>
<FLIR:CentralWavelength>
<rdf:Seq>
<rdf:li>10000</rdf:li>
</rdf:Seq>
</FLIR:CentralWavelength>
<FLIR:WavelengthFWHM>
<rdf:Seq>
<rdf:li>4500</rdf:li>
</rdf:Seq>
</FLIR:WavelengthFWHM>
</rdf:Description>
</rdf:RDF>
</x:xmpmeta>
<?xpacket end="w"?>
  EXIFIFDOffset: 0x7a8
  GPSIFDOffset: 0x84e
TIFFReadCustomDirectory: Warning, Unknown field with tag 37393 (0x9211) encountered.
TIFF Directory at offset 0x7a8 (1960)
  FNumber: 1.250000
  DateTimeOriginal: 2021:01:20 14:26:40
  FocalLength: 19.000000
  Tag 37393: 0
  SubSecTimeOriginal: 34
  FocalPlaneXResolution: 3.840000
  FocalPlaneYResolution: 3.072000
  FocalPlaneResolutionUnit: 4
  SensingMethod: 15


**exiftool -v2 DJI_0018-7.tif**
  ExifToolVersion = 12.16
  FileName = DJI_0018-7.tif
  Directory = .
  FileSize = 329960
  FileModifyDate = 1611667634
  FileAccessDate = 1611667634
  FileInodeChangeDate = 1611667634
  FilePermissions = 33279
  FileType = TIFF
  FileTypeExtension = TIF
  MIMEType = image/tiff
  ExifByteOrder = II
  + [IFD0 directory with 17 entries]
  | 0)  ImageWidth = 640
  |     - Tag 0x0100 (4 bytes, int32u[1])
  | 1)  ImageHeight = 512
  |     - Tag 0x0101 (4 bytes, int32u[1])
  | 2)  BitsPerSample = 8
  |     - Tag 0x0102 (2 bytes, int16u[1])
  | 3)  Compression = 1
  |     - Tag 0x0103 (2 bytes, int16u[1])
  | 4)  PhotometricInterpretation = 1
  |     - Tag 0x0106 (2 bytes, int16u[1])
  | 5)  StripOffsets = 2280 9960 17640 25320 33000 40680 48360 56040 63720 71400 79080 [snip]
  |     - Tag 0x0111 (172 bytes, int32u[43])
  | 6)  SamplesPerPixel = 1
  |     - Tag 0x0115 (2 bytes, int16u[1])
  | 7)  RowsPerStrip = 12
  |     - Tag 0x0116 (4 bytes, int32u[1])
  | 8)  StripByteCounts = 7680 7680 7680 7680 7680 7680 7680 7680 7680 7680 7680 7680 7[snip]
  |     - Tag 0x0117 (172 bytes, int32u[43])
  | 9)  XResolution = 72 (72/1)
  |     - Tag 0x011a (8 bytes, rational64u[1])
  | 10) YResolution = 72 (72/1)
  |     - Tag 0x011b (8 bytes, rational64u[1])
  | 11) PlanarConfiguration = 1
  |     - Tag 0x011c (2 bytes, int16u[1])
  | 12) ResolutionUnit = 2
  |     - Tag 0x0128 (2 bytes, int16u[1])
  | 13) Software = LIBFORMAT (c) Pierre-e Gougelet
  |     - Tag 0x0131 (32 bytes, string[32])
  | 14) ApplicationNotes (SubDirectory) -->
  |     - Tag 0x02bc (1349 bytes, int8u[1349] read as undef[1349])
  | + [XMP directory, 1349 bytes]
  | | About = DJI Meta Data
  | | AbsoluteAltitude = 620.353088
  | | - Tag 'x:xmpmeta/rdf:RDF/rdf:Description/drone-dji:AbsoluteAltitude'
  | | RelativeAltitude = 50.000000
  | | - Tag 'x:xmpmeta/rdf:RDF/rdf:Description/drone-dji:RelativeAltitude'
  | | GimbalRollDegree = 0.000000
  | | - Tag 'x:xmpmeta/rdf:RDF/rdf:Description/drone-dji:GimbalRollDegree'
  | | GimbalYawDegree = -82.599998
  | | - Tag 'x:xmpmeta/rdf:RDF/rdf:Description/drone-dji:GimbalYawDegree'
  | | GimbalPitchDegree = -90.000000
  | | - Tag 'x:xmpmeta/rdf:RDF/rdf:Description/drone-dji:GimbalPitchDegree'
  | | FlightRollDegree = -0.400000
  | | - Tag 'x:xmpmeta/rdf:RDF/rdf:Description/drone-dji:FlightRollDegree'
  | | FlightYawDegree = -55.700001
  | | - Tag 'x:xmpmeta/rdf:RDF/rdf:Description/drone-dji:FlightYawDegree'
  | | FlightPitchDegree = 1.100000
  | | - Tag 'x:xmpmeta/rdf:RDF/rdf:Description/drone-dji:FlightPitchDegree'
  | | CamReverse = 0
  | | - Tag 'x:xmpmeta/rdf:RDF/rdf:Description/drone-dji:CamReverse'
  | | GimbalReverse = 0
  | | - Tag 'x:xmpmeta/rdf:RDF/rdf:Description/drone-dji:GimbalReverse'
  | | RtkFlag = 0
  | | - Tag 'x:xmpmeta/rdf:RDF/rdf:Description/drone-dji:RtkFlag'
  | | [adding XMP-FLIR:TlinearGain]
  | | TlinearGain = 0.40
  | | - Tag 'x:xmpmeta/rdf:RDF/rdf:Description/FLIR:TlinearGain'
  | | [adding XMP-FLIR:BandName]
  | | BandName = LWIR
  | | - Tag 'x:xmpmeta/rdf:RDF/rdf:Description/FLIR:BandName/rdf:Seq/rdf:li 10'
  | | [adding XMP-FLIR:CentralWavelength]
  | | CentralWavelength = 10000
  | | - Tag 'x:xmpmeta/rdf:RDF/rdf:Description/FLIR:CentralWavelength/rdf:Seq/rdf:li 10'
  | | [adding XMP-FLIR:WavelengthFWHM]
  | | WavelengthFWHM = 4500
  | | - Tag 'x:xmpmeta/rdf:RDF/rdf:Description/FLIR:WavelengthFWHM/rdf:Seq/rdf:li 10'
  | 15) ExifOffset (SubDirectory) -->
  |     - Tag 0x8769 (4 bytes, int32u[1])
  | + [ExifIFD directory with 9 entries]
  | | 0)  FNumber = 1.25 (1250/1000)
  | |     - Tag 0x829d (8 bytes, rational64u[1])
  | | 1)  DateTimeOriginal = 2021:01:20 14:26:40
  | |     - Tag 0x9003 (20 bytes, string[20])
  | | 2)  FocalLength = 19 (19/1)
  | |     - Tag 0x920a (8 bytes, rational64u[1])
  | | 3)  ImageNumber = 0
  | |     - Tag 0x9211 (4 bytes, int32u[1])
  | | 4)  SubSecTimeOriginal = 34
  | |     - Tag 0x9291 (3 bytes, string[3])
  | | 5)  FocalPlaneXResolution = 3.84 (3840/1000)
  | |     - Tag 0xa20e (8 bytes, rational64u[1])
  | | 6)  FocalPlaneYResolution = 3.072 (3072/1000)
  | |     - Tag 0xa20f (8 bytes, rational64u[1])
  | | 7)  FocalPlaneResolutionUnit = 4
  | |     - Tag 0xa210 (2 bytes, int16u[1])
  | | 8)  SensingMethod = 15
  | |     - Tag 0xa217 (2 bytes, int16u[1])
  | 16) GPSInfo (SubDirectory) -->
  |     - Tag 0x8825 (4 bytes, int32u[1])
  **| + [GPS directory with 7 entries]
  | | 0)  GPSLatitudeRef = N
  | |     - Tag 0x0001 (2 bytes, string[2])
  | | 1)  GPSLatitude = 48 4 31.321 (48/1 4/1 31321/1000)
  | |     - Tag 0x0002 (24 bytes, rational64u[3])
  | | 2)  GPSLongitudeRef = E
  | |     - Tag 0x0003 (2 bytes, string[2])
  | | 3)  GPSLongitude = 11 38 30.191 (11/1 38/1 30191/1000)
  | |     - Tag 0x0004 (24 bytes, rational64u[3])
  | | 4)  GPSAltitudeRef = 0
  | |     - Tag 0x0005 (1 bytes, int8u[1])
  | | 5)  GPSAltitude = 620.353 (620353/1000)
  | |     - Tag 0x0006 (8 bytes, rational64u[1])
  | | 6)  GPSMapDatum = WGS-84
  | |     - Tag 0x0012 (7 bytes, string[7])**

**Comment by urban-warrior** [comment]
Can you post a link to DJI_0018-7.tif.  We have tools to extract metadata from XMP profiles.   We may be able to provide a solution to this issue.

**Comment by fmw42** [comment]
See https://dev.exiv2.org/projects/exiv2/wiki/How_does_Exiv2_compare_to_Exiftool.  Also see https://exiftool.org/ExifTool.pdf and https://exiftool.org/history.html

**Comment by fmw42** [comment]
See https://exiftool.org/TagNames/XMP.html

**Comment by whugemann** [comment]
As I said above in https://www.imagemagick.org/discourse-server/viewtopic.php?f=1&t=36378&start=15, you can use Exiftool to transfer the data into another file. Exiftoll does not only read Exif information, but lots of other metadata formats. That is the solution I stayed with.

**Comment by marsie321** [comment]
Thank for your replies. 

I have tried both tools even more like ImageJ and NConvert. 
a + b) exiv2 and exiftool are great but exiv2 does not have multi-page functionality and exiftool can read the whole tiff (verbose mode) but if and how exif/meta data can be extracted for each page is unclear ("Phil" is having a look into it).
https://exiftool.org/forum/index.php?topic=12083

c) NConvert good@exif/meta but 8Bit. Otherwise ncovert is extracting single pages and exif/meta data. If and how 16Bit images can be read by nconvert will be checked by "Pierre" @ developer of nconvert. 
https://newsgroup.xnview.com/viewtopic.php?f=82&t=39704&p=167608#p167608
d) ImageJ and tiffsplit "no" meta data, but 16Bit tiff

So this multi-page tiff + exif is a bit tricky :-). 

But is a **general problem** with imagemagick identify and libtiff.  **(jpg + exif is OK, tif + exif is not reading gpsinfo).** 

I added the DJI_0018-7.tif (here it is converted as 8 Bit via nconvert). Additionally I added a reference geotagged image
GPS_location_stamped_with_GPStamper.jpg/tiff.
[images-zip.zip](https://github.com/ImageMagick/ImageMagick/files/5879738/images-zip.zip)


identify -verbose DJI_0018-7.tif | grep -i gps
identify: Unknown field with tag 37393 (0x9211) encountered. `TIFFReadCustomDirectory' @ warning/tiff.c/TIFFWarnings/1046.

nconvert -out jpeg -keepfiledate -keepcspace identify -verbose DJI_0018-7.tif # To write an jpg with gps info based on tif, if I use magick/convert I would loose gps info.

identify -verbose DJI_0018-7
[images-zip.zip](https://github.com/ImageMagick/ImageMagick/files/5879728/images-zip.zip)
.jpg | grep -i gps
    exif:GPSAltitude: 620353/1000
    exif:GPSAltitudeRef: 0
    exif:GPSInfo: 248
    exif:GPSLatitude: 48/1, 4/1, 31321/1000
    exif:GPSLatitudeRef: N
    exif:GPSLongitude: 11/1, 38/1, 30191/1000
    exif:GPSLongitudeRef: E
    exif:GPSMapDatum: WGS-84

**identify** -verbose GPS_location_stamped_with_GPStamper.**jpg** | grep -i gps
  Filename: GPS_location_stamped_with_GPStamper.jpg
    comment: Location stamped with GPStamper
    exif:GPSInfo: 3360
    exif:GPSLatitude: 41/1, 53/1, 12633/625
    exif:GPSLatitudeRef: N
    exif:GPSLongitude: 87/1, 37/1, 35223/1250
    exif:GPSLongitudeRef: W

**identify** -verbose GPS_location_stamped_with_GPStamper.**tif** | grep -i gps
  Filename: GPS_location_stamped_with_GPStamper.tif
identify: Wrong data type 2 for "UserComment"; tag ignored. `TIFFReadCustomDirectory' @ warning/tiff.c/TIFFWarnings/1046.
identify: Wrong data type 3 for "PixelXDimension"; tag ignored. `TIFFReadCustomDirectory' @ warning/tiff.c/TIFFWarnings/1046.
identify: Wrong data type 3 for "PixelYDimension"; tag ignored. `TIFFReadCustomDirectory' @ warning/tiff.c/TIFFWarnings/1046.

**Comment by marsie321** [comment]
[images-zip.zip](https://github.com/ImageMagick/ImageMagick/files/5879740/images-zip.zip)
