### ISSUE TITLE
how to use jpeg_turbo library in imageMagick

### ISSUE THREAD

**Issue by iamhgdabc** [ImageMagick/ImageMagick#1675]
### Prerequisites

- [ ] I have written a descriptive issue title
- [ ] I have verified that I am using the latest version of ImageMagick
- [ ] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Steps to Reproduce

iamgeMagick always link libjpeg, how to forbidden jpeg library and always link jpeg-turbo
### System Configuration

- ImageMagick version:
- Environment (Operating system, version and so on):
- Additional information:

**Comment by urban-warrior** [comment]
We ask for your operating system for a reason.  Any answer depends on what OS you're asking about.

**Comment by iamhgdabc** [comment]
> We ask for your operating system for a reason. Any answer depends on what OS you're asking about.

my operating system is centos6

**Comment by urban-warrior** [comment]
JPEG Turbo is a drop-in replacement for the default IJG JPEG delegate library.  If libjpeg points to the turbo library @ ImageMagick build time, it will automatically link to it.  Otherwise you'll need to set the CFLAGS environment variable to point to the JPEG Turbo headers and library before you issue the ./configure command-line script.  Before you build, check the output of the configure script to ensure it found the JPEG Turbo library.

**Comment by iamhgdabc** [comment]
> JPEG Turbo is a drop-in replacement for the default IJG JPEG delegate library. If libjpeg points to the turbo library @ ImageMagick build time, it will automatically link to it. Otherwise you'll need to set the CFLAGS environment variable to point to the JPEG Turbo headers and library before you issue the ./configure command-line script. Before you build, check the output of the configure script to ensure it found the JPEG Turbo library.

how to set the CFLAGS environment variable to point to the JPEG Turbo headers and library before run the ./configure command-line script. should i change ./configure file
