### ISSUE TITLE
How to Optimize the Speed of jpg encoding and decoding use ImageMagick library

### ISSUE THREAD

**Issue by iamhgdabc** [ImageMagick/ImageMagick#1679]
### Prerequisites

- [ ] I have written a descriptive issue title
- [ ] I have verified that I am using the latest version of ImageMagick
- [ ] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

my ImageMagick version is 6.9.10-44 and system is centos6, in my virtual machine， Using ImageMagick API (MagickReadImageBlob and MagickGetImageBlob) to encode and decode 1.8M JPEG images takes 1s(decode 250ms, encode 750ms)，but direct  use jpeg-turbo api just cost about 300ms, It's 3 times. has any way to improve the performance of ImageMagick
### System Configuration

- ImageMagick version:
- Environment (Operating system, version and so on):
- Additional information:

**Comment by urban-warrior** [comment]
ImageMagick leverages the JPEG delegate to read/write JPEG images.  Does your ImageMagick build link to jpeg-turbo?  If not, ImageMagick may be linked to the presumably slower JPEG delegate.  ImageMagick defaults to higher quality compression results of 92 rather than the default 75 likely reducing performance.  You can control the compression quality with the quality setting.  There are performance tradeoffs in ImageMagick as discussed @ https://imagemagick.org/script/architecture.php.  Finally, also try the latest release of ImageMagick when comparing performance.  There likely is performance improvements in the most recent releases.
