### ISSUE TITLE
MacPorts, the recommended way of installing ImageMagick, installs a version 6., instead of the newer 7.

### ISSUE THREAD

**Issue by NCryme** [ImageMagick/ImageMagick#1770]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

> We recommend MacPorts which custom builds ImageMagick in your environment (some users prefer Homebrew). Download MacPorts and type:
> `sudo port install ImageMagick`

Following the recommended steps, I find myself with an obsolete version of ImageMagick: ImageMagick 6.9.9-40 Q16 x86_64 2019-10-28. 

### Steps to Reproduce
Trying to install ImageMagick from MacPorts.

### System Configuration

- ImageMagick version: ImageMagick 6.9.9-40 Q16 x86_64 2019-10-28
- Environment (Operating system, version and so on): Mac OS X, 10.15, build 19A602. MacPorts version 2.6.2.
- Additional information:

**Comment by fmw42** [comment]
MacPorts is slow to update Imagemagick 6. This is a MacPorts issue, not one for Imagemagick. Please report/ask MacPorts to upgrade their port for imagemagick 6. However, they do not seem willing to support Imagemagick 7 as well as Imagemagick 6. I have asked already.

**Comment by NCryme** [comment]
I see, maybe if MacPorts never updates to ImageMagick 7, ImageMagick should not advertise MacPorts as the recommended way to install ImageMagick and/or propose more details on the Homebrew way?

Thank you, I'll try the other ways then!

**Comment by urban-warrior** [comment]
We updated the docs to recommend Homebrew.  It exports the latest ImageMagick releases under Mac OS.

**Comment by kencu** [comment]
The maintainer of ImageMagick on MacPorts found that a large number of projects were slow to adapt to the new requirements of ImageMagick 7 https://imagemagick.org/script/porting.php and would not properly work with the new version. Also, there was extensive testing required to see exactly which projects would and would not properly work with ImageMagick 7, and there were not a lot of volunteers to actually do that testing.

And as you may know, ImageMagick 6 remains very actively maintained -- here in Feb 2023, the last update to the ImageMagick 6 repo was just a few hours ago :> So the project made a decision to remain on ImageMagick 6 until that was all sorted out by the various upstreams.

It is certainly possible to carry two different versions of ImageMagick in parallel -- MacPorts offers about 12 different versions of the clang/llvm tree all at once, for example, and all can be used at any time depending on your system version -- but nobody has volunteered as yet to do that work, so MacPorts remains on ImageMagick 6 today as the most compatible version available.

If an enthusiast would like to do the work to allow the installation of multiple ImageMagick versions in parallel that don't conflict and could be selected by the user at will, that would be certainly acceptable. There is no-one against such a plan. A number of people have come forward to say they would like to do that, and often they felt they would find it easy to do so and could not understand why no-one had done it already -- but in the end, they never actually do it, as they get bogged down in the execution. As we all know, the idea takes but seconds -- the execution of the idea is another matter.

A few years have gone by since this issue was opened and since a deep dive into compatibility was undertaken -- if most projects are now compatible with ImageMagick 7, then a wholesale switch to that version is extremely trivial to accomplish (changing just a few digits in the current Portfile that builds it). Many users have tested out a switch in their own installation -- it takes only a few seconds to do it.
