### ISSUE TITLE
Unity build crash... working well on editor

### ISSUE THREAD

**Issue by PTEKALE** [ImageMagick/ImageMagick#1800]
hello,
I'm compositing two images one is from webcam texture and another is from local path for masking... in editor it works well But when i build unity solution it crashed without any error... Im using Magick.Net-Q8-64.dll 

Anyone have solution on this?

**Comment by dlemstra** [comment]
You created this issue in the wrong project. You should have created the issue here instead: https://github.com/dlemstra/Magick.NET. Please create the issue there but do include some extra information because I am missing a lot of information here. I suspect it is crashing because an exception is raised that are not catching but please continue the conversation the other repository.
