### ISSUE TITLE
Why are updates so frequent, and which version should I use as a deployment environment?

### ISSUE THREAD

**Issue by linjialiang** [ImageMagick/ImageMagick#1815]
Why are updates so frequent, and which version should I use as a deployment environment?

**Comment by fmw42** [comment]
Updates occur whenever there is a significant or security bug fix. Generally, update to the latest version in order to get the most feature and all bug fixes. There are rare times when a problem occurs with a release (and it may not compile correctly), so a new one must be released as soon as possible to fix that issue. Personally, I update my computer with each release as it comes out.

**Comment by linjialiang** [comment]
Thanks for your reply. I also recompiled the new version today and updated the PHP extension
