### ISSUE TITLE
evaluate-sequence is inefficient on large datasets

### ISSUE THREAD

**Issue by Avamander** [ImageMagick/ImageMagick#1824]
### Prerequisites
- [X] I have written a descriptive issue title
- [X] I have verified that I am using the latest version of ImageMagick 
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
`evaluate-sequence` uses enormous amounts of RAM and disk but is still takes hours to merge a few thousand frames. This is very slow and inefficient compared to Adobe's tools. I and probably many others would really love using `imagemagick` on larger datasets when sources are really noisy without any hacks. Maybe this task could be multithreaded better?

### Steps to Reproduce
1. Download a bit over a minute of: https://www.youtube.com/watch?v=yPUaEdgVGHA
2. Split the video into frames using ffmpeg
3. Execute `evaluate-sequence` in `median` mode

### System Configuration
Ryzen 9 3900x \w 32GiB of RAM \w M.2 SSD

- ImageMagick version: ImageMagick 6.9.10-23 Q16 x86_64 20190101
- Environment (Operating system, version and so on): Ubuntu 19.10, up-to-date

**Comment by fmw42** [comment]
What was your exact command line? The median is slow. ImageMagick convert has to load all the images into RAM and have enough room to store the same number of output images. Run times will depend upon how large your images are, how many frames, how much RAM you have available and whether the processing is multi-threaded. You might be better off processing the median filtering using mogrify, so that it loads only one image at a time, but loops over each image rather than loading them all at one time. Then when done, combine the images into your final video.

**Comment by Avamander** [comment]
I executed ``convert `ls` -evaluate-sequence median merged_median.bmp``

**Comment by Avamander** [comment]
> Run times will depend upon how large your images are, how many frames, how much RAM you have available and whether the processing is multi-threaded.

I had more memory available than the source images would take, it used it all and then gigabytes of disk cache.

**Comment by fmw42** [comment]
> I executed convert `ls` -evaluate-sequence median merged_median.bmp

That is not a valid ImageMagick command.

You ran out of memory, so ImageMagick used disk space to supplement it. You ran out of memory perhaps because you need twice the space needed for your input images, because ImageMagick needs to hold all the inputs and all the outputs at one time in your command. Multi-threading will not help if you run out of RAM and need to use disk cache.

**Comment by Avamander** [comment]
> That is not a valid ImageMagick command.

You're incorrect.

> You ran out of memory perhaps because you need twice the space needed for your input images

If input images are 900MiB then 6GiB of free RAM should be enough? Or not?

**Comment by fmw42** [comment]
Sorry, I missed the convert before your `ls`.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick late this week.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ likely by the weekend. 

In our testing, we reduced the runtime for 2000 1024x768 pixel images from 40 minutes to under 2 minutes.
