### ISSUE TITLE
latest version - gravity

### ISSUE THREAD

**Issue by vilords** [ImageMagick/ImageMagick#1879]
there is a bug in gravity north east ... at least when working using php imagick

letters get cut off (pushed more to the right than they are supposed to be)

previous versions behave fine ...

**Comment by dlemstra** [comment]
And how can we reproduce this? We have an issue template for a reason.

**Comment by Gornius** [comment]
This sounds like it's related to my problem.
Issue begins from version 7.0.10-2.

Expected behavior (ver. 7.0.10-1):
[Expected behavior](https://i.imgur.com/wIdaqQM.png)

Actual behavior (ver. 7.0.10-2)
[Actual behavior](https://i.imgur.com/4eVWYWM.png)

**Comment by fmw42** [comment]
It would help if you posted editable text for your code and not a screenshot. That way the developers can test your code without having to retype everything.

**Comment by vilords** [comment]
I experienced this problem with 7.0.10-3, but it was ok with -4 -5 -6 ... will need to check -8 on Monday.

**Comment by vilords** [comment]
works with -8 fine .. just checked

**Comment by Gornius** [comment]
The issue is: glyphs are not being centered properly (at least not like I would want them to). You would expect glyph's center to be in center of an image, while it looks like glyph's left side.

Command: `magick -size x120 label:"1" 1-7.0.10-1.png`:
![1-7 0 10-1](https://user-images.githubusercontent.com/34241360/80293633-2032d080-8761-11ea-95ea-8461a40a8a2c.png)
Command `magick -size x120 label:"1" 1-7.0.10-2.png`:
![1-7 0 10-2](https://user-images.githubusercontent.com/34241360/80293662-6c7e1080-8761-11ea-8618-30a111bd1137.png)
Command:`magick -size x120 label:"1" 1-7.0.10-7.png`:
![1-7 0 10-7](https://user-images.githubusercontent.com/34241360/80293687-b36c0600-8761-11ea-89e3-a4c67daecd61.png).

**Comment by fmw42** [comment]
I do not think the ImageMagick developers are going to port the fix into older versions. If it works fine in 7.0.10.8, then you will likely have to upgrade.

**Comment by Gornius** [comment]
Issue still persists in 1-7.0.10-8: `magick -size x120 label:"1" 1-7.0.10-8.png`:
![1-7 0 10-8](https://user-images.githubusercontent.com/34241360/80293925-4312b400-8764-11ea-94f8-b1b2a371e845.png)

**Comment by fmw42** [comment]
OK. Then not much more I can do. I will leave it to the IM developers for further analysis.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ http://www.imagemagick.org/download/beta/ by sometime tomorrow.
