### ISSUE TITLE
[Bug] issue with jpg conversion to pdf  

### ISSUE THREAD

**Issue by RAmbika** [ImageMagick/ImageMagick#2070]
### Description

The attached jpg (IMG_4849.jpg) in the below link cannot be converted to PDF properly.
When we open the file the it shows the error "insufficient data for an image" and results in blank pages but after scrolling pages up and down it loads 3x the original image(Sreenshot.PNG)
https://drive.google.com/drive/folders/1Z8iCk4WxHXn65zgEXoWUJBVoUeb88l6l?usp=sharing

### Steps to Reproduce

convert.exe "IMG_4849.jpg" -density "200" "out.PDF"
### System Configuration

- ImageMagick version: 7.0.10.0
- Environment (Operating system, version and so on): Windows 7
- Additional information:

**Comment by fmw42** [comment]
It converts fine for me on IM 7.0.10.14 Q16 Mac OSX Sierra. No error or warning messages. For IM 7, use magick.exe, not convert.exe.  Have you tried to upgrade to current version of IM.  Also what version of the JPG library are you using?  Perhaps that is old and needs upgrading. See

`magick -list format`

and look at the end of the line for JPG.

**Comment by d-ph** [comment]
Hello,

Allow me to interject, fmw42.

I came across this problem myself this week and I spent some time today to investigate. Here are my findings:

1. This defect manifests itself when a greyscale raster file with an RGB icc profile is attempted to be converted to pdf.

2. This is reproducible on latest imagemagick. I don't know why you weren't able to reproduce it. I have 3 test files that consistently fail for the same reason. For completeness, my imagemagick:
```
$ convert --version
Version: ImageMagick 7.0.10-14 Q16 x86_64 2020-05-23 https://imagemagick.org
Copyright: © 1999-2020 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules OpenMP(3.1) 
Delegates (built-in): bzlib freetype gslib heic jng jp2 jpeg lcms ltdl lzma openexr png ps tiff webp xml zlib
```

3. This is the same problem as the one worked out in the following thread: http://www.imagemagick.org/discourse-server/viewtopic.php?t=37761&p=173703

4. The quick&dirty solution is for the end user to either drop all icc profiles from greyscale images prior to conversion to pdf or drop the icc profiles only after ascertaining that they don't match the number of channels in the image (i.e. the image is 1 channel greyscale, but the profile is for a 3-channel RGB).

5. Even though imagemagick is doing the right thing during the conversion and the problem is clearly on the app that created the raster files, this issue is regrettably quite common. So it might be worthwhile to look for a solution on an imagemagick level (similar to how ghostscript gracefully attempts to work with poorly written pdf files).

---

Again, I'm not sure why you're not able to reproduce it but I'd like to ask you to try again. Once you manage to produce a corrupted pdf (it opens in latest Adobe Reader with error stating "Insufficient data for an image."), in order to prove that the error is icc-related, follow these steps:

0. Convert the IMG_4849.jpg mentioned in this ticket to IMG_4849.pdf.
1. Open the pdf in vim: `vim IMG_4849.pdf`.
2. Look for string: `ICCBased` (i.e. type: "/ICCBased" case-sensitive). Vim will scroll to the following region:
```
10 0 obj
[/ICCBased 11 0 R]
endobj
11 0 obj
<<
/N 1
/Filter /ASCII85Decode
/Length 12 0 R
/Alternate /DeviceGray
>>
stream
!!!'G@;p1%"98E%D/OH9;Fa%r=BSfM#N5Xf!!`K5!#>PW@:O@t5u:BOz5u:BOzzzz!!)`D!!
*'"!!(J"@;p1%ar6Os-%?J#311H1dHVHuzzzzzzz!!!!+A7]gl!!!#s!!!"1@rQI1!!!%1!!!
```
3. In the line after the word `stream`, replace the first `!` with letter `a`. I.e. the following edit should be done:
```
stream
a!!'G@;p1%"98E%D/OH9;Fa%r=BSfM#N5Xf!!`K5!#>PW@:O@t5u:BOz5u:BOzzzz!!)`D!!
*'"!!(J"@;p1%ar6Os-%?J#311H1dHVHuzzzzzzz!!!!+A7]gl!!!#s!!!"1@rQI1!!!%1!!!
```
4. Save the file.
5. Open the pdf in Adobe Reader. It works now.

By replacing the exclamation mark with letter "a" above, the embedded icc profile in the pdf file gets corrupted which makes Adobe Reader silently fall back to interpret the image data with `/DeviceGray` colourspace, which display the document correctly. Still, however, the pdf remains corrupted and e.g. ghostscript will fail to render it correctly to png.

As I mentioned, this is not imagemagick's fault that the pdf is corrupted because the source file itself is technically corrupted. But perhaps something may be done about it?

An immediate idea: when imagemagick determines that the number of channels in the image data doesn't match the number of channels the embedded icc profile is expecting, then imagemagick should not embed that profile when converting to pdf. Also, a warning should be printed to stderr that imagemagick silently dropped the profile because it didn't match the image data.

If it's not determinable how many channels an icc profile is for (I personally don't know how to do it), then a poor-man's method could be employed, where imagemagick uses "heuristics" to determine if the icc profile is for and RGB colourspace (the greyscale image vs rgb icc profile is arguably the 100% of cases of this problem). Sometimes the name of the profile suggests it's for RGB, e.g. `icc:description: GIMP built-in sRGB`, so that name could be strpos()'d. In the case of the file attached to the ticket, the name of the profile doesn't suggest the RGB colourspace, but the content of the icc profile does include a string "RGB " (alongside the rest of the binary data). I realise that strpos()'ing a content of a binary file is foolish, but maybe it's justified to err on that side, instead of making more people scratch their heads about the "insufficient data for an image" error, in case imagemagick incorrectly determines that the icc profile matches the greyscale image data.

Looking forward to your answer.

d-ph

**Comment by fmw42** [comment]
The command

magick IMG_4849.jpg -density 200 out.pdf

works fine with no error using IM 7.0.10.14 on Mac OSX Sierra.

I can open the PDF fine in Mac Preview. However, it does not open in Adobe Acrobat Reader compatible with my old OSX Sierra.

So there does seem to be some incompatibility. 

I will have to leave this to the IM developers to review.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow. 

In the mean-time, add -strip to your command-line.

**Comment by d-ph** [comment]
Good day Gents,

I tested IM 7.0.10-15 on Windows with the 2 files mentioned in this ticket, and the conversion now works correctly.

Thank you for a quick response and fix.

Have a good Saturday.

**Comment by d-ph** [comment]
Hello again,

It appears that on latest version 7.0.10-16, the `IMG_4849.jpg` fails to convert to pdf again. Would you be able to shed some light on this, please? I tested with the Windows portable binary.

d-ph

**Comment by fmw42** [comment]
I confirm that the command

magick IMG_4849.jpg -density 200 out.pdf

works fine with no error using **IM 7.0.10.16** on Mac OSX Sierra.

I can open the PDF fine in Mac Preview. **However, it does not open in Adobe Acrobat Reader compatible with my old OSX Sierra.**

**So there does seem to be some incompatibility.**

**I will have to leave this to the IM developers to review.**

**Comment by d-ph** [comment]
Hi,

Just wanted to mention that I retested this today and the conversion now works again on latest imagemagick version 7.0.10-19.

Thanks.

**Comment by princekream** [comment]
I've been having a similar issue all morning with another conversion and luckily found this page.

Downloaded the same file IMG_4849.jpg, converted to PDF and I'm getting the error "insufficient data for an image"

Running version 7.0.11-14, Windows 10, x64

**Comment by dlemstra** [comment]
The problem with the `IMG_4849.jpg` file is that the color profile has 3 channels but the image only has one channel. A work around for your issue is doing `magick IMG_4849.jpg -strip out.pdf` for now until we have a solution for this.

**Comment by cipri-tom** [comment]
May I add a photo that still fails to convert properly ?

[test-photo](https://user-images.githubusercontent.com/2991890/144854184-3862f93e-1f54-4f50-8e93-0e4946bca520.jpg) (not displayed as it is quite big).

Conversion seems to work, but the resulting PDF cannot be opened with Preview, although its thumbnail is rendered by QuickLook.

I'm on MacOS 11.6, if that matters. Thank you !

**Comment by fmw42** [comment]
I can convert it fine on IM 7.1.0-17 as 

`magick 144854184-3862f93e-1f54-4f50-8e93-0e4946bca520.jpg 144854184-3862f93e-1f54-4f50-8e93-0e4946bca520.pdf
`
It opens fine in Mac Preview on OSX Sierra. But Adobe Acrobat Reader (v20) will not open it.

**Comment by cipri-tom** [comment]
Thanks, @fmw42  ! I've upgraded: `  7.0.11-13_1 -> 7.1.0-17` and now I can see the result. 

But it is concerning that Adobe Acrobat Reader is not opening them 😬. I suppose this is also on Mac. Any idea of Windows?

Until your comment, I have used a different software to convert: [img2pdf](https://gitlab.mister-muffin.de/josch/img2pdf). Maybe the magick devs can get inspiration from there to solve this issue. I'd love to use only magick for all my tasks

**Comment by fmw42** [comment]
Adding -strip to the command makes it work for me and it opens in Adobe Reader. I also add -auto-orient to get the image in the right orientation.

`magick 144854184-3862f93e-1f54-4f50-8e93-0e4946bca520.jpg -auto-orient -strip 144854184-3862f93e-1f54-4f50-8e93-0e4946bca520.pdf`
