### ISSUE TITLE
Possible issues with PDF output

### ISSUE THREAD

**Issue by fmw42** [ImageMagick/ImageMagick#2111]
IM 7.0.10.16 Q16  Mac OSX Sierra

Two possible issue with creating PDF output.

1) I cannot get rid of the alpha channel

2) The output does not preserve the specified density or units and always has density 72 and undefined units

Input:

[bw.pdf](https://github.com/ImageMagick/ImageMagick/files/4737940/bw.pdf)

I have tried each of the following:

```
magick -units pixelsperinch -density 300 bw.pdf -alpha off -colorspace gray -threshold 50% x.pdf

magick -units pixelsperinch -density 300 bw.pdf -alpha deactivate -colorspace gray -threshold 50% x.pdf

magick -units pixelsperinch -density 300 bw.pdf -colorspace gray -background white -flatten -threshold 50% x.pdf

```
Result:

[x.pdf](https://github.com/ImageMagick/ImageMagick/files/4737947/x.pdf)

```
Filename: x.pdf
  Format: PDF (Portable Document Format)
  Mime type: application/pdf
  Class: DirectClass
  Geometry: 842x595+0+0
  Resolution: 72x72
  Print size: 11.6944x8.26389
  Units: Undefined
  Colorspace: sRGB
  Type: Bilevel
  Base type: Undefined
  Endianness: Undefined
  Depth: 16/1-bit
  Channel depth:
    red: 1-bit
    green: 1-bit
    blue: 1-bit
    alpha: 1-bit

```

**Comment by urban-warrior** [comment]
We have limited control over PDF because we leverage Ghostscript to render it and the rendering depends on the device we leverage.  The default device is `pngalpha` which returns the alpha channel. You can choose another Ghostscript device, such as `pnmraw` by editing the ImageMagick `delegates.xml ` configuration file.  Or you can add `-alpha none`, _after_ you read the PDF.

PDF's are resolution independent.  As such, the resolution is not stored in the PDF image files.  Instead, you can render it at whatever resolution you want.

**Comment by fmw42** [comment]
But I thought you do not use GS to write the PDF. So if I turn off alpha, why does it not stay turned off?

Also there does not seem to be a -alpha none option

`magick -units pixelsperinch -density 300 bw.pdf -alpha none -colorspace gray -threshold 50% x.pdf`

magick: UnrecognizedAlphaChannelOption '-alpha' 'none' at CLI arg 6 @ error/operation.c/CLISimpleOperatorImage/1779.
