### ISSUE TITLE
Lot of Operation canceled' @ fatal/cache.c/GetImagePixelCache/1885

### ISSUE THREAD

**Issue by remicollet** [ImageMagick/ImageMagick#217]
Version 6.9.4-1 was ok
Observed since 6.9.4-3

See https://github.com/mkoppanen/imagick/issues/158

**Comment by dlemstra** [comment]
It might be possible that this is caused by the OpenCL changed that were done recently. I suspect that it is taking this long because it is bench marking the devices. Is it possible to disable the time limit you set on the operation and try to run it? It should then create a file called `ImagemagickOpenCLDeviceProfile` in your home directory in a folder called.ImageMagick (not sure about the name, I'm a windows guy). And you should be able to run the test without any problems. You might want to change your tests and add a test that runs as the first one and does an OpenCL operation without a time limit. Not sure if that is possible with your unit tests software though.

**Comment by mikayla-grace** [comment]
The unit test is setting the 'time' resource in ImageMagick.  Increase this limit or set it to 0 and the unit tests should run to completion.

**Comment by Danack** [comment]
> I suspect that it is taking this long because it is bench marking the devices.

If that's the case, is there a way to disable this benchmarking?
When the automated tests run for Imagick, there are quite a few different builds done: https://travis-ci.org/mkoppanen/imagick/builds/135732833

As the environment is destroyed and re-created for each run, the benchmarking results won't be stored, and would need to be run each time.

**Comment by remicollet** [comment]
@mikayla-grace please see https://github.com/mkoppanen/imagick/issues/158#issuecomment-225167349

**Comment by mikayla-grace** [comment]
Its difficult for us to debug. If you can reproduce the problem with the ImageMagick command line or one of the supported API's such as MagickWand, we can be more helpful. The time limit is fairly straightforward. By default its ignored. If you set a time limit policy in policy.xml or call MagickSetResourceLimit() with a time limit, ImageMagick periodically checks the run time against the time limit and if its exceeds the limit it throws an exception and exits. We're not sure how its done in IMagick but from the command line you can view the current policy settings, including any time limit with this command: convert -list resource. Here we set a time lime and review the setting:

```
-> convert -limit time  10 -list resource
Resource limits:
  Width: 107.4MP
  Height: 107.4MP
  Area: 50.541GB
  Memory: 23.535GiB
  Map: 47.07GiB
  Disk: unlimited
  File: 768
  Thread: 8
  Throttle: 0
  Time: 10
```

**Comment by remicollet** [comment]
Using pr #219 fix this issue, imagick test suite pass.
