### ISSUE TITLE
Density sets density_unit to 0

### ISSUE THREAD

**Issue by DemiImp** [ImageMagick/ImageMagick#228]
Back on Sept 25, 2013 a commit was made that introduced a bug: http://git.imagemagick.org/repos/ImageMagick/commit/d214ceb1ffb7d3bdc68a4d862cadd1a6e0801947

You can see that the code defaults to density_unit to 1 (pixels per inch) at line 2129. But when the x_resolution and y_resolution are both not 0, the density_unit changes to 0 (aspect ratio) at line 2145 (which was added in the commit mentioned above).

ImageMagick docs explicitly states "The default unit of measure is in dots per inch (DPI). The -units option may be used to select dots per centimeter instead." ( http://www.imagemagick.org/script/command-line-options.php#density )

I'm not sure if this change was added for a different reason, but either the code or the docs are now wrong.  For those who are updating from an earlier version of Ubuntu (14.04) to a newer version (16.04), people may find that their code no longer works correctly... this makes me inclined to suggest that line 2145 should be removed so things function as the docs describe.

**Comment by mikayla-grace** [comment]
Its likely a transient bug.  In recent releases of ImageMagick, the JPEG density unit member is only set if the image units is explicitly set to pixels-per-inch or pixels-per-centimeter.

**Comment by DemiImp** [comment]
I understand that, but ImageMagick doesn't behave as the documentation states it should.

**Comment by DemiImp** [comment]
I don't know why the question label was added to this.  There's either a bug in the code or a bug in the documentation.

**Comment by dlemstra** [comment]
You are taking the remark out of context, this is about reading an image:

> This option specifies the image resolution to store while encoding a raster image or the canvas resolution while rendering (reading) vector formats such as Postscript, PDF, WMF, and SVG into a raster image. Image resolution provides the unit of measure to apply when rendering to an output device or raster image. The default unit of measure is in dots per inch (DPI). The -units option may be used to select dots per centimeter instead.

And this is mentioned about writing an image:

> If the file format supports it, this option may be used to update the stored image resolution. Note that Photoshop stores and obtains image resolution from a proprietary embedded profile. If this profile is not stripped from the image, then Photoshop will continue to treat the image using its former resolution, ignoring the image resolution specified in the standard file header.

**Comment by DemiImp** [comment]
I'm not sure if I understand correctly.  A units value of 0 means that the xdensity and ydensity should be interpreted as the pixel aspect ratio.

Please refer to the specification on page 5: https://www.w3.org/Graphics/JPEG/jfif3.pdf

If ImageMagick reads a units value of 0 but treats it as 1 up until writing a file, that sounds like it would be an entirely different bug.  Can you further explain what ImageMagick's documentation means by "the default unit of measure"?  How is default unit type only for reading but not writing?

**Comment by dlemstra** [comment]
You have completely lost me... I have no idea what you are telling or asking me.

My previous post does not talk about reading a JPG file. It states that the -density option is used when you are reading vector formats and that you can use the -units option together with that. But we might need to change the way we document it as Snibgo mentioned here: https://www.imagemagick.org/discourse-server/viewtopic.php?f=3&p=135094#p135094

**Comment by jenslundgaard** [comment]
If anybody has battled with ImageMagick's seeming inability to apply the -density tag in certain situations, I vote for this being a bug! : )

The most useful documentation in relation to this is probably here http://www.imagemagick.org/Usage/basics/#density
...which leads the user to believe that the problem is something to do with an embedded 8bim Photoshop profile or that the xResolution / yResolution isn't set

Except it isn't - at least not for our files after tearing my hair out for an entire evening.

The issue for us was that if the source file is a vector file (e.g. .ai or .eps) and you use ImageMagick (via Ghostscript) to transform to a bitmap with -density=xxx then this seemingly doesn't get set, but the real problem isn't that the densities (xResolution/yResolution etc) don't get set, it's that the *unit of measure* don't get set (or rather remains the default of PixelsPerInch)
As soon as you add  -units PixelsPerInch before the -density modifier then everything works as expected - or rather it works in the way that I understand the documentation to read - i.e. agree with Demilmp!!

**Comment by DemiImp** [comment]
Just to make sure I'm understanding correctly... So the "default unit of measure" is only "PixelsPerInch" when using vector formats?  If so, it's not clear at all that the docs are supposed to be read like that.  The docs should say that you should always specify a -units except when using vector formats where the default is PixelPerInch

I'm not sure why this was closed without the documentation getting clarified or without any code changes.

**Comment by jenslundgaard** [comment]
Hi Demilmp
Thanks for the quick reply!

It's the other way round, the unit of measure is only PixelsPerInch when the original source is NOT a vector - i.e. if it's a bitmap.
If you convert a vector (e.g. .ai or .eps) then -units is blank (or at least it gets set to something which neither Windows nor Photoshop can understand) 

e.g.
if the input source is a bitmap file then the following will result in a 150dpi output file
_magick someInputBitmapFile.png -density 150 someOutputBitmapFile.png_


but if the input source is a vector (which of course gets pre-processed with GhostScript which may be the fly in the ointment rather than ImageMagick itself) then the below command will result in a "150nothing" file, which both Windows and Photoshop will display as 96 and 72 dpi respectively because there isn't any unit of measure to go with the number of 150 so I guess it just assumed the default screen res
_magick someInputVectorFile.ai -density 150 someOutputBitmapFile.png_

It's pretty confusing that the same command results in two different outputs depending on input filetype so I would certainly vote for having ImageMagick "actively" defaulting to -units=PixelsPerInch so the output is consistent.
Hope that makes sense
