### ISSUE TITLE
API changes in Magick++7

### ISSUE THREAD

**Issue by jeroen** [ImageMagick/ImageMagick#236]
The following functions are documented and working on IMv6 however did not compile on IMv7.
- `Magick::opacityImage`
- `Magick::levelChannelImage`
- `Magick::matteColorImage`
- `Magick::matteImage`

Also:
- `Magick::quantizeImages` changed signature

And:
- `penColorImage` is in the header but fails to link

Is this expected? Where can I find a complete list of API changes in Magick++ 7?

```
image-manipulate.cpp: In function 'XPtrImage magick_image_opacity(XPtrImage, std::size_t)':
image-manipulate.cpp:256:46: error: 'opacityImage' is not a member of 'Magick'
   for_each ( output->begin(), output->end(), Magick::opacityImage(opacity));
                                              ^
image-manipulate.cpp: In function 'XPtrImage magick_image_level(XPtrImage, double, double, double, int)':
image-manipulate.cpp:264:49: error: 'levelChannelImage' is not a member of 'Magick'
      for_each ( output->begin(), output->end(), Magick::levelChannelImage((Magick::ChannelType) channel, black_point, white_point, mid_point));
                                                 ^
image-manipulate.cpp: In function 'XPtrImage magick_image_matte(XPtrImage, bool, Rcpp::String)':
image-manipulate.cpp:275:48: error: 'matteColorImage' is not a member of 'Magick'
     for_each ( output->begin(), output->end(), Magick::matteColorImage(color.get_cstring()));
                                                ^
image-manipulate.cpp:276:46: error: 'matteImage' is not a member of 'Magick'
   for_each ( output->begin(), output->end(), Magick::matteImage(matte));
                                              ^
```

Log for `QuantizeImages`:

```
../windows/imagemagick-7.0.2.4/include/ImageMagick-7/Magick++/STL.h: In instantiation of 'void Magick::quantizeImages(InputIterator, InputIterator, bool) [with InputIterator = __gnu_cxx::__normal_iterator<Magick::Image*, std::vector<Magick::Image> >]':
image-stl.cpp:140:48:   required from here
../windows/imagemagick-7.0.2.4/include/ImageMagick-7/Magick++/STL.h:2626:30: error: too few arguments to function 'MagickCore::MagickBooleanType MagickCore::QuantizeImages(const QuantizeInfo*, MagickCore::Image*, MagickCore::ExceptionInfo*)'
              first_->image() );
                              ^
In file included from ../windows/imagemagick-7.0.2.4/include/ImageMagick-7/MagickCore/MagickCore.h:139:0,
                 from ../windows/imagemagick-7.0.2.4/include/ImageMagick-7/Magick++/Include.h:42,
                 from ../windows/imagemagick-7.0.2.4/include/ImageMagick-7/Magick++.h:10,
                 from magick_types.h:3,
                 from image-stl.cpp:6:
../windows/imagemagick-7.0.2.4/include/ImageMagick-7/MagickCore/quantize.h:61:3: note: declared here
   QuantizeImages(const QuantizeInfo *,Image *,ExceptionInfo *),
   ^
```

Log for `penColorImage`:

```
image-manipulate.o:image-manipulate.cpp:(.text+0x475d): undefined reference to `Magick::penColorImage::penColorImage(Magick::Color const&)'
image-manipulate.o:image-manipulate.cpp:(.text+0x4798): undefined reference to `Magick::penColorImage::operator()(Magick::Image&) const'
collect2.exe: error: ld returned 1 exit status
```

**Comment by olear** [comment]
Alpha changed in IM7, so matte/opacity functions was renamed to alpha.

image.matte() => image.alpha() etc etc.

**Comment by jeroenooms** [comment]
@olear is The porting documentation states that: 

> The Magick++ and PerlMagick API's have not changed and match that of the ImageMagick version 6.

Is this still the case? Maybe consider keeping legacy wrappers for `matteImage` etc in the C++ API?

**Comment by dlemstra** [comment]
I apologize for the confusion. We did make some minor changes to the Magick++ API. We renamed matte to alpha in a lot of places. The QuantizeImages method has an issue with calling the C API method, I will push a patch for that later today.

**Comment by jeroenooms** [comment]
Can I suggest to either emphasize API changes in the C++ documentation, or, including compatibility wrappers with the old names in IM7 with behind some `DEPRECATED` macro?

**Comment by dlemstra** [comment]
We will update the documentation.

**Comment by ferdnyc** [comment]
Hi, as noted in the bug report I just referenced this from (OpenShot/libopenshot#162), the rename from `matte()` to `alpha()` in ImageMagick 7 broke compilation of libopenshot, since the code still uses `matte()`. 

Retaining IM6 compatibility is important to us, and since I guess there are no wrappers in either IM6 or IM7 to facilitate writing universally-compatible code, does IM7 provide `#define`s to conditionalize code based on the API version in use? 

Also, the outcome of this was "We will update the documentation.", but it took me no small amount of time to track down the `matte()` deprecation because:
1. It's never _directly_ documented as being deprecated **anywhere**, as far as I can tell.
1. `matte()` simply disappears from [the API autodocs for the Image class](https://imagemagick.org/api/Magick++/classMagick_1_1Image.html), with no indication that `alpha()` should be used in its place. It's difficult to find information based on what's _not_ there, so that's of very little use to anyone trying to update their IM6 code to IM7.
1. The [Porting to ImageMagick version 7](http://www.imagemagick.org/script/porting.php) document _nowhere_ mentions the `matte()` attribute rename.
   1. It lists the `DrawMatte()` -> `DrawAlpha()` rename
   1. There's a note that "The `matte` primitive is now `alpha`" for the `-draw` command line option

   But the removal/rename of `matte()` as a `Magick::Image` attribute method is never once addressed in that entire document.
1. [Porting to ImageMagick version 7](http://www.imagemagick.org/script/porting.php) in fact claims, right at the top:
   > The Magick++ and PerlMagick API's have not changed and matches that of the ImageMagick version 6.
1. The _non_-autodoc API documentation still lists `matte()` as a valid attribute. It appears on both of the following pages:
   1. http://www.imagemagick.org/api/Image++.php
   1. http://www.imagemagick.org/Magick++/Image++.html

Please, at _least_ clearly and explicitly document the **deprecation** of `matte()` (in _all_ currently-available documentation where it's mentioned), and provide instruction that `alpha()` is to be used in its place.

If you really wanted to help your API users, adding `alpha()` as a wrapper/alias for `matte()` in future releases of IM6 (so that code can be ported to IM7 without losing compatibility with **all** versions of IM6) would be welcome. (Actually, doing that long **before** `matte()` was removed in IM7 would've been even more welcome.)

**Comment by jeroen** [comment]
Hi @ferdnyc perhaps you can borrow some ideas from the R bindings. See for example here: https://github.com/cran/magick/blob/master/src/magick_types.h#L34-L63

**Comment by ferdnyc** [comment]
Thanks @jeroen , `MagickLibVersion` looks like it should work nicely for conditionalizing the code. I see that it's defined in `ImageMagick-6/magick/version-64.h` as well as in IM7.

I stil urge the IM team to update the web docs, though. Anyone looking for info on the changes is likely to find those _long_ before they make it to this GitHub issue, and this appears to be just about the only place where it's really spelled out that `matte()` is no longer supported in IM7 and should be replaced with `alpha()`.
