### ISSUE TITLE
ImageMagick can't detect animated PNG

### ISSUE THREAD

**Issue by kamenik** [ImageMagick/ImageMagick#24]
Identify animated.png  doesn't return data about animation. Used with JMagick, isAnimatedImage() return false for animated png.

**Comment by urban-warrior** [comment]
No such thing as an animated PNG.  Do you mean MNG?  We did not write nor do we support JMagick.  If you reproduce the problem from the command-line or from MagickCore, we will investigate further.

**Comment by kamenik** [comment]
Animated PNG - https://en.wikipedia.org/wiki/APNG - it is extension to PNG, similarly as animated GIF is extension to 'normal' GIF.

I know, you are not author of JMagick, but it is just wrapper around your libs. It detects animated GIF correctly.

**Comment by urban-warrior** [comment]
When asked if we support APNG, the PNG developer (Glenn who develops libpng) says: No.  We detect and ignore the APNG chunks "acTL", "fcTL", and "fdAT".

**Comment by revolter** [comment]
Well. it's 2017 now, ten years later after Glenn said that. Could you reconsider this?

See https://github.com/onevcat/APNGKit:

> Apple recently supported APNG in both desktop and mobile Safari. Microsoft Edge and Chrome are also considering adding APNG support since it is already officially added in WebKit core.

Most probably the `.png` was used to maintain backwards compatibility.

**Comment by revolter** [comment]
@urban-warrior, Any take take on what I said?

**Comment by glennrp** [comment]
The PNG Development Group has not changed its stance regarding APNG.  It's a little amusing that the original proponents of APNG have found a need to use ".apng" under some circumstances, in order to distinguish between APNG and PNG datastreams, and they've declared a MIME type for APNG.  That approach would have been agreeable to the PNG group.

**Comment by QuantumRevenger** [comment]
I hope this is added to ImageMagick soon as its now available in both Chrome / Firefox now. I am yet to find out whether apng supports playing certain frames once, and looping other sections.

**Comment by glennrp** [comment]
On Sat, Sep 16, 2017 at 1:48 PM, QuantumRevenger <notifications@github.com>
wrote:

> I hope this is added to ImageMagick soon as its now available in both
> Chrome / Firefox now. I am yet to find out whether apng supports playing
> certain frames once, and looping other sections.
>

APNG only supports looping the entire animation.

**Comment by QuantumRevenger** [comment]
That's a shame but thanks for letting me know. If anyone knows of a format which can (if exists) would be appreciated.

Also, will APNG offer better sizes compared to gif? (Does Image Magick support it?)

**Comment by glennrp** [comment]
The PNG proposed "mPNG" chunk supports arbitrary reuse of frames.
http://libpng.download/documents/proposals/history/png-mpng-proposal-20070411.txt
Proposed 10 years ago and pretty much forgotten.

APNG doesn't provide much better sizes than gif -- maybe a little due to deflate compression versus LZW compresion -- mainly it offers more colors and partial transparency.

**Comment by LudwigvonWu** [comment]
Sorry if I ask, but what about naming the libpng supporting the APNG specification "libapng" and forcing the output file extension to be ".apng" instead of ".png" whenever a PNG file containing the acTL, fcTL and fdAT chunks is created by ImageMagick? This way the PNG Development Group would have their view on PNG and APNG enforced, while from my tests a large majority of the current software that supports APNG files with ".png" extension also support APNG files with the ".apng" extension, including Goggle Chrome and Mozilla Firefox. The possible lack of backward compatibility wouldn't be a deal breaker, now that 70% of the browsers support APNG files. Not to say that the APNG Specification itself doesn't specify which file extension should be used for the output file.
I think everyone would win, and as I said before, many users of ImageMagick might not actually mind the forced ".apng" extension, some of them would probably welcome said behavior.

**Comment by KrasnayaPloshchad** [comment]
Mozilla has a patch for this.
https://dxr.mozilla.org/mozilla-central/source/media/libpng/apng.patch

**Comment by 8spinach** [comment]
it was a bad call for the png group to not support apng, especially citing the gif (most popular animation format on the web) as a reason; support for apng in imagemagick, also, shouldn’t depend on the png group’s decision, especially now that the bulk of the work is done and a patch is available.

**Comment by Schweinepriester** [comment]
+1 for APNG, since in 2019 it is already available for >85 % of the web and most (relevant) browsers: <https://caniuse.com/#feat=apng>

**Comment by TheEssem** [comment]
+1. I have seen multiple websites and apps use this format and it seems superior to GIF in nearly every way. Forget about the PNG Group's decision; that was nearly 13 years ago and the web has drastically evolved since that time. apngasm/apngdis could be a good starting point for adding support: http://apngasm.sourceforge.net/

**Comment by AuracleTech** [comment]
Yeah this is 2020. Time to support APNG.
Gifs used to be deprecated too, then we required them.
Now APNG is the new Gif. we need APNGs. They are better in every way possible.
Re-open the issue!

**Comment by forresthopkinsa** [comment]
> APNG is the new GIF

Do we *need* a new naive animated image format? Why can't the world move on to properly compressed videos? WEBM has caught on in a lot of places for autoplay+looping animations.

**Comment by AuracleTech** [comment]
> > APNG is the new GIF
> 
> Do we _need_ a new naive animated image format? Why can't the world move on to properly compressed videos? WEBM has caught on in a lot of places for autoplay+looping animations.

APNG supports transparency compared WEBM, and by the way it's not new, and all browser supports it.

**Comment by forresthopkinsa** [comment]
> by the way it's not new

I was just quoting you, friend.

I believe that webm actually *does* support alpha transparency.

**Comment by fmw42** [comment]
The two are not equivalent. WEBM is a video format which APNG is an animated image format similar to GIF.

**Comment by AuracleTech** [comment]
I still want my APNG

**Comment by 8spinach** [comment]
> I believe that webm actually _does_ support alpha transparency.

there's no browser support. meanwhile, every browser supports apng.

**Comment by forresthopkinsa** [comment]
> The two are not equivalent. WEBM is a video format which APNG is an animated image format similar to GIF.

That's kind of my point -- 99% of instances where animated images are used, videos would be more appropriate. APNGs, like GIFs, are a tremendously inefficient format, because they're bastardized stills.

GIFs are still widely used purely because the internet has gotten used to them. Let's not perpetuate the problem.

As far as browser support: every modern browser except Safari supports WEBMs. I would hardly call that "no browser support".

If you *must* support Safari or it *must* be an animated image format, then use WEBP -- it has support in all modern browsers (alpha and animation included) and it's much more modern (and standardized) than APNG. And ImageMagick supports it.

**Comment by AuracleTech** [comment]
Okay so right now I need a gradiant, transparent animation.
Can't do this with gif as transparency is only 0 or 1, not 0 or 255.
Can't do this with webm as transparency is just not supported.
APNG do all of this.
Just accept it, stop being a technophobe, APNG is better.
Is you care about 15% more data over your internet in 2020, maybe you just need a better connection.

**Comment by fmw42** [comment]
Lets not argue on this forum. Be respectful. As it is, ImageMagick does not currently support either. At some point perhaps it will support both. If anyone is willing to code up either, you would likely get support for it. But the IM developers have limited time availability and are very busy otherwise with bug fixes and such.

**Comment by forresthopkinsa** [comment]
@AuracleTech Have you tried WEBP? I think it could be really helpful for your use case. ImageMagick supports it.

**Comment by AuracleTech** [comment]
No, I need APNG, WEBM won't work with what I'm doing right now.

**Comment by 8spinach** [comment]
> As far as browser support: every modern browser except Safari supports WEBMs. I would hardly call that "no browser support".

no browser support for webm with transparency.

**Comment by 8spinach** [comment]
> At some point perhaps it will support both.

people are here talking about it because the issue is closed and has been closed for years. there is no perhaps that will come to pass without noise.

>If anyone is willing to code up either, you would likely get support for it.

mozilla patched the library imagemagick uses. the work has been done. imagemagick has not accepted that work.

**Comment by dlemstra** [comment]
We will not add support for APNG until the APNG patch has been accepted by the libpng team. Once that has been added it should be possible for someone to add support for APNG.

**Comment by forresthopkinsa** [comment]
> No, I need APNG, WEBM won't work with what I'm doing right now.

WEBM and WEBP are different formats.

> > As far as browser support: every modern browser except Safari supports WEBMs. I would hardly call that "no browser support".
> 
> no browser support for webm with transparency.

Edge, Firefox, Chrome, and Opera all _supposedly_ support WEBM with transparency.

And *all* modern browsers definitely support WEBP transparency.

**Comment by AuracleTech** [comment]
> > As far as browser support: every modern browser except Safari supports WEBMs. I would hardly call that "no browser support".
> 
> no browser support for webm with transparency.

Yeah. No browser support webm with transparency. So who cares if it does support transparency.
APNG win.

**Comment by urban-warrior** [comment]
Easy solution.  ImageMagick is open-source.  Create a pull-request for ImageMagick that supports APNG and/or WEBM.  If its sufficiently cross-platform and robust, we will merge it in the ImageMagick distribution.

**Comment by AuracleTech** [comment]
> Easy solution. ImageMagick is open-source. Create a pull-request for ImageMagick that supports APNG and/or WEBM. If its sufficiently cross-platform and robust, we will merge it in the ImageMagick distribution.

Im a web dev I have no clue how images are even saved bit wise.

**Comment by urban-warrior** [comment]
Do you have ffmpeg installed on your system?  If so, try this command:

```
convert mpeg:chompy.png chompy%03d.png
```

**Comment by fmw42** [comment]
I have been testing using ffmpeg to determine arguments to put into the ImageMagick coding. Here are my examples using the beta with the patch (7.0.10.31 beta)

# creates an APNG animation at 50 ticks delay and 10 loops
`im7beta magick lena.jpg mandril3.jpg monet2.jpg zelda1.jpg PNG:- | ffmpeg -framerate 100/50 -i - -plays 10 anim.apng`


[anim.apng.zip](https://github.com/ImageMagick/ImageMagick/files/5272439/anim.apng.zip)


# creates a WEBM video at 50 ticks delay (no looping control for videos?)
`im7beta magick lena.jpg mandril3.jpg monet2.jpg zelda1.jpg PNG:- | ffmpeg -framerate 100/50 -i - -c:v libvpx anim.webm`

[anim.webm.zip](https://github.com/ImageMagick/ImageMagick/files/5272440/anim.webm.zip)


Support for various browser versions can be found at:

https://caniuse.com/apng
https://caniuse.com/webm

**Comment by rubyFeedback** [comment]
If you go to wikipedia:

https://en.wikipedia.org/wiki/APNG#Support

You see ImageMagick not even being listed there. So I assumed it did not support APNG.

Then I found the discussion here.

I come from that oldschool era where we had animated .gif files.

I don't really use .gif files myself anymore; mostly .jpg and .png. I
like .png even though you may have quite massive files (for larger
pictures that is but I just hate jpeg losing so much quality so quickly,
it's really bad ...). So from that point of view it would be nice if APNG
is supported by ImageMagick.

I consider ImageMagick similar to ffmpeg, and if ffmpeg supports this
then perhaps ImageMagick does not need to support it. I just don't
think the explanation given as to why ImageMagick should not have
support for this to not make a whole lot of sense, if you already have
.gif related support such as via convert -loop. So from that point of
view I agree with all who think APNG should be supported. Alternatively,
remove -loop and let ffmpeg handle this if you don't want to support
it. As it is right now, it seems inconsistent to me how ImageMagick 
approaches this. So, the TL;DR - please support APNG fully.

**Comment by rubyFeedback** [comment]
@fmw42 yeah, I guess if ffmpeg supports this then you can reason that
it is not so important whether ImageMagick supports it or not. People
can just use ffmpeg. I guess the question is whether animated pictures
are a movie, or likewise whether a movie consists of individual pictures
or not. :D

There is definitely an overlap in functionality, but you see this with tons
of existing software out there. For my own use case and needs, ffmpeg
literally removed just about any other conversion when it comes to 
audio and video. Or perhaps integrate ImageMagick into ffmpeg, then
this discussion would be simplified. ;D (Although I am not really suggesting
this! Manipulating video is more complicated than manipulating images,
IMO. The "convert" binary from imagemagick is really quite simple to 
understand and easy to use; I use it via ruby to script batch-modify tons
of images. FFMPEG is really more complicated to use, just look at advanced
filters in ffmpeg ... quite annoying to use them)

**Comment by fmw42** [comment]
ImageMagick 7, now supports APNG since version 7.0.10-31

```
2020-09-20 7.0.10-31 <quetzlzacatenango@image...>
Add support for APNG (specify explicitly, e.g. apng:animate.png).
```

**Comment by FurkanGozukara** [comment]
anyone here know how can i convert apng into animated webp?

**Comment by fmw42** [comment]
Install the latest WEBP delegate on the latest ImageMagick 7. Then

`magick APNG:image.png image.webp`

**Comment by FurkanGozukara** [comment]
@fmw42 I am using 7.24

Here my question

https://stackoverflow.com/questions/68011850/how-to-convert-apng-into-webp-by-using-magick-net-imagemagick-and-c?r=SearchResults

**Comment by fmw42** [comment]
There is no ImageMagick version 7.24. It is only at 7.1.0.0.  Please check again. Also do you have WEBP installed?

**Comment by FurkanGozukara** [comment]
@fmw42 

![image](https://user-images.githubusercontent.com/19240467/122352162-88410900-cf57-11eb-9688-d4b454f5c18d.png)

**Comment by fmw42** [comment]
OK. Your version is for Magick.NET not ImageMagick command line.  Any questions about that would need to be answered by the Magick.NET developer.
