### ISSUE TITLE
mogrify should enclose filenames in quotes.

### ISSUE THREAD

**Issue by thefuzzy0ne** [ImageMagick/ImageMagick#2579]
Assuming `mogrify` basically calls convert repeatedly, by enclosing the filenames within quotes, it will then be possible for it to support filenames that begin with a slash instead of assuming it's a switch.

Is there any reason that this can't be/hasn't already been done? Could this be please added?

**Comment by snibgo** [comment]
mogrify doesn't call convert.

Quotes are needed at the command line when filenames contain spaces. This is because command line interpreters assume spaces are separators between tokens.

Slash / and backslash \ are markers for directories. If a filename contains these characters, IM and many other programs will be confused.

Please show examples that show the problem you want to solve.

**Comment by thefuzzy0ne** [comment]
It turns out that the problem is not quite as straightforward as I thought. I thought it was any file starting with a dash that was a problem, but it's not. It's actually any filename starting a single dash followed by a string, followed by another dash then optionally followed by another string. For example:
`-some-file.gif`
or
`-somefile-.gif`

Please see [this example](https://github.com/ImageMagick/ImageMagick/files/5225532/imagick-mogrify-problem.zip). Simply extract it, open a console, `cd` into it and then run:

`magick mogrify -resize 50x50 -path resized *.*`

I have no idea what's so significant about filenames containing more than one non-contiguous dashes in the filename

Thanks in advance.

**Comment by snibgo** [comment]
The problem is that IM thinks that anything on the command line that starts with dash "-" and has an alpha as the next character (eg "-somefile.png") is an option, not a file. This is in mogrify.c MogrifyImageCommand() and option.c IsCommandOption().

In "magick", we can use "--" as an option before a filename that starts with "-", so this command works:
```
magick -- "-this-fails.png" -resize 200 x.png
```
Although MogrifyImageCommand() contains "--" as a special case, it doesn't seem to affect the processing. I don't know if that omission is deliberate or a bug.

A developer may comment.

(As a workaround, I suggest never starting filenames with "-".)

**Comment by thefuzzy0ne** [comment]
It happily processes filenames that start with a dash. It just doesn't like it when there are two non-contiguous dashes.
`-filename.gif` and `--filename.gif` are both fine and process without issue.

`-file-name.gif` is not and somehow gets parsed as a switch.

**Comment by snibgo** [comment]
The double-dash works fine because the second character isn't an alpha.

I don't know why a dash within the name makes a difference.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/download/beta/ by sometime tomorrow.
