### ISSUE TITLE
Multi-layer PSD lost  alpha channel , readed as a RGB image 

### ISSUE THREAD

**Issue by yunyuncc** [ImageMagick/ImageMagick#2834]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

I known this problem has been reported before, But the problem is still there. 
see also  #1838  
I'm having the same problem with him and I have try the lastest version (7.0.10-38).

### Steps to Reproduce

this is my code, I want convert PSD to png , but  alpha channel is lost
here is test images
[test_images.zip](https://github.com/ImageMagick/ImageMagick/files/5551071/test_images.zip)

```c++
#include <Magick++.h>
#include <fstream>
#include <iostream>
#include <list>
#include <string>
using namespace std;
using namespace Magick;
std::string loadfile(const std::string &path)
{
    std::ifstream inf;
    inf.open(path.c_str(), std::ios::binary | std::ios::ate);
    if (!inf.is_open())
    {
        throw std::runtime_error("can't open " + path + " in loadfile");
    }
    int size = inf.tellg();
    inf.seekg(0, std::ios::beg);
    std::string cmsg;
    cmsg.resize(size);
    inf.read((char *)cmsg.data(), size);
    return cmsg;
}
void savefile(const std::string &path, const std::string &data)
{
    std::ofstream fs;
    fs.open(path.c_str(), std::ios::binary);
    if (!fs.is_open())
    {
        throw std::runtime_error("can't open " + path + " in savefile");
    }
    fs << data;
}

void show(Image &image)
{
    if (image.alpha())
    {
        cout << "has alpha" << endl;
    }
    else
    {
        cout << "has not alpha" << endl;
    }
    cout << "channels:" << image.channels() << endl;
    cout << image.format() << endl;
    cout << image.magick() << endl;
}
int main(int /*argc*/, char **argv)
{
    std::string data = loadfile(argv[1]);
    Blob blob(data.c_str(), data.size());
    Image image(blob);
    show(image);
    image.magick("PNG");
    image.write(&blob);

    std::string dataOut;
    dataOut.assign((char *)blob.data(), blob.length());
    savefile("test.png", dataOut);
    return 0;
}


```
### System Configuration

- ImageMagick version:
7.0.10-38
- Environment (Operating system, version and so on): 
Linux 374564a6219f 4.15.0-106-generic #107~16.04.1-Ubuntu SMP Thu Jun 4 15:40:05 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Additional information:

**Comment by dlemstra** [comment]
You are not getting an alpha channel because we no longer make the incorrect assumption that when the merged image has 4 channels that the 4th channel is an alpha channel. And this image does not contain any information that we can use to determine that the 4th channel is an alpha channel. We could possibly introduce a define for this to get the incorrect behaviour but not sure if we should do that or what name we should use for that option.

cc @fmw42

**Comment by fmw42** [comment]
Dirk,  This is one of the PSD issues I have been concerned about for quite a while. Typically PSD files have background transparency. And we have in the past extracted that at the expense of the alpha channel in the PSD file. I tried his IMG_1902.PSD. It has both background transparency and alpha transparency, though I am not sure why, since they seem to do the same. There is a white layer background layer that is disabled now. But when I convert the file, it gets used and alpha channel which is disabled does not get use. The result is the white background layer shows even though it was disable.. I note that whenever  enable the alpha channel and save the file and reopen it, that alpha channel gets disabled.

In my opinion, we should have a define that lets the user select either the background transparency or the alpha transparency or both (multplied).

I am not sure what to do about the disabled layers. We could have another define to permit the use of disabled channels.

**Comment by blue-j** [comment]
PSD is an authoring format, while ImageMagick treats it as a rendered format.  PSD is really not intended for output/publishing.  That is why it allows so many alpha channels (aka saved selections) even though alphas have historically intended to indicate transparency only.  That said, I believe we should try to support PSD more, though it is a horribly complicated format.

Relevant metadata are _Photoshop:numchannels_ and _Photoshop:alphachannelsnames_ though I suspect they are not always written?  Maybe those could be helpful?

**Comment by fmw42** [comment]
As far as I can tell, every time I try to save a PSD file after enabling an alpha channel, when I save, close and reopen it the alpha channel is disabled. So we do not know how to access a disabled alpha channel. Do you know of some way to keep it enabled? Or to access disabled alpha channels?

**Comment by blue-j** [comment]
PSD is meant to be a format for file preparation/authoring.  Background transparency is not related to alpha channels.  Alpha channels don't even amount to transparency anywhere in PSD, until you make a PNG or TIFF or other format which utilizes them that way, in which case it invokes all the parameters of that format (although they have modified TIFF to be very different from v6, and it basically supports all PSD features at this point, but you can still output a normal TIFF).  They are considered "saved selections" in Photoshop, a way for authors to save areas they have selected of an image.  You literally can make them with the "Save selection..." command.  I have saved some sample files and the way they look in the PS UI for reference.  

[PSD_samples.zip](https://github.com/ImageMagick/ImageMagick/files/5632872/PSD_samples.zip)

**Comment by fmw42** [comment]
But my point is that if I save a PSD and then use ImageMagick to convert to PNG, it is missing the alpha channels because PS disables them when saving the PSD file. So if it is not enabled, it cannot be used to convert to PNG.

**Comment by blue-j** [comment]
Yes, because alpha channels don't indicate transparency in PSDs.  In order for ImageMagick to be able to make a transparent PNG from a PSD, it should be based on background transparency not alpha channels. Perhaps I even misspoke above - alphas may simply *never* be used to indicate transparency in Photoshop.  You are expected to load them as selections and knock out pixels to show background transparency, which in turn is honored when you export a PNG or TIFF and choose transparency. My suggestion is to ignore alpha channels in PSDs and look for background transparency instead to generate transparent PNGs with ImageMagick.

**Comment by blue-j** [comment]
<img width="1281" alt="Screen Shot 2020-12-02 at 5 10 16 PM" src="https://user-images.githubusercontent.com/3990142/100950686-b8e0ba00-34c1-11eb-8f6a-9e13ad78d302.png">
<img width="1084" alt="Screen Shot 2020-12-02 at 5 11 06 PM" src="https://user-images.githubusercontent.com/3990142/100950698-bda56e00-34c1-11eb-8706-ce84335c83af.png">
<img width="729" alt="Screen Shot 2020-12-02 at 5 12 25 PM" src="https://user-images.githubusercontent.com/3990142/100950701-bed69b00-34c1-11eb-9808-e255eeb6bc9e.png">

**Comment by blue-j** [comment]
<img width="732" alt="Screen Shot 2020-12-02 at 5 14 45 PM" src="https://user-images.githubusercontent.com/3990142/100950862-2db3f400-34c2-11eb-83b1-7324ab7f549b.png">

**Comment by blue-j** [comment]
<img width="983" alt="Screen Shot 2020-12-02 at 5 17 52 PM" src="https://user-images.githubusercontent.com/3990142/100951000-779cda00-34c2-11eb-9479-b5f374fbc04a.png">

**Comment by blue-j** [comment]
<img width="1016" alt="Screen Shot 2020-12-02 at 5 19 52 PM" src="https://user-images.githubusercontent.com/3990142/100951075-a7e47880-34c2-11eb-89ab-b83fe70caff9.png">

**Comment by fmw42** [comment]
We already save the background transparency when converting to PNG provided the transparency check box is checked, as far as I know.  But other people have been asking about utilizing the alpha channels as transparency either in place of the background transparency or in place of it.

**Comment by fmw42** [comment]
I do not understand what you are trying to show. Photoshop always disables the alpha channels when the file is saved. When reopened, it is disabled. So we have no way to access a disabled alpha channel when trying to convert the PSD file to PNG.  

We transfer the background transparency to PNG, but only if the transparency checkbox is checked when the PSD file is saved. If it is not checked, then I do not think it can be transferred to the PNG

**Comment by blue-j** [comment]
My apologies for misunderstanding.  No, there is no way to ask Photoshop to retain the state of channels being on/off that I know off.  When you save, it always turns on all the pixel channels and disables the alphas.  I can ask my team if anyone knows differently.

**Comment by fmw42** [comment]
Please do, thanks.

**Comment by wesclarkemag** [comment]
Hello, I just started using ImageMagick and I think it's a great tool. Except I think I am hitting the same issue as fmw42. Trying to convert a PSD that has a number of layers + alpha channel. It does appear to have a BG transparency layer but it is obscure by a lot of other crud above it. As I am looking to batch this, it's not likely I can just turn layers off as that would defeat the purpose. Is there a way to use the existing Alpha channel to knock out rgb pixels when doing the conversion?

**Comment by fmw42** [comment]
Not currently. Zip and post your PSD file so we can examine it. You should be getting the background transparency. Also any layer that is not enabled will not show in an ImageMagick conversion.
