### ISSUE TITLE
Infinite loop in ClonePixelCacheRepository (MagickCore/cache.c:3266)

### ISSUE THREAD

**Issue by moshekaplan** [ImageMagick/ImageMagick#30]
https://bugs.launchpad.net/ubuntu/+source/imagemagick/+bug/1496643

**Comment by dlemstra** [comment]
On windows I get the following output:

`convert ClonePixelCacheRepository_infinite_loop null:`
`convert.exe: unable to extend cache 'ClonePixelCacheRepository_infinite_loop': No space left on device @ error/cache.c/OpenPixelCache/3525.
convert.exe: Memory allocation failed 'ClonePixelCacheRepository_infinite_loop' @ error/pcx.c/ReadPCXImage/363.
convert.exe: no images defined 'null:' @ error/convert.c/ConvertImageCommand/3217.`

So it will just run long instead of infinite on your machine. You will probably want to modify your policy.xml file as stated here: https://github.com/ImageMagick/ImageMagick/issues/27
