### ISSUE TITLE
Idea: trigger Imagick tests on Travis build

### ISSUE THREAD

**Issue by Danack** [ImageMagick/ImageMagick#322]
Hi guys,

As you may, or may not, know, I'm the maintainer of the PHP Imagick extension.

Unfortunately due to various reasons, my time available to commit to supporting that open source project is quite limited, so I wanted to get some initial feedback on an idea before I spend too much time implementing it and sending it as a pull request. 

Last year, I setup the PR for [building ImageMagick through Travis](https://github.com/ImageMagick/ImageMagick/pull/1). That seems to be working well. 

However occasionally some changes are committed to ImageMagick that break tests in the PHP Imagick test suite. e.g. recently the gradient [color generation](https://github.com/ImageMagick/ImageMagick/issues/316).

When one of Imagick's users finds something like that, what then that happens then is I need to do some investigation work to find out when the commit that broke something occurred and then report it here as an issue to investigate, and then you guys need to read my bug report, possibly days or weeks after the commit occurred that caused the issue.

It seems to me that quite a bit of time could be saved for both of us if the Travis (and possibly appveyor) tests were changed to not only compile ImageMagick, but to also compile PHP Imagick, and to run it's tests as well, to increase the test coverage that is done on each ImageMagick commit.

Just to be clear - this would only affect the 'badges' and Travis notifications rather than actually affecting any output build of ImageMagick. Would you guys be open to that idea, or are there some downsides you can think of that would make it be not a good idea?

cheers
Dan

**Comment by dlemstra** [comment]
One issue that I could think of is that our build breaks because we make a changes that fixes something but breaks your tests and then fails our build. It would be nice if our commits could triggered a build on your repository and then run the tests. I have the same issue with Magick.NET (.NET library of Imagemagick). Sometimes one of my tests fails because we made a change that introduces a bug. Maybe you could have a separate repository that has two remotes. One with your code and one with our code. You could trigger a build in that repository with a cronjob and run the test on a daily basis. You will still need to check a couple commits but it will be much easier than doing that after a couple of weeks. Would that be a possible solution for you?

**Comment by Danack** [comment]
It is possible for the Travis setup to be done in a way, for there to be 'post build' steps, which even if they fail, the build won't be marked as failing. I think they are the after_success, after_failure, after_script steps.

However....yes I can see that setting this up for all downstream libraries that would like it would be tricky, if nothing else due to the length of the builds.
