### ISSUE TITLE
Add more encoder options for AVIF

### ISSUE THREAD

**Issue by njdoyle** [ImageMagick/ImageMagick#3379]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
- [X] I have verified that I am using the latest version of ImageMagick

### ImageMagick version

7.0.11-3

### Operating system

Linux

### Operating system, version and so on

Ubuntu 18.04

### Description

I would like to be able to control additional encoder options provided by libaom and libheif for AVIF images.
Specifically, I would like to control the `speed` parameter and the `chroma` parameter.

### Steps to Reproduce

Encode an AVIF image and notice that these parameters are not available.

**Comment by njdoyle** [comment]
Closing with the merge of PR #3380. Thanks!

**Comment by dominic-p** [comment]
Sorry to post on a closed issue. I've been playing around with AVIF encoding, and I noticed that this issue and the PR reference `avif:speed` and `avif:chroma`, but it looks like the commit itself added `heic:speed` and `heic:chroma`. In my ad-hoc testing, it does appear that the avif prefixed options don't do anything.

Is this intentional? I understand that there is a relationship between the two image formats, but it feels a bit counterintuitive to be specifying heic parameters when I'm producing avif images. Maybe an alias could be added to allow either `heic:*` or `avif:*` options?

**Comment by dlemstra** [comment]
That is indeed intentional. Our coders will always use their name as the prefix. We will not add aliases.

**Comment by dominic-p** [comment]
Thanks for the reply. I appreciate it.
