### ISSUE TITLE
Washed-out colors for JXL output

### ISSUE THREAD

**Issue by ghost** [ImageMagick/ImageMagick#3699]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
- [X] I have verified that I am using the latest version of ImageMagick

### ImageMagick version

7.0.11-13

### Operating system

Linux

### Operating system, version and so on

Arch Linux

### Description

JXL files produced by ImageMagick have washed-out colors.

Input is a 16-bit PNG.

### Steps to Reproduce

Convert the input to JXL by `cjxl` and `convert`, and compare the results using GIMP.

`cjxl -q 99 temp.png temp-cjxl-99.jxl`
`convert temp.png -quality 99 temp-im-99.jxl`

### Images

[Test files](https://github.com/ImageMagick/ImageMagick/files/6506475/test-files.zip)

**Comment by dlemstra** [comment]
This seems to be an issue with encoding the image in 32-bit floats. We just pushed a patch where we use `JXL_TYPE_UINT16` instead of `JXL_TYPE_FLOAT` for 16-bit images and the image comes out correctly. I think we will need to talk with the JXL team about this or go through the `cjxl` code to check why there is a difference.

**Comment by dlemstra** [comment]
The washed out colors will be gone in the next release. But that probably also means you will need to upgrade to the latest version (currently 0.5).
