### ISSUE TITLE
A TGA image converted to PNG is flipped vertically.

### ISSUE THREAD

**Issue by Viech** [ImageMagick/ImageMagick#3844]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
- [X] I have verified that I am using the latest version of ImageMagick

### ImageMagick version

7.1.0-0

### Operating system

Linux

### Operating system, version and so on

Arch Linux rolling with Kernel 5.12.10

### Description

When converting a `q3map2`-produced external lightmap file from `TGA` to `PNG`, the resulting image is vertically flipped. Just for giggles, a map that should look like [this](http://dl.viech.name/unvanquished_2021-06-19_130830_000.jpg) then looks like [this](http://dl.viech.name/unvanquished_2021-06-16_214107_000.jpg).

I have seen the similar #3061, however this was for an older version of ImageMagick and was closed as fixed.

The issue does **not** happen when I use the `-auto-orient` switch. I'm reporting this despite this workaround.

### Steps to Reproduce

Affected: `convert lm_0000.tga lm_0000.png`
Workaround: `convert -auto-orient lm_0000.tga lm_0000.png`

### Images

Input: http://dl.viech.name/lm_0000.tga
Output: http://dl.viech.name/lm_0000.png

**Comment by illwieckz** [comment]
On my end (ImageMagick 6.9), `convert lm_0000.tga lm_0000.png` is properly oriented, but `convert -auto-orient lm_0000.tga lm_0000.png` produces an upside down image. So, given the ImageMagick version, the behaviour can invert completely, meaning we can't trust options.

In the past I faced the bug when converting jpg to tga and/or png: https://bugs.launchpad.net/ubuntu/+source/imagemagick/+bug/1838860

[![upside down](https://dl.illwieckz.net/b/imagemagick/bugs/convert-jpg-to-tga-upside-down/convert-jpg-to-tga-upside-down.png)](https://dl.illwieckz.net/b/imagemagick/bugs/convert-jpg-to-tga-upside-down/convert-jpg-to-tga-upside-down.png)

I had noticed converting a given jpg to png would be fine but jpg to tga would be upside down, but then jpg to png to tga would be fine. And I had noticed converting another jpg to png would be fine but then jpg to png to tga would be upside down, like if sometime the bug can be carried over some formats before popping up.

So here there is report on issue when doing tga to png, there was reports for tga to tiff in https://github.com/ImageMagick/ImageMagick/issues/1406 and reports for tga to jpg in https://github.com/ImageMagick/ImageMagick/issues/3061 and now, the not using `auto-invert` gives what another version produces with, or using it gives what another version produces without.

Is there an option that can be trusted across versions ? At the time I implemented an ugly workaround for “jpg to tga” by converting to png first with `-strip`: https://github.com/DaemonEngine/Urcheon/commit/b9a42f65117fd4a7fa59c72ba07c5e738aef90fb

**Comment by dlemstra** [comment]
The `TGA` encoder contained some bugs with the orientation and at some point these got fixed. We cannot garuantee ImageMagick works the same way accress versions otherwise because we fixed bugs from older versions.

For the `TGA` encoder you will need to use `-auto-orient` to change the orientation of the image. And I am unable to reproduce your issues with the latest version of ImageMagick 7 @illwieckz .

**Comment by urban-warrior** [comment]
Question, does ImageMagick currently produce the expected results for TGA?  Assuming it does, there was a bug in the past.  Unfortunately the only reliable method to produce expected results is to require a recent release of ImageMagick or perform version checks.  As an example, numerous [Fred's Scripts](http://www.fmwconcepts.com/imagemagick/index.php) does version checks to account for bug fixes between versions.

**Comment by illwieckz** [comment]
> Question, does ImageMagick currently produce the expected results for TGA?

@Viech said doing `convert lm_0000.tga lm_0000.png` with ImageMagich 7.1 produces flipped images, which is not the expected result as far as I know.

Why 

> For the `TGA` encoder you will need to use `-auto-orient` to change the orientation of the image.

We don't want the orientation of the image to be changed, but to be kept the same as original file.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by dlemstra** [comment]
The patch that was applied yesterday has been reverted. ImageMagick should not change the orientation to `TopLeft` when the image is read but preserve the original orientation of the image. You will need to use `-auto-orient` to change the orientation to `TopLeft`,

**Comment by Viech** [comment]
I don't know what `TopLeft` means. When I use just `convert` – without any options – I expect the output image to not be flipped or rotated but look just like the original image within an average image viewing application. I understand that there can be a difference between memory alignment and how the image is displayed but I would assume that almost all applications would agree on how to display the image on the screen eventually. I would like ImageMagick's default behavior to be such that other applications can display a converted image correctly.

**Comment by fmw42** [comment]
Always add -auto-orient to your command line to take care of that. If that does not work, then there might be an error in your photo meta data recording of the orientation.

**Comment by illwieckz** [comment]
I'm not sure to understand everything. My concern is: 

Can we do (with a version of imagemagick convert behaving the way you want it to behave):

```sh
for i in *.jpg *.tga *.png
do
	convert --auto-orient "${i}" "${i}.png"
done
```

And always get the same orientation whatever the input format, and without changing the command line option given the format?

Note: PNG to PNG is not a mistake, someone may want to rewrite PNG to sanitize them for example.

In [Urcheon](https://github.com/DaemonEngine/Urcheon) I use imagemagick to convert any format supported by imagemagick to a transient png before feeding another converter.

For example cwebp does not support tga on input, so I just convert everything to png before calling cwebp.

Yes I know imagemagick may do webp as well, but my point is to never use image-specific option with imagemagick convert, like on this shell example. Then I use dedicated tools for the final format.

Another example is that I don't trust [Crunch](https://github.com/DaemonEngine/crunch) to support all [existing PNG variants](https://github.com/UnvanquishedAssets/UnvanquishedTestAssets/tree/master/src/map-test-pngalpha_src.dpkdir/textures/test-pngalpha_custom_src) even if it claims to support PNG as input, because well, except PNG optimizers, almost no one tool try to compress PNG efficiently so those variants are usually untested by tools. So because crunch supports TGA and I know default TGA output of imagemagick convert is well supported by crunch, I convert every PNG to TGA using imagemagick convert before converting to CRN using crunch to make sure the process never fail (unless imagemagick convert is at fault).

**Comment by fmw42** [comment]
That command should work if the input PNG or any input format has the camera orientation flag correctly loaded into the image meta data. If that does not exist, there is no way to know how the image was captured.

**Comment by snibgo** [comment]
@Viech wrote:
>  When I use just convert – without any options – I expect the output image to not be flipped or rotated but look just like the original image within an average image viewing application.

That expectation is mistaken. IM won't do that.

"An average image viewing application" will regard the orientation flag. If it is anything other than top-left, it will flip or flop or rotate as required by the flag. This should have the same effect as IM's "-auto-orient".

IM won't do an auto-orient unless you tell it to.

**Comment by Viech** [comment]
I see, but is IM also not supposed to copy (instead of apply) an existing orientation flag between formats by default?

Further, has anyone looked at my particular images and verified that the input uses an orientation flag? As it's not a photo but a game lightmap, I would be surprised if it did. Opening `lm_0000.tga` in GIMP does _not_ give me the "do you want to keep/lose orientation" message that it gives me for some photos. Maybe there still is a bug here.

**Comment by dlemstra** [comment]
The TGA header contains an  Image Descriptor Byte. Where bit 5 tells us the screen origin:

```
Bit 5 - screen origin bit. 

0 = Origin in lower left-hand corner. 
1 = Origin in upper left-hand corner.
Must be 0 for Truevision images. 
```

And there is also some orientation magic happening when bit 4 is set. For your image we get the following orientation:

```
I:\>identify -format "%[orientation]" lm_0000.tga
BottomLeft
```

**Comment by illwieckz** [comment]
It looks like the tool producing that lightmap (q3map2) is zeroing the whole header then set the various data (size, bitness…) but never write anything on the orientation bit, being left to zero:

https://gitlab.com/xonotic/netradiant/-/blob/0012eff8c732414960a7bb02765b230014b1650d/tools/quake3/q3map2/lightmaps_ydnar.c#L72

The tool reuses a variant of a function from Quake 3 source code that does the same:

https://github.com/id-Software/Quake-III-Arena/blob/dbe4ddb10315479fc00086f08e25d968b4b43c49/common/imagelib.c#L1093

The historical Quake 3 code is:

```c
void WriteTGA (const char *filename, byte *data, int width, int height) {
	byte	*buffer;
	int		i;
	int		c;
	FILE	*f;

	buffer = malloc(width*height*4 + 18);
	memset (buffer, 0, 18);
	buffer[2] = 2;		// uncompressed type
	buffer[12] = width&255;
	buffer[13] = width>>8;
	buffer[14] = height&255;
	buffer[15] = height>>8;
	buffer[16] = 32;	// pixel size

	// swap rgb to bgr
	c = 18 + width * height * 4;
	for (i=18 ; i<c ; i+=4)
	{
		buffer[i] = data[i-18+2];		// blue
		buffer[i+1] = data[i-18+1];		// green
		buffer[i+2] = data[i-18+0];		// red
		buffer[i+3] = data[i-18+3];		// alpha
	}

	f = fopen (filename, "wb");
	fwrite (buffer, 1, c, f);
	fclose (f);

	free (buffer);
}
```

The notable part seems to be:

```
	memset (buffer, 0, 18);
```

And then not setting anything on byte 17, leaving it zeroed.

This is unfortunate, this code exists since more than 20 years and is used in maybe hundreds of derivatives, including dozens of games engines and authoring tools and their related forks. I even myself zeroed that byte when writing a tool (`esquirel`) that intended to produce files compatibles with the id Tech 3 ecosystem, so just mimicking the cargo cult way what q3map2/quake3 did: https://github.com/DaemonEngine/Urcheon/blob/d6475430cc9da425737a129e4083dad0ecdb0cf5/Urcheon/Bsp.py#L336

So ImageMagick may be right according to the [specifications](https://www.dca.fee.unicamp.br/~martino/disciplinas/ea978/tgaffs.pdf), but then be incompatible with two decades of software development… I don't know how that can be solved…

Is there an imagemagick convert option to assume input origin is top left? In our case, we can guess using a file name pattern (`lm_[0-9][0-9][0-9][0-9].tga`) that the origin is top left.

**Comment by illwieckz** [comment]
I'm a bit cofused by [TGA specifications](https://www.dca.fee.unicamp.br/~martino/disciplinas/ea978/tgaffs.pdf) wording. On page 9 (12 of the PDF), it says:

> Bits 5 & 4: These bits are used to indicate the order in which pixel data is transferred from the file to the screen. Bit 4 is for left-to-right ordering and bit 5 is for top-to-bottom ordering as shown below.

So it says “bit 4 is for left-to-right” and the table indicates that with `0` value the first pixel is on the left (so we can assume it continue to the right otherwise it would go offscreen).

Then it says “bit 5 is for top-to-bottom”, but then the table indicates that with `0` value the first pixel is on the bottom (so we can assume it continue to the top otherwise it would go offscreen).

So if you only read the sentence and don't look at the table, one may wrongly assume bit 4 and 5 are to modify the origin and orientation from “left-to-right” and “top-to-bottom”, while they are to modify the origin and orientation from “left-to-right” and “bottom-to-top” according to the table.

**Comment by fmw42** [comment]
If you know it is always wrong, just flip (or rotate 180) your image accordingly.

**Comment by illwieckz** [comment]
Hmm, I have to do more investigations to check if those tools are always wrong or not. They are likely to write the image bottom-to-top. In my  `esquirel` code I wrote to be compatible with them, I zero the bytes (that means bottom-left is origin), but I also write from from left to right and from bottom to top and other tools are happy with that: https://github.com/DaemonEngine/Urcheon/blob/d6475430cc9da425737a129e4083dad0ecdb0cf5/Urcheon/Bsp.py#L342

What is the expected behaviour of `convert image.tga image.png` (without `-auto-orient`)? Is it expected to read from bottom left or from top left?

**Comment by fmw42** [comment]
I would expect it to be top-left of how the data was recorded, not necessarily how the top-left of the image.

**Comment by illwieckz** [comment]
I've looked at some files from a legacy idTech3 game level:

```
$ wget https://dl.unvanquished.net/main/map-tremor-gpp.pk3

$ mkdir map-tremor-gpp
$ cd map-tremor-gpp
$ unzip ../map-tremor-gpp.pk3 

# textures, not produced by idTech 3 tools, likely to be produced by old GIMP or old Photoshop
$ for i in $(find textures/ -type f -name *.tga); do printf '%s: %s\n' $i $(identify -format "%[orientation]" $i); done
textures/tremor/light_128x512.tga: BottomLeft
textures/tremor/plainglass.tga: BottomLeft
textures/tremor/tremorlightblend.tga: BottomLeft
textures/tremor/tremorspark1.tga: BottomLeft
textures/tremor/e6bsegrtflr256.tga: BottomLeft

# lightmaps, produced by idtech 3 `q3map2` tool
$ for i in $(find maps/tremor/ -type f -name *.tga); do printf '%s: %s\n' $i $(identify -format "%[orientation]" $i); done
maps/tremor/lm_0000.tga: BottomLeft
maps/tremor/lm_0001.tga: BottomLeft
maps/tremor/lm_0002.tga: BottomLeft
maps/tremor/lm_0003.tga: BottomLeft
maps/tremor/lm_0004.tga: BottomLeft
maps/tremor/lm_0005.tga: BottomLeft
maps/tremor/lm_0006.tga: BottomLeft
maps/tremor/lm_0007.tga: BottomLeft

$ esquirel bsp -ib maps/tremor.bsp -od maps/tremor.bspdir

# lightmaps, extracted from bsp file and written to tga by `esquirel` tool:
$ for i in $(find maps/tremor.bspdir/ -type f -name *.tga); do printf '%s: %s\n' $i $(identify -format "%[orientation]" $i); done
maps/tremor.bspdir/lightmaps.d/lm_0000.tga: BottomLeft
maps/tremor.bspdir/lightmaps.d/lm_0001.tga: BottomLeft
maps/tremor.bspdir/lightmaps.d/lm_0002.tga: BottomLeft
maps/tremor.bspdir/lightmaps.d/lm_0003.tga: BottomLeft
maps/tremor.bspdir/lightmaps.d/lm_0004.tga: BottomLeft
maps/tremor.bspdir/lightmaps.d/lm_0005.tga: BottomLeft
maps/tremor.bspdir/lightmaps.d/lm_0006.tga: BottomLeft
maps/tremor.bspdir/lightmaps.d/lm_0007.tga: BottomLeft
maps/tremor.bspdir/lightmaps.d/lm_0008.tga: BottomLeft
maps/tremor.bspdir/lightmaps.d/lm_0009.tga: BottomLeft
maps/tremor.bspdir/lightmaps.d/lm_0010.tga: BottomLeft
maps/tremor.bspdir/lightmaps.d/lm_0011.tga: BottomLeft
maps/tremor.bspdir/lightmaps.d/lm_0012.tga: BottomLeft
maps/tremor.bspdir/lightmaps.d/lm_0013.tga: BottomLeft
maps/tremor.bspdir/lightmaps.d/lm_0014.tga: BottomLeft
maps/tremor.bspdir/lightmaps.d/lm_0015.tga: BottomLeft
maps/tremor.bspdir/lightmaps.d/lm_0016.tga: BottomLeft
maps/tremor.bspdir/lightmaps.d/lm_0017.tga: BottomLeft
maps/tremor.bspdir/lightmaps.d/lm_0018.tga: BottomLeft
maps/tremor.bspdir/lightmaps.d/lm_0019.tga: BottomLeft
maps/tremor.bspdir/lightmaps.d/lm_0020.tga: BottomLeft
maps/tremor.bspdir/lightmaps.d/lm_0021.tga: BottomLeft
maps/tremor.bspdir/lightmaps.d/lm_0022.tga: BottomLeft
maps/tremor.bspdir/lightmaps.d/lm_0023.tga: BottomLeft
maps/tremor.bspdir/lightmaps.d/lm_0024.tga: BottomLeft
```

So, all those legacy files use `BottomLeft` origin. So they are expected to be written from BottomLeft without transformation when converting to a format with BottomLeft origin and the data (not the visual image) being flipped vertically when converting to a format with TopLeft origin.

In [PNG specification](https://www.w3.org/TR/PNG/#7Scanline) I read:

> A PNG image (or pass, see clause 8: Interlacing and pass extraction) is a rectangular pixel array, with pixels appearing left-to-right within each scanline, and scanlines appearing top-to-bottom.

If I'm right, the first byte in a TGA datastream with `0` in attribute bit 5 codes the bottom left pixel and the first byte in a PNG datastream codes the top left pixel. So converting such a TGA to PNG requires to flip the scanlines vertically. This is not about visual orientation like turning a camera picture to fit the camera orientation, this is about decoding and encoding a stream properly according to their specifications.

**Comment by fmw42** [comment]
So always add -flip to your command line when reading your images.

**Comment by illwieckz** [comment]
> So always add -flip to your command line when reading your images.

Have you read my comment:

> If I'm right, the first byte in a TGA datastream with 0 in attribute bit 5 codes the bottom left pixel and the first byte in a PNG datastream codes the top left pixel. So converting such a TGA to PNG requires to flip the scanlines vertically. This is not about visual orientation like turning a camera picture to fit the camera orientation, this is about decoding and encoding a stream properly according to their specifications.

I'm writing right now a script to produce an image with a TopLeft pattern stored in a BottomLeft TGA datastream to see if converting to PNG still displays the pattern TopLeft. So we can check if this or that version of ImageMagick has a bug. Otherwise we're just fooling our brains.

**Comment by fmw42** [comment]
I will leave this to the IM developers to decide what to do. I only tried to offer a solution that you could use that would work. Seems to me that adding -flip solves your issue from the ImageMagick perspective, thought perhaps not optimal from your point of view.

**Comment by illwieckz** [comment]
Yeah, but in the end it looks like our files are properly oriented, so if we need to flip, that would mean there is a bug. That's why I want to produce a file programmatically to be sure what we have is what we want, because using existing images or creating images with third-party tools may be biased.

**Comment by dlemstra** [comment]
In ImageMagick we try to preserve the orientation of the image so our users can know how the image is stored. And for the `TGA` format this means that you might need to do an `-auto-orient` after the image has been read. When the image is already in the `TopLeft` position nothing will happen and otherwise the image will be rotated to `TopLeft`.

It might be possible that older versions of ImageMagick did this incorrectly and that might mean you will need to add version checks for that in your software when you want to be compatible with an older version.

**Comment by illwieckz** [comment]
I confirm the current version of ImageMagick has a bug and does not preserve orientation of the image.

This is because it mistakenly uses the storage format convention as a metadata and adds it to the metadata coding the image orientation.

```sh
$ git rev-parse HEAD
c071597408a3265f7ef319b890e30b3cb2d7a7fc
```

```sh
$ magick --version | grep '^Version:'
Version: ImageMagick 7.1.0-3 Q16 x86_64 2021-06-25 https://imagemagick.org
```

As I said [earlier](https://github.com/imagemagick/imagemagick/issues/3844#issuecomment-865244119) I decided to write a tool too produce unbiased TGA samples:

> I want to produce a file programmatically to be sure what we have is what we want, because using existing images or creating images with third-party tools may be biased: we would only compare visual representations, not the data stream.

You can find the tool and the unbiased samples there:

- [gitlab.com/illwieckz/produce-reference-tga](https://gitlab.com/illwieckz/produce-reference-tga)

Complete explanations of what is going on can be found on the related [README](https://gitlab.com/illwieckz/produce-reference-tga/-/blob/master/README.md) file. Are also provided PNG samples that can be used as reference to compare produced files. Are also provided TGA samples with orientation bits unset that can be used as reference to compare produced files when not using `-auto-orient`.

Quotes:

> The root cause of those bug seems to be a confusion about semantic of data ordering (the way the image data is stored and decoded) and orientation metadata (non-image data that may code an image transformation to be done after decoding the image data itself).

> The fact the first bytes of a TGA bit stream code the left pixel of the bottom line of the screen is a format convention, the fact another image format may code the top left pixel of the screen as first bytes of a PNG bit stream prior to compression is another format convention, none of these format differences are coding an orientation metadata.

> This is very similar to what happens with big-endian and little-endian image formats. For example the PNG format has integers stored as big endian while TGA format has integers stored as little endian. A TGA or PNG decoder must respect the endianness even if it is chosen to not apply further transformation that may be coded in the file. This is true as well for the TIFF format that has both little-endian and big-endian formats.

> For example producing a big endian or a little endian TIFF with ImageMagick with command `magick convert image.tga -define tiff:endian=msb image-msb.tif` or `magick convert image.tif -define tiff:endian=isb image-isb.tif` (without `-auto-orient`) must not alter colors. The `-auto-orient` option must not be required to get a file that would display expected colors when read by third party software.

> In the same way, converting a TGA to PNG with ImageMagick command `magick convert image.tga image.png` must not require `-auto-orient` to produce an image that has first bytes of the TGA bitstream coding the left pixel of the bottom line in the PNG file if the orientation bits are unset (equal to zero).

> Similar problematic may be faced with formats describing pixels as RGBA streams or as BGRA or ARGB ones or other variants. A device ignoring orientation metadata must not swap the color channels and adjust the byte read or the pixel display accordingly to the specification of the given format.

> The [TGA specification](https://www.dca.fee.unicamp.br/~martino/disciplinas/ea978/tgaffs.pdf) makes non-ambiguous usage of the “_display_” verb when describing the decoding process, and makes non-ambiguous usage of the “display device” terminology.

> A TGA decoder must display first TGA image bytes as pixel on bottom left on the “_display device_” even when ignoring possible metadata telling the contrary.

> Some other image formats like the BMP format also stores data in rows in a way the first bytes are expected to be displayed starting from bottom left. This format convention does not code image orientation metadata.

> A BMP decoder must display first BMP image bytes as pixel on bottom left of the “_target device_” if negative sign bit is not set in height field, and a TGA decoder must display first TGA image bytes as pixel on bottom left of the “_display device_” if the vertical orientation bit is unset in attribute field. The sign bit in BMP height field or the lack of vertical orientation bit in TGA attribute field being left unset to 0 does not code a vertical flip metadata of the image.

> After the TGA file is written to the buffer from bottom left to top right, an encoder for another format like the PNG format may then start to read the buffer from top left to bottom right to store the first image bytes if such format like the PNG format stores top left pixel as first bytes of the bitstream before compression.

> When reading a TGA file with orientation bits unset (equal to zero), ImageMagick tools report a `BottomLeft` origin and use this information as an orientation metadata to transform the image, which contradicts the fact the orientation bits are unset.

> So the ImageMagick tools mistakenly uses the image data format description (that does not code display orientation) as a metadata by itself and adds it to the metadata (that code displays information) which produce misoriented files on the vertical axis. The usage of the `-auto-orient` option may produce files that display properly because it's like flipping vertically two times by mistake, each flip mutually canceling themselves.

> There is another bug in ImageMagick `convert` tool related to this semantic misinterpretation, like producing a non-default format by writing the file upside-down and setting a vertical orientation bit to restore the orientation at display time when converting to TGA file format, even when the original file in another format did not carried any orientation information.

**Comment by illwieckz** [comment]
I know the BMP format also stores the lines from bottom to top like TGA, but I have not verified if the `convert` tool flips the lines vertically like it does with TGA files, and then set the sign bit in the height field to tell viewers to revert the flip the same way the `convert` tool flips the lines vertically then set the vertical bit orientation bit in the attribute field to tell viewers to revert the flip.

This may be interesting to investigate as well (I'm not saying I will do it).

At least for TGA, this bug has other unexpected implications described in #3903: _ImageMagick convert tool writes a non-default TGA format and sets a metadata to tell third-party tools to adjust_.

**Comment by dlemstra** [comment]
Closing this issue because @illwieckz apparently wants to continue this conversation in #3903.

**Comment by illwieckz** [comment]
@dlemstra This issues is not fixed, there are two bugs, this one and the one described in #3903. There are ways to fix #3909 without fixing this one for example even if they are related.

**Comment by illwieckz** [comment]
I continue here the off topic talk from #3903 which is about this bug (and **not** #3903):

> > The orientation of your file `from-bottom-left.png` is not bottom left but top left.

> Exactly, this the proof ImageMagick has a bug, the one described in #3844: a properly converted PNG image from a bottom left tga (as in TGA convention) is expected to produce a top left PNG (as in PNG convention), as you just noticed. Those are not metadata orientations, those are format conventions, like endianness or RGBA ordering, this is where the #3844 bug lies. But can we talk about #3844 bug in #3844 thread instead?

---

To expand it a bit more, because you may have missed things:

This file is named `from-bottom-left.png` because it's part of the samples provided in the repository to address this specific issue we talk about in that thread. 

The `from-bottom-left.png` file is the file properly converted to png from `reference-bottom-left.tga` file (the `raw-bottom-left.tga` one would produce the same), it is not named this way to describe the png orientation but to keep track from which tga file it was made from: the `reference-bottom-left.tga` is expected to produce that `from-bottom-left.png` if converted correctly.

Also the “left” and “bottom” words are used in the perimeter of the TGA specification (the meaning may differs in other perimeters, like ImageMagick one or some other image formats.

For example a “BottomLeft” image in TGA conventions is expected to produce the same image on a display a “TopLeft” image in PNG conventions would do.

So, by noticing the `from-bottom-left.png` is a top left image you just acknowledge the bug described here. This file is what ImageMagick must produce to be conformant to the TGA specification.

You can now verify the bug by yourself by using latest ImageMagick code, by doing this:

```sh
magick convert reference-bottom-left.tga from-bottom-left-2.png
```

Same would do with:

```
magick convert raw-bottom-left.tga from-bottom-left-2.png
```

Note: using `-auto-orient` produces a file that displays properly but that's not because the implementation is bug free, it's because when doing so the bug is done two times (cancelling itself).

**Comment by dlemstra** [comment]
We do not consider this a bug we will read the image as it was stored and preserve the orientation of how it was stored. I don't see any reason to reopen this issue.

**Comment by illwieckz** [comment]
I noticed no one answered this question from the reporter:

> Further, has anyone looked at my particular images and verified that the input uses an orientation flag?

The provided `lm_0000.tga` input file does not use any orientation flag.

This can be verfied in multiple ways.

First the source code of the tool (`q3map2`)  having produced the file does not seems to set any vertical or horizontal flip metadata bit.

Second this can be verified by looking at the produced file itself. Let's do it.

If the identification string is empty, the first bytes of the TGA files should be `0`, it is:

```
$ dd status=none bs=1 skip=0 count=1 if=lm_0000.tga | hexdump | head -n 1
0000000 0000
```

When the identification string is empty, the pixel depth should be stored offset 16 and the attribute byte should be stored at offset 17.

Because this is an RGB image without alpha channel, the depth should be 24-bit (`0x18`):

```
$ dd status=none bs=1 skip=16 count=1 if=lm_0000.tga | hexdump -v | head -n 1
0000000 0018
```

If the image is a 24-bit RGB image, the alpha depth should be `0`.

The attribute byte stores the alpha depth on bit `0-3`, then horizontal flip on bit `4` and vertical flip on bit `5`. Remaining bits `6` and `7` are unused and should be unset (`0`).

So a 24-bit RGB image without horizontal flip and without vertical flip should have the attribute byte equal to `0`. It is:

```
$ dd status=none bs=1 skip=17 count=1 if=lm_0000.tga | hexdump | head -n 1
0000000 0000
```

So the provided `lm_0000.tga` file has vertical flip metadata unset, meaning no vertical flip transformation should be done.

Third, we can verify it with the `file` utility:

```
$ file lm_0000.tga 
lm_0000.tga: Targa image data - RGB 1024 x 1024 x 24
```

That utility also report this as a 24-bit RGB image without vertical flip bit set (additional data would be printed otherwise).

For comparison, here is an example of 32-bit RGBA image with vertical flip bit set:

```
$ file vertical-flip.tga
vertical-flip.tga: Targa image data - RGBA 32 x 32 x 32 - 8-bit alpha - top
```

The TGA is a bottom-left storage format, so any bottom-left metadata on a bottom-left format does not code a vertical flip, but the absence of any vertical flip.

Also it looks like this question by @urban-warrior was not answered:

> Question, does ImageMagick currently produce the expected results for TGA?

It appears not. ImageMagick vertically flips the data when vertical flip bit is unset.

**Comment by dlemstra** [comment]
You are not adding any new information @illwieckz. I have now told you multiple times that we don't consider this to be a bug. The way we read the image and how we set the orientation might not work for your situation. Maybe you should look for a different library to use?

**Comment by illwieckz** [comment]
@dlemstra do you have any proof that the current implementation of ImageMagick verifies this statement:

> we will read the image as it was stored and preserve the orientation of how it was stored

Or do you have any test the result would make you believe it is verified, so I may look at such test to find eventual flaws in the testing itself?

I have pursued the independent testing of ImageMagick by feeding its input with more formats. At this point it's not fuzzing, it's just feeding input with default formats and default or standard orientations.

I can understand why a tool can want to have intermediary representations that would not be conformant to the input or the output format for various reasons, for example for not having to do operations on internal buffers. Same for tools that are expected to be part of a larger pipe, as long as the orientation is preserved in one mean or another so the final step can produce the expected file. But this thread is not about that.

Also this thread is not about discussing needs outside of the need of being conformant to specifications. This is not about this or that usage, it's about being conformant to specifications and about being reliable.

I have extended the study to more formats outside of TGA and PNG, and as usual I've done it in a clean room manner by re-implementing some converters from specifications to avoid any bias that may come from ImageMagick source code. I've figured out more situations where ImageMagick does wrong things with orientation:

- It happens with some format combination that when converting from a format A to a format B, and both formats have the same internal storage orientation and both the input and the output file have the same metadata orientation, the image is reverted on display.
- I also discovered that with some format combination, converting from format A to format B to format A may not give back the original orientation, while converting from format A to format C to format A may give back the original orientation even if intermediary C is wrongly orientated.

At some point the ImageMagick project is likely to receive more bug reports, and reports that would not be duplicate of this one neither duplicate of others that have already been reported to my knowledge and not be duplicate of this one either. The more I test ImageMagick with default inputs, the more I find problems, like it's not possible for the user to expect the `convert from B to A` function to be the inverse function of `convert from B to A` function when using ImageMagick tools.

I'm currently too busy to do the writing and publishing of the additional findings in the paper right now but be sure I'll do it.

While waiting for my publication, can you answer this simple question:

_When an user does the command `identify -format "%[orientation]" <image file>`, does the tool answer the storage format convention or the metadata for display orientation?_

**Comment by dlemstra** [comment]
I am going to lock down this issue. Please accept that we a have different viewpoint on the situation. And to answer your question. It depends on the image format how the orientation is determined.
