### ISSUE TITLE
version 7.1.0.1 crashes when resizing JPEG file (version 7.0.11.14 does not crash)

### ISSUE THREAD

**Issue by vlad312** [ImageMagick/ImageMagick#3864]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
- [X] I have verified that I am using the latest version of ImageMagick

### ImageMagick version

7.1.0.1

### Operating system

Linux

### Operating system, version and so on

Debian (sid)

### Description

I'm using ImageMagick version 7.1.0.1-dmo1, binaries installed from:
https://deb-multimedia.org/dists/unstable/main/binary-amd64/package/imagemagick-7

When processing an attached image, ImageMagick crashes:

$ /usr/bin/convert -quality 95 -resize 300 053479224927.jpg 053479224927_300.jpg
double free or corruption (!prev)
Aborted

$ /usr/bin/convert --version
Version: ImageMagick 7.1.0-1 Q16 x86_64 2021-06-21 https://imagemagick.org
Copyright: (C) 1999-2021 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules OpenMP(4.5) 
Delegates (built-in): bzlib djvu fontconfig freetype gslib heic jbig jng jp2 jpeg lcms lqr ltdl lzma openexr pangocairo png ps raqm raw tiff webp wmf x xml zip zlib

![053479224927](https://user-images.githubusercontent.com/67744556/123214186-9058f580-d4cf-11eb-868b-ec321eb6f663.jpg)

### Steps to Reproduce

see above

**Comment by fmw42** [comment]
ImageMagick 7 is particular about the command order. It should be read the input first, then settings then operators, then the output. Also in ImageMagick 7, use magick not convert. So try

`magick 053479224927.jpg -resize 300 -quality 95 053479224927_300.jpg`

**Comment by dlemstra** [comment]
Probably related to this issue: https://github.com/ImageMagick/ImageMagick6/issues/159.

**Comment by dllu** [comment]
I can reproduce it. I've attached a `valgrind` log.
[convert.log](https://github.com/ImageMagick/ImageMagick/files/6713156/convert.log)

By the way, `magick` also crashes with the same crash.

**Comment by fmw42** [comment]
I get the following in IM 7.1.0.1 Q16 Mac OSX Sierra

`magick 123214186-9058f580-d4cf-11eb-868b-ec321eb6f663.jpg -resize 300 -quality 95 x.jpg`
magick(1330,0x7fff9bcb73c0) malloc: *** error for object 0x7fb7ef807400: incorrect checksum for freed object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6

**Where did the JPG originate?  What JPG library/qtables created it?**

**Comment by dllu** [comment]
I get the crash when resizing all the jpegs that originate from my Fujifilm GFX 50R camera, so I don't think there is anything particularly special about the jpeg files that crash imagemagick. And I know that this didn't happen with previous versions of imagemagick since I've been using it to resize my photos for many years.

**Comment by fmw42** [comment]
I can resize other JPGs just fine with IM 7.1.01. Perhaps it is the dimensions of your image. If I crop it, it resizes OK. This works.

`magick 123214186-9058f580-d4cf-11eb-868b-ec321eb6f663.jpg[100x100+0+0] -resize 300 -quality 95 x.jpg`

However, this fails:

`magick 123214186-9058f580-d4cf-11eb-868b-ec321eb6f663.jpg[500x500+0+0] -resize 300 -quality 95 x.jpg`

So perhaps it is because it is being minified.

This also works -  a simple copy.

`magick 123214186-9058f580-d4cf-11eb-868b-ec321eb6f663.jpg x.jpg`

**Comment by dllu** [comment]
Here's a reasonably sized 50 megapixel picture I used that also crashes imagemagick: https://i.dllu.net/2021-06-23-13-57-47_DSCF9873_95942623fe49e44c5d6d93496f8f848d50a52fda.jpg

Bear in mind my machine has 64 GB of ram and resizing this shouldn't be any problem, and as I mentioned in my previous comment, it worked fine for years with the same size image and suddenly starts crashing now. Graphicsmagick also resizes it instantly.

I'm running a `git bisect` now to see which commit caused the regression.

**Comment by dllu** [comment]
Actually you know what, I think https://github.com/ImageMagick/ImageMagick/commit/601356f1d2881b57945de8c22349d8758927f76a fixed it. With both my image and OP's image, it seems that `601356f1d2881b57945de8c22349d8758927f76a` doesn't have the bug but `46b37479fb7ddec1455a040c72aae0f61c76d46` crashes. 

This would make sense since `coders/jpeg.c` calls `ConcatenateStringInfo`.
