### ISSUE TITLE
[Bug] Don't delete old values of PATH after Chocolatey upgrade

### ISSUE THREAD

**Issue by Kristinita** [ImageMagick/ImageMagick#389]
### 1. Summary

I need manually delete old values of PATH system environment variable after upgrade ImageMagick in Chocolatey.

### 2. Expected behavior

Automatically delete old values of PATH system environment variable.

### 3. Actual behavior

![PATH](http://i.imgur.com/4FlEaln.png)

### 4. Steps to reproduce

I install and upgrade ImageMagick [**use Chocolatey package**](https://chocolatey.org/packages/imagemagick). For example, I have ImageMagick 7.0.4 version → `choco upgrade imagemagick -y` → I upgrade ImageMagick to 7.0.5 version. But value of deleted folder `C:\Program Files\ImageMagick-7.0.4-Q16` don't remove into my PATH system environment variable.

### 5. Environment

**Operating system and version:**
Windows 10 Enterprise LTSB 64-bit EN
**ImageMagick:**
7.0.5-0 Q16 x64 2017-02-20
**Chocolatey:**
0.10.3

Thanks.

**Comment by dlemstra** [comment]
We did not create that package on Chocolatey. I think you will need to contact the author yourself: https://chocolatey.org/profiles/bdukes, https://twitter.com/BrianDukes.

**Comment by Kristinita** [comment]
@bdukes, what do you think about this problem?

Thanks.

**Comment by bdukes** [comment]
The Chocolatey package runs the uninstaller before upgrading, because the installer isn't silent when upgrading (or, at least, wasn't back when the package was originally created).  So, I think this is probably an issue from the uninstaller, rather than an issue with the installer.  If there's a different set of command line switches that the Chocolatey package can use (either to upgrade silently or to remove the PATH on uninstall), I'm definitely open to updating the package as necessary.

**Comment by dlemstra** [comment]
This issue will be resolved in the next release that should be publish today. The following commit fixed the bug: https://github.com/ImageMagick/VisualMagick/commit/54d95132f451462dbcb9fadd68171db51717c478
