### ISSUE TITLE
ImageMagick creates huge temporary files

### ISSUE THREAD

**Issue by serghei-topor** [ImageMagick/ImageMagick#395]
The trouble is described in this thread https://www.imagemagick.org/discourse-server/viewtopic.php?t=23649

I have a cron job which removes **magick** files every 1 minute as a short term solution
`find /tmp -maxdepth 1 -type f -name "magick-*" -delete`

Does this trouble have solution? Thanks in advance

My current environment:
ImageMagick 6.8.9-9 Q16 x86_64
Ubuntu 16.04 LTS

**Comment by mikayla-grace** [comment]
ImageMagick requires temporary disk space, for example, when you utilize a delegate program or if you are processing a large file that exceeds the memory resources of your system.  When the command completes, there should not be any magick-* files left over.  If there is, its a bug-- unless ImageMagick fails due to some unrecoverable error.  An example is, if you only have a small amount of free space in your /tmp folder and ImageMagick memory maps the file and the /tmp partition fills up.  For that scenario, the OS issues an unrecoverable signal so the magick-* file remains.

If you do find magick-* files remain, first try ImageMagick 6.9.7-10, the latest release.  If that leaves orphan temporary files, post here with your command so we can reproduce the problem.

**Comment by serghei-topor** [comment]
@mikayla-grace thaks, I'll try

Just for additional information:

- I use ImageMagick from command line for cropping

- all cropping operations are organized as background jobs (web service is written in RoR, for background operations I use DelayedJob framework)

- Everage image file size is 1 Mb

- System always gets in /tmp folder 2 magick- files; each file has constant size in 232 GB, so total size is 464 Gb

**Comment by jrothrock** [comment]
Currently having this issue as well, ROR 5, background process with sidekiq, but I'm using ffmpeg to create a snapshot of a video, and optimize the image with minimagic (carrierwave). 

Image ends up being a couple KB, but the file in the temp is 32GB. 

I have a 40GB DO droplet, and from doing ```du -su *``` at the root, it seems like it's just taking up all the remaining available space. 

The file does clear when ffmpeg, or carrierwave, is finished though, but sometimes the process will fail throwing non enough space error, and the files won't delete

**Comment by jrothrock** [comment]
Okay so I figured out what was going on, on my end. I had minimagic running in my video uploader for carrierwave, when it shouldn't have been, I think it then tried to run imagemagick over the video. I just had to remove the minimagic process in the video uploader

**Comment by d4vidmiller** [comment]
This seems to be happening to us also. We are running ImageMagic 6.7.8.9

Any help is appreciated.

**Comment by serghei-topor** [comment]
@d4vidmiller Probably it may help you - in ImageMagick in configuration file you can strictly limit the size of the temporary files. https://www.imagemagick.org/script/resources.php#configure 

In my case I had 2 dump files and each file had 250 GB and 400 Gb as the total size of /tmp folder, and these magick dumps were hanging the system

**Comment by terion-name** [comment]
Same issue

**Comment by mikayla-grace** [comment]
See .  https://www.imagemagick.org/script/security-policy.php.  Set policies to limit the amount of resource ImageMagick is permitted to consume.  See https://www.imagemagick.org/script/architecture.php to estimate the amount of resources ImageMagick requires to read, process, and write an image or image sequence.

**Comment by unhammer** [comment]
Sorry, I've been reading the links posted by @mikayla-grace and I'm still not sure how to interpret the policy.xml settings. Am I correct in assuming that when I've added 
```
  <policy domain="resource" name="memory" value="2GiB"/>                                                                                                                                       
  <policy domain="resource" name="disk" value="1GiB"/>
```
(which gives me
```
$ identify -list policy

Path: /etc/ImageMagick-7/policy.xml
  Policy: Resource
    name: disk
    value: 1GiB
  Policy: Resource
    name: memory
    value: 2GiB

Path: [built-in]
  Policy: Undefined
    rights: None 
```
) then ImageMagick will not create tmp-files over 1GiB (per file) and at most malloc 2GiB?

**Comment by Erudition** [comment]
Same problem. likely due to inadvertently processing a video. Problem is Now my disk is so full I can't even delete the file...
```bash
sudo rm -rf magick-20592fpKOr42kW0ma.pam 
rm: cannot remove 'magick-20592fpKOr42kW0ma.pam': Read-only file system
```

**Comment by urban-warrior** [comment]
Your disk got an error and it was set to read-only to help prevent further errors.  Try unmounting and remounting the file system or perhaps rebooting.

**Comment by marcelogrsp** [comment]
Hi guys, how did you sort it?

**Comment by ghareesh** [comment]
While trying to convert pdf to tiff image, the solution gets stuck in one place and generates lot of 
magick-xxxxxx files in temp.. Seems to repeat at same point while re executing..How can I troubleshoot this?

**Comment by fmw42** [comment]
Where is the PDF file?  We need that to test. Also what is your ImageMagick version and platform?

**Comment by unkn0wn-developer** [comment]
How did you guys resolve this?

**Comment by unkn0wn-developer** [comment]
> See . https://www.imagemagick.org/script/security-policy.php. Set policies to limit the amount of resource ImageMagick is permitted to consume. See https://www.imagemagick.org/script/architecture.php to estimate the amount of resources ImageMagick requires to read, process, and write an image or image sequence.

Can this cause other problems when something that big actually needs to be processed uncompressed?

**Comment by unkn0wn-developer** [comment]
> If you read the architecture document carefully, you'll see you can limit memory and image pixels are forced to disk. The processing is slower but it helps prevent ImageMagick from thrashing your system. You can even limit your disk by policy so that if the limit is exceeded, ImageMagick will exit. See https://imagemagick.org/script/security-policy.php for a good starting point for setting polices for your environment.

Thank you so much for your quick reply!! :)
I'm going to edit "/etc/ImageMagick-6/policy.xml" and uncomment/edit the following line:
from
```
  <!-- <policy domain="resource" name="disk" value="16EiB"/> -->
```
to 
```
<policy domain="resource" name="disk" value="5GB"/>
```
to avoid ending up with 64gb temp file causing disk problems in the worst case scenario.

We don't mind something slowing down as long as it still works.
We definitely don't want this setting to crash the uploads because temp file is too small.


* Also, how do I determine the maximum disk size I need for optimal performance?

I couldn't find any guides regarding that.
I saw people randomly commenting on other gitlab issues "oh this much gb worked for me, that much gb worked for us" but it looks like they find that by trial and error.

* Is there a concrete fact/calculation that I can use?
For example, what caused 64gb temp file that we got? Was it a 20000000x20000000px image file? or how big of an image file that 64gb can utilize in realistic terms?
For example, We don't care anything bigger than a thumbnail created from an 8k video (7680 x 4320). 
How much GB/MB that would be when it's uncompressed and processed by ImageMagick?

**Comment by urban-warrior** [comment]
> How much GB/MB that would be when it's uncompressed and processed by ImageMagick?.

Read the architecture guide carefully.  It tells you exactly how to calculate the answer to your question-- that is for the pixel cache.  Some image processing algorithms consume operational memory.  Even then, we have memory methods to mitigate large requests, e.g. memory-mapping the request on disk instead of heap memory.

> For example, what caused 64gb temp file that we got? 

Likely a very large image file.

> Also, let's say ImageMagick crashed and it left a temp file behind?

ImageMagick intercepts whatever signals it can and cleans up temporary files automagically.  For signals it cannot catch, like SIGBUS, some files might be left behind.  However, if you set the cache synchronize policy to true, SIGBUS should never be thrown.  In our online studio @ magickstudio.imagemagick.org, the script checks for any temporary files that are over some threshold hours old and automatically deletes them.  The online studio has been running for over a decade and we have never had any downtime other than routine maintenance thanks to this security policy (some parts obfuscated):

```
<policymap>
  <policy domain="resource" name="temporary-path" value="/always-use-something-other-than/tmp"/> 
  <policy domain="resource" name="memory" value="256MiB"/> 
  <policy domain="resource" name="list-length" value="32"/> 
  <policy domain="resource" name="width" value="8KP"/> 
  <policy domain="resource" name="height" value="8KP"/> 
  <policy domain="resource" name="map" value="512MiB"/> 
  <policy domain="resource" name="area" value="16KP"/>
  <policy domain="resource" name="disk" value="1GiB"/> 
  <policy domain="resource" name="file" value="768"/> 
  <policy domain="resource" name="thread" value="2"/>
  <policy domain="resource" name="time" value="120"/> 
  <policy domain="system" name="precision" value="6"/>
  <policy domain="cache" name="memory-map" value="anonymous"/>
  <policy domain="cache" name="synchronize" value="true"/>
  <policy domain="cache" stealth="true" name="shared-secret" value="that would be telling."/>
  <policy domain="coder" rights="write" pattern="{HTTP,HTTPS,MVG}" />
  <policy domain="filter" rights="none" pattern="*" />
  <policy domain="path" rights="none" pattern="@*"/>
  <policy domain="system" name="font" value="/somewhere/my-unicode-font.ttf"/>
</policymap>
```

**Comment by unkn0wn-developer** [comment]
> > Also, let's say ImageMagick crashed and it left a temp file behind?
> 
> ImageMagick intercepts whatever signals it can and cleans up temporary files automagically. For signals it cannot catch, like SIGBUS, some files might be left behind. However, if you set the cache synchronize policy to true, SIGBUS should never be thrown. In our online studio, the script checks for any temporary files that are over some threshold hours old and automatically deletes them. The online studio has been running for over a decade and we have never had any downtime other than routine maintenance thanks to this security policy (some parts obfuscated):

Thank you so much for providing a very detailed answer. That was super helpful!
Okay, so I've been reading the architecture guide in the past couple days. It answered most of my questions.
So, if we have `<policy domain="cache" name="synchronize" value="true"/>` where it's value set to true, it's impossible for imagemagick to crash and leave orphan files like 64gb file that we got. Probably, the system would run out of space or have another problem but ImageMagick would recover from it and it would clean up that temp file before the process stopped.

However, considering that we don't want 64gb file anyway, I will also set this line`<policy domain="resource" name="disk" value="1GiB"/>` and voila. I believe that everything should work as expected. Right?

I hope that I understood everything right. It's time to implement all that now 🎉

**Comment by urban-warrior** [comment]
> it's impossible for imagemagick to crash and leave orphan files like 64gb file that we got

Let's say its improbable.

> and voila. I believe that everything should work as expected. Right?

Well it depends on your expectations.  But if your goal is to ensure your online system can't be taken down by some nefarious or accidental means while utilizing ImageMagick, the security policy we provided should go along way toward that goal.  However, we of course, as a provider of free software, can not make any guarantees.   To help ensure stability, with the security policy, you are limiting the amount of memory any one ImageMagick process can consume, how much disk, how many threads, which image types are permitted to be read or written, how much processing time, etc.  If any of these policies are violated, ImageMagick will throw an exception.  However, don't rely on ImageMagick to keep everything secure.  If your app download's files off the Internet, you likely want to limit the filesize.  You may want to sanitize any parameters an online user is setting.  You may want to track your users to identify any nefarious behaviors and block them, etc.

**Comment by unkn0wn-developer** [comment]
> > it's impossible for imagemagick to crash and leave orphan files like 64gb file that we got
> 
> Let's say its improbable.
> 
> > and voila. I believe that everything should work as expected. Right?
> 
> Well it depends on your expectations. But if your goal is to ensure your online system can't be taken down by some nefarious or accidental means while utilizing ImageMagick.......

Hey, I'm back again. First of all, I'd like to thank you again for your previous helpful responses.

 I had another question regarding this. If I set

`<policy domain="resource" name="disk" value="1GiB"/>`

and if I don't enable "synchronize=true" to not take a performance hit (up to 5x).
`<!-- <policy domain="cache" name="synchronize" value="true"/> -->`

As long as I have 1GiB disk space, would I be fine without "synchronize"?

**Comment by deltaforce** [comment]
I have also started having this issue on several sites. 
I am getting disk usage alerts for sites, logging in and find a whole bunch of magick files have been created today and used up all the disk quota.

the thing is that I have not made any changes on any of these sites for months. So no images have been uploaded or resized, so I am confused as to why imagemagick is even running and has even created these files.

**Comment by fmw42** [comment]
temp files are working files for ImageMagick and should get  deleted automatically. However, if you run out of temp space they will be left behind. You can delete them manually and hopefully you won't run out of temp space. If you create/convert large images, be sure you have enough temp space to hold them.

**Comment by deltaforce** [comment]
I know what they are ... I think you have completely missed the point.
Imagine if your car keeps running out of petrol, even though it has been sitting on the driveway for 6 months and nobody has driven it. How is the petrol getting used up?

**Comment by dave105010** [comment]
Hi,

I'm back again.
`<policy domain="resource" name="disk" value="1GiB"/>`
AND
`<policy domain="cache" name="synchronize" value="true"/>`

both don't work.

Many months later, we ended up with 46GB+ random imagemagick temporary file again.
![Screen Shot 2021-10-28 at 12 51 35 PM](https://user-images.githubusercontent.com/61291225/139496168-72958073-a68a-4063-8d0c-e223101997ee.png)

This should be re-opened and investigated further.

**Comment by fmw42** [comment]
Your system or ImageMagick command is crashing leaving those files behind.  Run an automated system cleanup of that directory every night might help you.

**Comment by dave105010** [comment]
> Your system or ImageMagick command is crashing leaving those files behind. Run an automated system cleanup of that directory every night might help you.

That's what we are doing right now but that kind of solution feels hacky. This file is obviously created by ImageMagick and we never ever process any file that might potentially end up 46GB even when it's uncompressed. I'm including videos, images, and everything else while thinking about this all. Also, our applications don't record any errors on any of the operations. This must be a bug or a recursive command running in the background in an infinite loop due to some mistyped equal sign or something.

I've been investigating this for months and I can't reproduce it manually and as I said nothing that uses ImageMagick fails or reports any error messages. Everything runs perfectly fine. It's just this file randomly appears out of nowhere.

**Comment by urban-warrior** [comment]
We'll investigate.  Keep in mind that there are certain signals that we cannot recover from such as SIGBUS.  But they sync should help prevent against SIGBUS.

**Comment by dave105010** [comment]
Thank you so much!! synchronize is also set to true in our environment. 
I know these kinds of odd bugs must be hard to find and fix.
In any case, we appreciate you all for taking the time and investigating this issue on behalf of everyone in this GitLab thread.

**Comment by urban-warrior** [comment]
PAM files are created by delegate programs and libraries which we have less control over.  If the delegate fails, we catch the status and theoretically we clean up the temporary files, however, it may not always work.  If you can identify a command-line that always leaves behind a temporary file, that would be helpful.  Otherwise, we'll run tests in our development library, however we suspect we will not be able to reproduce the problem.

**Comment by brendon** [comment]
I've suddenly started experiencing this problem also. Super tricky to track down the cause too. I suspect a rogue file or potentially accidentally processing a video as others have suggested. The files are around 40GB but really they're as large as will fix on the remaining empty space on the disk. I'm not sure if they wouldn't have gotten bigger if they could. My policy seems reasonable. Is there a way to restrict how big these tmp files can get?

```
Policy: Resource
    name: disk
    value: 1GiB
  Policy: Resource
    name: map
    value: 512MiB
  Policy: Resource
    name: memory
    value: 256MiB
  Policy: Resource
    name: area
    value: 128MB
  Policy: Resource
    name: height
    value: 16KP
  Policy: Resource
    name: width
    value: 16KP
```

This is just a default Ubuntu 20.04 install.

**Comment by ronilaukkarinen** [comment]
We have the same problem.

**Comment by charleslcso** [comment]
Me too. Huge magic-xxxxxxxxxxxxxxxxxxxx files are created in /tmp when it tries to generate thumbnails for .mp4 files. Program that triggers Imagick to run is FileRun.

**Comment by fmw42** [comment]
Likely because Imagemagick loads the whole mp4 file to process a thumbnail.  What was your exact command.  In any case, the file should be automatically deleted after finishing. If it fails, then it might leave the file around until /tmp is cleared.

**Comment by zerodeux** [comment]
Just ran into this ... Imagemagick interrupted by a timeout, left huge temps files behind.

I'm a bit surprised that it does not make use of the usual Unix pattern "open, unlink" which let the current process use the temp file, while making sure 1/ it is not reachable from other processes and 2/ it will be removed from the filesystem whatever fate waits the process (sigbus, etc.).

**Comment by urban-warrior** [comment]
We avoid using the "open, unlink" pattern with ImageMagick due to compatibility issues between Linux and Windows. Additionally, closing files promptly helps reduce the number of simultaneous open file descriptors.

ImageMagick attempts to delete temporary files for any signals it can intercept. Could you provide steps to reproduce the issue of leftover temporary files? If we can replicate it and identify it as a bug, we'll prepare a patch to resolve the issue promptly.

**Comment by brendon** [comment]
So weird that this just comes up again. I had this take down our server a couple of days ago after nothing for a long time (2021?). Filled the root partition with a 25GB file in the `/tmp` folder. Fortunately it was quick to find and easy to delete bit still. Hoping it was a one-off.

**Comment by fmw42** [comment]
Please post your command and error message and also your policy.xml file.  Also how much space do you have allocated in /tmp.  What are the dimensions of the image, not the file size?

**Comment by zerodeux** [comment]
I just realized my scenario is PHP with imagick extension, Imagemagick code thus running embedded within the PHP interpreter (sorry, this is not my app, I thought at first it was system()-invoking `convert` and such like tons of PHP apps).

The PHP script hits the max_execution_time limit (which is wanted) :

    Fatal error: Maximum execution time of 30+2 seconds exceeded (terminated) 

Since I'm using the (fast)CGI SAPI, the process is not terminated, only the current HTTP request is (the same process is recycled to handle many HTTP requests). I think it explains the tempfile leak I'm observing. However I know PHP extensions can register to a script termination hook for their cleanup, thus I would expect imagick to avoid such leaks (because I think the PHP developer has no way of fixing this from the PHP code).

So maybe I'd rather file something at https://github.com/Imagick/imagick ?

**Comment by urban-warrior** [comment]
We are of course interested in any file leaks due to ImageMagick.  We can't speak to issues with iMagick, CGI, HTTP service, etc.  If after further analysis you find the root cause is ImageMagick, let us know how to reproduce the issue and we will investigate further.

**Comment by johandenhollander** [comment]
Just posting here to let you know we have issues with quickly filling up of /tmp too because of the Magick temp files.
This was not an issue before but since a few weeks it is.
Using it with PHP 8.3 and Nginx on Ubuntu.

**Comment by brendon** [comment]
I wonder if there's a new attack vector someone has discovered or perhaps a bug in a recent update? We've only have the one occurrence so far.

**Comment by zerodeux** [comment]
I made a follow-up ticket to the imagick extension : https://github.com/Imagick/imagick/issues/681

I tried to read the Imagick module code but could not figure out if the modules takes care of releasing objects and temp files upon abnormal script termination. I asked them.

**Comment by deltaforce** [comment]
everyone please note, this topic is from 2017, this is not a new issue and obviously still ha snot been fixed.

**Comment by brendon** [comment]
This is still happening to us fairly regularly. Is there any kind of logging we can add to assist you in identifying the source of the runaway tmp file size? The last one was 19GB.

**Comment by fmw42** [comment]
@brendon What was your command line?

**Comment by brendon** [comment]
It's being triggered via the Rmagick gem I think, so I don't have the command line to hand. Next time it happens I'll have a closer look at the logs to see if there is one that coincides somewhat.

**Comment by brendon** [comment]
Ok, so I've figured out what is causing it on my end (at least one occurrence). A user is uploading a `.mp4` file. Somehow (and I need to look into this after writing this post) it's being processed by Imagemagick.

Imagemagick proceeds to create a `/tmp` file that fills the disk. In my case it's the root partition and kills the machine.

I don't think Imagemagick should behave like this even if it's given stupid input. The uploaded file is only 200 odd megabytes. The temp file it creates is 15GB. It then crashes and doesn't clean up after itself.

The content of the file itself is this (repeated):

```
deploy@v7:/tmp$ cat magick-1745656_Grd1I4IEnMx.pam
P7
WIDTH 1920
HEIGHT 1080
DEPTH 3
MAXVAL 255
TUPLTYPE RGB
ENDHDR
P7
WIDTH 1920
HEIGHT 1080
DEPTH 3
MAXVAL 255
TUPLTYPE RGB
ENDHDR
P7
WIDTH 1920
HEIGHT 1080
DEPTH 3
MAXVAL 255
TUPLTYPE RGB
ENDHDR
P7
WIDTH 1920
HEIGHT 1080
DEPTH 3
MAXVAL 255
TUPLTYPE RGB
ENDHDR
P7
```

There's actually some non-printing characters between each of the repetitions. Perhaps it's outputting each frame or something.

I do hope that helps. I think this is something that should be mitigated at least as the default behaviour to just fill the disk and not clean up in the end after reaching a hard limit doesn't seem ideal. :)

**Comment by brendon** [comment]
Running `identify` on this mp4 on my Mac just causes it to sit there and do apparently nothing. I assume it's parsing the file? No disk usage increase on the Mac though.

**Comment by urban-warrior** [comment]
See https://imagemagick.org/script/architecture.php#tera-pixel on how to efficiently process large image files.  See https://imagemagick.org/script/security-policy.php on how to limit resource consumption on your host.

**Comment by brendon** [comment]
Short of managing side effects, is there a way to make sure `idenfity` just returns 'not an image' if it's used against an mp4, rather than spawning a ffmpeg process and grinding away until the disk is full?

**Comment by brendon** [comment]
I have come across `<policy domain="delegate" rights="none" pattern="mpeg:decode" />`. Is that enough to stop `idenfity` trying to work with the file?

**Comment by urbels** [comment]
Issue going for years but it is closed. Any news for the fix?

**Comment by brendon** [comment]
> Issue going for years but it is closed. Any news for the fix?

Adding this to policy.xml solved it for me:

```
<policy domain="delegate" rights="none" pattern="mpeg:decode" />
```

It prevents ImageMagick from processing MP4 files.

**Comment by urban-warrior** [comment]
ImageMagick attempts to consume the entire video sequence which can be resource intensive.  One solution is to disable the MPEG decoder, another is to add a policy that limits how large a sequence is permitted, e.g., 32 frames.  Yet another solution is to add '[0]' to your image filename to only read the first frame of a video, e.g., `video.mp4[0]`.

**Comment by brendon** [comment]
> ImageMagick attempts to consume the entire video sequence which can be resource intensive. One solution is to disable the MPEG decoder, another is to add a policy that limits how large a video sequence is permitted, e.g., 32 frames. Yet another solution is to add '[0]' to your image filename to only read the first frame of a video, e.g., `video.mp4[0]`.

Great advice! In my case it was being called via an intermediate Ruby Gem that isn't frequently updated, and I wasn't using the 'thumbnail' being generated in that case so I just disabled mp4's altogether :)
