### ISSUE TITLE
Merging PDFs fails with "not allowed by the security policy `gs'"

### ISSUE THREAD

**Issue by ChristophSchmidpeter** [ImageMagick/ImageMagick#4065]
### ImageMagick version

7.1.0.4

### Operating system

Linux

### Operating system, version and so on

Arch Linux (updated on 10.08.21

### Description

The command
`convert InputPdf1.pdf InputPdf2.pdf OutputPdf.pdf`
to merge the PDFs InputPdf1.pdf InputPdf2.pdf fails with the error message

> convert: attempt to perform an operation not allowed by the security policy \`gs' @ error/delegate.c/ExternalDelegateCommand/386.
convert: no images defined `OutputPdf.pdf' @ error/convert.c/ConvertImageCommand/3322.

### Steps to Reproduce

- Have two PDFs in your current folder, e.g. InputPdf1.pdf InputPdf2.pdf
- Run the command
`convert InputPdf1.pdf InputPdf2.pdf OutputPdf.pdf`

**Comment by fmw42** [comment]
There is a security policy called policy.xml on your system. The default is no to allow reading or writing of PDF/PS/EPS etc due to an old security flaw in Ghostscript. You should edit the policy.xml file to set the permissions to "read|write" for those file types. Also be sure your ImageMagick install has Ghostscript installed and can see it. `convert -version` should list "gs" or "gslib" if you have it installed.

**Comment by snibgo** [comment]
As fmw42 says.

As you use IM v7, I suggest you use "magick" instead of "convert".

To see the policy currently in effect:
```
magick -list policy
```
