### ISSUE TITLE
Converting from LAB to RGB leads to wrong colors

### ISSUE THREAD

**Issue by stklaudert** [ImageMagick/ImageMagick#4105]
### ImageMagick version

7.1.0-4

### Operating system

MacOS

### Operating system, version and so on

11.3

### Description

Hi,

We have an issue with the conversion from lab to rgb. By now we use imagemagick 7.0.7-4 and everything is okay.
We us an input profile (CIELabD50) and an output profile (ProPhoto). The conversion is done and the Prophoto profile is embedded in output jpg.

Now we want to update to newer version and see uncorrect colors in the resulting image.
We tried version 7.1.0-4 on mac and also on linux, but same result.
The output image has no embedded profile, but the colorspace is changed from lab to rgb.

Could you please help us and let us know, if we are missing something here?

Thank you,
Stefan

### Steps to Reproduce

magick lab_test.tif -profile profiles/CIELabD50.icc -intent absolute -profile profiles/ProPhoto.icc test.jpg

### Images

[lab-rgb.zip](https://github.com/ImageMagick/ImageMagick/files/7032152/lab-rgb.zip)

**Comment by fmw42** [comment]
I do not understand. What makes you think the result is wrong? What are you comparing to?

**Comment by snibgo** [comment]
> The output image has no embedded profile, but the colorspace is changed from lab to rgb.

Something is wrong. Your test.jpg does have an embedded profile.

When I run your command, with IM v7.1.0-4 on Windows 8.1, the output does have an embedded profile, as it should. My image is identical to yours.

How do you know the result is wrong? Please supply an "as required" image.

**Comment by stklaudert** [comment]
We expected an image as this, which was converted with imagemagick 7.0.7-4:
![expected](https://user-images.githubusercontent.com/79311147/130561467-330b2d49-b78d-4550-9e6b-b00220e19288.jpg)

**Comment by snibgo** [comment]
Short answer: yes, IM behaviour has changed, but I don't know if a bug has been removed or introduced. Try "-colorspace sRGB" instead of profiles.

Long answer:

lab_test.tif contains metadata declaring it to be encoded with CIElab, but with no embedded ICC profile. How do you know that lab_test.tif was created with a profile? Perhaps it wasn't.

My computer has a roughly sRGB screen, not ProPhoto, so for my tests I convert the image to sRGB.

Viewing lab_test.tif in Gimp, I get a near-white background.

With IM v7.1.0-4 "-colorpace sRGB", I get a near-white background:
```
%IMG7104%magick lab_test.tif -colorspace sRGB -resize 600 x1.jpg
```
![x1](https://user-images.githubusercontent.com/33812368/130652893-0fee4f4a-b5a3-4ee6-8e33-9497736fd83d.jpg)

This makes me suspect that lab_test.tif was created with simple arithmetic, not with a profile.

Next, we test by assigning the CIELabD50.icc profile to lab_test.tif, then converting to a sRGB profile.

With IM v7.0.3-5 (non HDRI) "-profile", I get a near-white background:
```
%IMG7036%magick lab_test.tif -profile CIELabD50.icc -profile sRGB.icc -resize 600 x2.jpg
```
![x2](https://user-images.githubusercontent.com/33812368/130652933-3798ef59-f691-470e-bb8e-60505395a142.jpg)

With IM v7.1.0-4 (with HDRI) "-profile", I get a dull orange background:
```
%IMG7104%magick lab_test.tif -profile CIELabD50.icc -profile sRGB.icc -resize 600 x3.jpg
```
![x3](https://user-images.githubusercontent.com/33812368/130653006-6c171b8c-d687-4c36-986b-b2d32702b964.jpg)

Which of these is correct? Without knowing the history of lab_test.tif and CIELabD50.icc, I can't be sure. Devising a black-box test isn't easy. We can create a CIELab image with IM and try that.

```
%IMG7036%magick ^
  hald:8 ^
  ( +clone ^
    -define precision:highres-transform=true ^
    -profile sRGB.icc -profile CIELabD50.icc -profile sRGB.icc +write x1.tiff ^
  ) ^
  -metric RMSE -format "%%[distortion]\n" -compare info:

0.00802869
```

```
%IMG7104%magick ^
  hald:8 ^
  ( +clone ^
    -define precision:highres-transform=true ^
    -profile sRGB.icc -profile CIELabD50.icc -profile sRGB.icc +write x1.tiff ^
  ) ^
  -metric RMSE -format "%%[distortion]\n" -compare info:

0.00804951
```
The results are close to zero, and virtually the same. This shows that the round-trip takes us back to where we started, and both versions of IM have this property. Nearly 1% RMSE is larger than I would like, but is trivial compared to the different between x2 and x3:
```
%IMG7104%magick ^
  x2.jpg ^
  x3.jpg ^
  -metric RMSE -format "%%[distortion]\n" -compare info:

0.326475
```

A better test would use an image encoded in CIELab that was _not_ created with IM. I can't find an example.

**Comment by shelaudert** [comment]
Hi everyone,

As my colleague is currently out of office, I'm taking over.

The source file lab_test.tif was created with Photoshop. As far as I know you can't embed a color profile in a LAB image file, at least Photoshop won't let you assign a color profile for LAB images.

For ImageMagick we use CIELabD50.icc as a default source color profile for the RGB conversion of LAB images which provide good conversion results for ImageMagick 7.0.7-4 but not for 7.1.0-4.

In Photoshop I can convert the LAB image to ProPhoto RGB without specifying a custom source color profile...
<img width="963" alt="Photoshop-color-conversion" src="https://user-images.githubusercontent.com/89517282/130792867-fe07f774-fa08-41ef-8cfc-01e839b3c88c.png">

... and it will give a good looking result:
![lab_test_photoshop](https://user-images.githubusercontent.com/89517282/130786451-91f8355b-9dc0-4088-af52-7243058f82ca.jpg)

How can I convert the LAB image to ProPhoto RGB (or any other RGB profile) in ImageMagick without specifying a source color profile? I tried the following command:

`magick lab_test.tif -intent absolute -colorspace sRGB -profile data/profiles/ProPhoto.icc out.jpg`

Here is the result for ImageMagick 7.1.0-4:
![lab_test_out_no_lab_profile_7 1 0-4](https://user-images.githubusercontent.com/89517282/130788226-3e0e3717-5488-4804-a70f-88bdf3840a58.jpg)

Unfortunately the colors of the resulting image do not look correct compared to result of ImageMagick 7.0.7-4 using CIELabD50.icc as the source color profile and compared to the conversion result of Photoshop. Do you have any other ideas?

**Comment by urban-warrior** [comment]
Try this command:
'''
magick lab_test.tif -colorspace sRGB -resize 600 x3.jpg
'''
In the mean-time, we will investigate the color profile transformation issue.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by dlemstra** [comment]
We have published a new release that fixes this @shelaudert. Can we close this issue?

**Comment by stklaudert** [comment]
We tested the fix and it works great!

Thank you for the fast solution!
