### ISSUE TITLE
Convert -resize webp image is cropped

### ISSUE THREAD

**Issue by alwaysmda** [ImageMagick/ImageMagick#4246]
### ImageMagick version

7.1.0-7

### Operating system

Windows

### Operating system, version and so on

Windows 7

### Description

trying to resize animated webp using the command:
convert input.webp -resize 512x512 output.webp

The file is resized to the correct **canvas** size but the image is larger than canvas so it will be cropped.

![image](https://user-images.githubusercontent.com/37049277/133881873-8aabc162-68f7-457d-97d4-c0723f0e7ccf.png)

![image](https://user-images.githubusercontent.com/37049277/133881861-ccc921b4-43a7-4d9f-8d7f-8daad3ca6852.png)

### Steps to Reproduce

resize any animated webp.

### Images

[input.webp.zip](https://github.com/ImageMagick/ImageMagick/files/7189491/input.webp.zip)

**Comment by urban-warrior** [comment]
Try this command:
```
convert input.webp -resize 512x512 +repage output.webp
```

**Comment by snibgo** [comment]
This is an animated webp. Each frame has a different size, and resizing each to the same size doesn't make sense. The frames are compressed in a similar way to GIF: each frame stores only the bounding rectangle of pixels that have changed. "-layers coalesce" removes this compression, so each frame contains the entire image at that point in time, and is 370x300 pixels. Resizing these does make sense.
```
magick 1.webp -layers coalesce -resize 512x512 out.webp
```

**Comment by pirate486743186** [comment]
i have a similar problem in version 6 in debian 11 32bits
it must be the same bug.

the same problem appears for some gifs.
example (nsfw)
https://chan.sankakucomplex.com/post/show/24446596

this command, will mess up the image in a similar fashion 
`convert in.gif -resize 500 out.gif`

The first layer seams correctly resized, the other layers are cropped.

The suggested command correctly converts the gif
`convert in.gif -layers coalesce -resize 500 out.gif`

not verified, but this suggest, that the bug is also present in apng.
