### ISSUE TITLE
Windows 10 saying ImageMagick contains a virus

### ISSUE THREAD

**Issue by stephlocke** [ImageMagick/ImageMagick#482]
Using the HTTP download link of ImageMagick-7.0.5-5-Q16-x64-dll.exe on the [ImageMagick download page](https://www.imagemagick.org/script/download.php), when attempting to install Windows 10 detected a threat and then halted the install process.

![image](https://cloud.githubusercontent.com/assets/6452610/25844370/1fe745d0-34a2-11e7-8a4b-c71bcfbd0d4f.png)

I now have in my quarantined items "Trojan:Win32/Clavior.G!cl"

**Comment by hrbrmstr** [comment]
Can you post the link to the d/l page?

**Comment by stephlocke** [comment]
Updated to include it: https://www.imagemagick.org/script/download.php

**Comment by stephlocke** [comment]
Blech, win10 doesn't like you c&P'ing text from it's threat detection stuff 
![image](https://cloud.githubusercontent.com/assets/6452610/25845081/76179688-34a4-11e7-8f3f-d48e2b165e81.png)

**Comment by hrbrmstr** [comment]
VirusTotal says all is 👍 with it: https://www.virustotal.com/en/file/7e6b15f16b492d094c9ed260ecf562cd204e376f45a5014ee42833d1d1deb906/analysis/1494323352/

But it does get detections elsewhere:

- https://www.metadefender.com/#!/results/file/ZTE3MDUwM0J5TVlEVEd3eVdya21LUFRHdmti/regular/analysis

And, you're also not alone in this happening: http://www.imagemagick.org/discourse-server/viewtopic.php?t=31889

I added to the IM discourse the post saying that folks are still getting the msg.

Metadefender also dislikes the HDR version so it's likely the culprit is one of the common DLLs between them and this is likely not really infected.

**Comment by mikayla-grace** [comment]
We build ImageMagick on AppVeyor which is a controlled environment. We keep copies of the original builds on a secure remote location. Checking the Windows binaries against these reference binaries shows no mods to the binary since it was released. We do have an upcoming release this weekend which hopefully will quell the noise from the virus scanners.

**Comment by dlemstra** [comment]
We ran another test with our latest installer and Filseclab is still reporting a false positive:

https://www.metadefender.com/#!/results/file/ZTE3MDUxNUIxb1o0ZjM4UHgtcmszWjRHMzh3eFo/regular/analysis

Virustotal has no false positives:

https://virustotal.com/nl/url/4e59c333920e359f98bcf3ab98eeb05ca6095874a31eb67076970b0b1cd4cf64/analysis/
