### ISSUE TITLE
'compose -multiply' does not produce satisfactory results of two input images

### ISSUE THREAD

**Issue by fu123456** [ImageMagick/ImageMagick#4847]
### ImageMagick version

7

### Operating system

Linux

### Operating system, version and so on

Manjaro (basically newest)

### Description

I have two images (i.e., a color image and a gray-scale mask image), and mulitply these two images, but I obtain a gray-scale image. Actually, I want to produce a color output image even if the mask is grayscale. In addition, if the mask is color, the result is correct (color). Please see the following figure. Thanks.
![位图](https://user-images.githubusercontent.com/22411577/154473695-ffa02ab1-6cb2-415b-84dd-5d2e139239b6.png)

### Steps to Reproduce

My command line is 'composite -compose Multiply test1.png test1_mask_sc.png outut.png'

### Images

three images I used here.
![Uploading test1.png…]()
![Uploading test1_mask_sc.png…]()

**Comment by fu123456** [comment]
My testing images are avaiable at https://drive.google.com/file/d/187RAFqHJCL6Cs5K821UVMCHD-CC_fKsm/view?usp=sharing

**Comment by snibgo** [comment]
You use IM v7, so I suggest you use "magick", not "composite" nor "magick composite".

The problem is that the "destination" of your compose is grayscale. The output medata is taken from the "destination", so that is also grayscale.

I suggest you ensure the mask is the "source" image:
```
magick mainimage.png mask.png -compose Multiply -composite out.png
```
If your mainimage might be grayscale, use "-set colorspace sRGB":
```
magick mainimage.png -set colorspace sRGB mask.png -compose Multiply -composite out.png
```

**Comment by fu123456** [comment]
Thanks. I have solved this issue via your solution.
