### ISSUE TITLE
PNG: convert fails with "invalid chunk type"

### ISSUE THREAD

**Issue by horstreiterer** [ImageMagick/ImageMagick#531]
![test](https://user-images.githubusercontent.com/29751350/27631881-5999299a-5bfa-11e7-9e26-aa1afadf76d1.png)

A sample PNG file fails to load in case of convert with "invalid chunk type". More specifically, png_read_end fails. This error also occurs in the context of a minimal sample. However, I'm unsure whether or not thus must be addressed by libpng (downgrading to a warning?) or ImageMagick (ignoring errors in case of png_read_end - I'm not sure if the data read by that function is required by ImageMagick). Please look into it.

The file displays/loads correctly with:
- Windows Explorer
- Microsoft Paint
- Adobe Photoshop

$ convert test.png test.jpg
convert: IEj[B6]: invalid chunk type `test.png' @ error/png.c/MagickPNGErrorHandler/1649.

Tested with ImageMagick 6.9.8-3 and libpng 1.5.13-7.

libpng Sample:

#include <unistd.h>
#include <stdlib.h>
#include <stdio.h>
#include <png.h>

static void errorhandler(png_struct *ping,png_const_charp message)
{
  printf("libpng-%s error: %s\n", PNG_LIBPNG_VER_STRING, message);
  exit(1);
}

int main(int argc, char **argv)
{
  FILE *fp = fopen(argv[1], "rb");
  char header[8];
  fread(header, 1, 8, fp);
  png_structp png_ptr = png_create_read_struct_2(PNG_LIBPNG_VER_STRING, NULL, errorhandler, NULL, NULL, NULL, NULL);
  png_infop info_ptr = png_create_info_struct(png_ptr);
  png_init_io(png_ptr, fp);
  png_set_sig_bytes(png_ptr, 8);
  png_read_info(png_ptr, info_ptr);
  png_read_update_info(png_ptr, info_ptr);
  int height = png_get_image_height(png_ptr, info_ptr);
  png_bytep *row_pointers = malloc(sizeof(png_bytep) * height);
  int y;
  for (y = 0; y < height; y++) {
    row_pointers[y] = (png_byte*) malloc(png_get_rowbytes(png_ptr,info_ptr));
  }
  png_read_image(png_ptr, row_pointers);
  png_read_end(png_ptr, info_ptr);
  fclose(fp);
  return 0;
}

**Comment by glennrp** [comment]
This could be addressed in libpng, not IM.  It was a design choice to issue
an error rather than a warning. I agree that it could be a "benign
error" when the bad chunk is in the "end" section of a PNG, after
the image data has already been successfully decoded.  It's too
late to get this into libpng-1.6.30 which is due out tomorrow but
we can address it in libpng-1.6.31beta.

Glenn

**Comment by glennrp** [comment]
The bad chunk is actually ahead of the IDAT,
not in the end segment, according to pngcheck:

studio> pngcheck -vf invalid_chunk.png
File: invalid_chunk.png (241 bytes)
  chunk IHDR at offset 0x0000c, length 13
    20 x 21 image, 32-bit RGB+alpha, non-interlaced
  chunk sRGB at offset 0x00025, length 1
    rendering intent = perceptual
  chunk gAMA at offset 0x00032, length 4: 0.45455
  chunk pHYs at offset 0x00042, length 9: 3780x3780 pixels/meter (96 dpi)
  invalid chunk name "IEj�" (49 45 6a ffffffb6)
  chunk IEj� at offset 0x00057, length 0:  illegal critical, safe-to-copy chunk
  chunk IDAT at offset 0x00063, length 122
    zlib: deflated, 2K window, fast compression
  chunk IEND at offset 0x000e9, length 0
ERRORS DETECTED in invalid_chunk.png

So treating it as an unknown chunk isn't going to help,
because libpng will still bail out immediately as the
PNG spec requires, upon encountering an unknown
critical chunk.
