### ISSUE TITLE
-orientation option is not saved if the source image file has no "Orientation" attribute set

### ISSUE THREAD

**Issue by GajowyJ** [ImageMagick/ImageMagick#5461]
### ImageMagick version

7.1.0-46

### Operating system

Windows

### Operating system, version and so on

Windows 10

### Description

If the source file has no Orientation attribute set then the orientation added with _-orient_ option is lost when saving. On the contrary, if the source file has any value of _Orientation_ defined, one can change and save it succesfully.

### Steps to Reproduce

1. Create a file without Orinentation attribute defined, eg. in Paint (pls use the one attached).
2. Run the command: `convert LGDP-copy.jpg -orient left-bottom LDGP-left-bottom.jpg`
3. Check the orinetation: `convert LDGP-left-bottom.jpg -format %[orientation] info:`

Expected result: `Left-Bottom`
Actual result: `Undefined`

### Images

![LGDP](https://user-images.githubusercontent.com/50527827/185720550-3c14e991-6044-4a3b-8487-8606a9e4586f.jpg)

**Comment by dlemstra** [comment]
This is happening because the jpeg format does store the orientation in it's own metadata. This is stored in the exif profile. When an image has this profile the value will be updated there but we won't add an exif profile if the image does not have one. And that is why you are seeing this kind of behavior.

**Comment by GajowyJ** [comment]
Thank you for clarification.
