### ISSUE TITLE
configured with `--disable-openmp` but fails due to missing `-lomp`

### ISSUE THREAD

**Issue by the-shank** [ImageMagick/ImageMagick#5559]
### ImageMagick version

7.1.0-48

### Operating system

Linux

### Operating system, version and so on

Arch Linux

### Description

I passed the `--disable-openmp` flag during configuration step.

```bash
./configure --disable-openmp CC=clang CFLAGS="-g -O0" CXX=clang++ CXXFLAGS="-g -O0"
```

I can see that `-fopenmp` is present in the output of the configuration script in the `LIBS` list, which I believe shouldn't be there:

![image](https://user-images.githubusercontent.com/546476/189819118-6845be2f-66cb-4699-b30a-9031bd8c6554.png)

I then try to build using `make` and the build fails due to missing `-lomp`.

![image](https://user-images.githubusercontent.com/546476/189820161-a2d4be66-400e-41c7-bfc7-d08c007a36e3.png)

### Steps to Reproduce

- download release 7.1.0-48
- extract archive
- create a `build` dir
- `cd` into the `build` dir
- run configure script: `./configure --disable-openmp CC=clang CFLAGS="-g -O0" CXX=clang++ CXXFLAGS="-g -O0"`
- run make: `make`
- build fails due to missing `-lomp`

**Comment by urban-warrior** [comment]
Its possible one of the delegate libraries has a requirement to include the OpenMP delegate library.  Try building without any dependencies (e.g. --without-tiff, --without-jpg, etc.).  Then add one back at a time until you identify the dependency which includes `-lomp` as a dependency.   Or search the PKG configuration files and look for the `-lomp` dependency.  For each build, make sure you build in a clean directory otherwise a dependency might be leftover from a previous build.

**Comment by the-shank** [comment]
Thank you, I shall try building without any dependencies.
