### ISSUE TITLE
smart copy exif item from heic

### ISSUE THREAD

**Issue by japheth-sh** [ImageMagick/ImageMagick#5604]
### Is your feature request related to a problem? Please describe.

Some devices have extra 4 bytes in heic Exif item, see below it contains the APP0 and length.
![image](https://user-images.githubusercontent.com/43056596/192926842-9d48823c-0ec7-4822-8e28-d456ae322337.png)
After convert it to jpg, it lost all Exif information: "convert -define heic:preserve-orientation=true 5f1657a4-1b7a-4541-bec6-cdf2f2df2628 5f.jpg"
![image](https://user-images.githubusercontent.com/43056596/192927504-aa092119-81d5-4f68-8828-488cb493733a.png)
And exiftool complaints:
![image](https://user-images.githubusercontent.com/43056596/192927666-50e8a394-ac28-44c6-b5ba-055bdaf56256.png)
If I modify the iloc info of exif item, set the offset +4 bytes and length -4 bytes, and do the convert again, the result looks good.
![image](https://user-images.githubusercontent.com/43056596/192928226-68b6a61b-2402-46c0-84cf-a2ce215a0ac5.png)
![image](https://user-images.githubusercontent.com/43056596/192928295-9379bfb8-c460-4754-adb2-037d29f38f1c.png)

### Describe the solution you'd like

So could we improve the convert here to detect "Exif" instead of dropping first 4 bytes directly?
![image](https://user-images.githubusercontent.com/43056596/192928520-90e5765c-ba39-4925-99ca-6797f8218191.png)

### Describe alternatives you've considered
Or calculate to get the real Exif start. In this case 0x0000000a + 4(00 00 00 0a itself)-6("Exif\0\0") = 8, so we should skip first 8 bytes.
_No response_

**Comment by dlemstra** [comment]
Which application / camera created these files? And can you share an image that has this issue? This feels like something that should be fixed in the software that created the image. Not sure if we should apply a patch for this.

**Comment by kmilos** [comment]
Actually, it looks like the `0a` offset is totally correct to me and point exactly to what is needed - the pure `II` or `MM` starting Exif payload.

When writing this to JPEG, it should not be blindly copied, but a new APP1 constructed (i.e. `Exif\0\0`) added to the pristine Exif payload starting w/ `II` or `MM` (i.e. the 10 bytes should've been discarded already when HEIF was parsed), so perhaps the bug is actually there.

HEIF (or any other format that is not JPEG), should not be carrying (or should be ignoring/discarding) these JPEG APP1 shenanigans...

**Comment by dlemstra** [comment]
Thanks for figuring this out. I just pushed a patch to make sure we use the offset instead of skipping it. This will be resolved in the next release.

**Comment by japheth-sh** [comment]
Thank you guys~~Have a good day~~

**Comment by japheth-sh** [comment]
confirmed it works well. closing this issue.
