### ISSUE TITLE
Label not centered with gravity: center using font Charlotte

### ISSUE THREAD

**Issue by joyresourceshub** [ImageMagick/ImageMagick#5834]
### ImageMagick version

Version: ImageMagick 7.1.0-52 Q16-HDRI x86_64 20549

### Operating system

MacOS

### Operating system, version and so on

Monterey 12.6

### Description

Hi,

When creating a template using the font Charlotte, in certain cases the label  is not centered, despite specifying "gravity: center"

From tests it seems to be in cases when the text contains at least 1 letter "t" lowercase, there could be other cases, too.

Font used:
 https://www.downloadfonts.io/charlotte-font/

command used:

convert  -size 3800x1800  -background transparent  -gravity center  -fill black  -font /Users/nick/workspace/the-dream-code/fulfill-orders-bot/customization-engine/fonts/Charlotte.otf "label: Dr. Keith"  /Users/nick/workspace/the-dream-code/fulfill-orders-bot/customization-engine/temp/out-temp-first-christmas-as-dr-name-1-Dr.Keith-0.png

### Steps to Reproduce

Download the font:
 https://www.downloadfonts.io/charlotte-font/

Run the command:
convert  -size 3800x1800  -background transparent  -gravity center  -fill black  -font /Users/nick/workspace/the-dream-code/fulfill-orders-bot/customization-engine/fonts/Charlotte.otf "label: Dr. Keith"  /Users/nick/workspace/the-dream-code/fulfill-orders-bot/customization-engine/temp/out-temp-first-christmas-as-dr-name-1-Dr.Keith-0.png

**Comment by urban-warrior** [comment]
Label rendering is data driven based on the font metrics and any hinting required by the font.  Add `-debug annotate` to your command-line.  Notice the algorithm converges on a X offset of 331, whereas if you use a well curated font such as Arial, the offset is 0 and the label is truly centered.  Unless proven otherwise, we are trending toward the font metrics either being incorrect or the Freetype library not interpreting the metrics properly or not applying hinting properly.  If you can prove otherwise, we will investigate further.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/archive/beta/ by sometime tomorrow.
