### ISSUE TITLE
Converting from PNG to CRT causes crashes and hangs in AFL fuzzer.

### ISSUE THREAD

**Issue by KalleKulju** [ImageMagick/ImageMagick#5896]
### ImageMagick version

Version: ImageMagick 7.1.0-53 beta Q16-HDRI x86_64 28a3af8a7:20221115

### Operating system

Linux

### Operating system, version and so on

Kali Linux

### Description

When I ran ImageMagick with afl using the afl's free dataset (https://lcamtuf.coredump.cx/afl/demo/) using PNG with convert function, I got crashes and hangs with the error: 'convert: no encode delegate for this image format 'SCT''

### Steps to Reproduce

Compile AFL with imagemagick
download PNG files from dataset https://lcamtuf.coredump.cx/afl/demo/
The crashes and hangs can be reproduced using the files below

### Images

[Reproduce crashes.zip](https://github.com/ImageMagick/ImageMagick/files/10270077/Reproduce.crashes.zip)
[Reproduce hangs.zip](https://github.com/ImageMagick/ImageMagick/files/10270079/Reproduce.hangs.zip)

**Comment by urban-warrior** [comment]
It is highly recommended by ImageMagick to set up a security policy that is appropriate for your local environment.

Add these policies to your `policy.xml` configuration file:

```
  <policy domain="resource" name="width" value="8KP"/> 
  <policy domain="resource" name="height" value="8KP"/>
```

All the hangs/crashes images passed for us without crashes or hangs and instead returns:

```
convert: width or height exceeds limit ...
```

Without the limits, the crashes come from AFL because ImageMagick is requesting memory that exceeds some internal limit in AFL.  The hangs are due to ImageMagick attempting to create the pixel cache on disk.  Since the requirements are so huge, it would take hours/days to complete assuming enough disk space was available to accommodate the cache requirements.  The limits causes ImageMagick to instead gracefully exit with an appropriate message.
