### ISSUE TITLE
DDS BC5 / ATI2 (3Dc) support

### ISSUE THREAD

**Issue by expenses** [ImageMagick/ImageMagick#5919]
### Is your feature request related to a problem? Please describe.

I'd like to be able to convert BC5 .DDS normal maps with imagemagick. Here's a sample:

[Wood_Normal.dds.zip](https://github.com/ImageMagick/ImageMagick/files/10332146/Wood_Normal.dds.zip)

### Describe the solution you'd like

Support :D

### Describe alternatives you've considered

Gimp supports loading these files, but it's annoying to script. Renderdoc loads these files as well.

### Additional context

See https://en.wikipedia.org/wiki/3Dc

Maister has written about compressed GPU textures: https://themaister.net/blog/2020/08/12/compressed-gpu-texture-formats-a-review-and-compute-shader-decoders-part-1/ and has implemented a BC5 decoder at: https://github.com/Themaister/Granite/blob/master/assets/shaders/decode/rgtc.comp

**Comment by mmomtchev** [comment]
@expenses can you please test my PR, I have a limited number of test files that are all from the same source

**Comment by dlemstra** [comment]
What should be the output of your image @expenses? When I use the code from @mmomtchev their PR I get the following output image:
 
![z](https://user-images.githubusercontent.com/10426229/217370965-64a5e4b5-1623-4d5f-900a-a42cb62d46b0.jpg)

**Comment by expenses** [comment]
Looks like it's decoding correctly, but the blue channel isn't being derived:

![20230208_10h50m14s_grim](https://user-images.githubusercontent.com/13566135/217495980-f1db8bc1-752c-413c-8499-613123160125.png)

So I don't know too much about this format, except that it's presumably intended for normal maps. Normals are vectors with a length of 1, but because non-HDR images can't handle negative numbers, they're encoded by mapping the values from -1 to +1 to 0 to +1. Afaik, the blue channel can be derived with `B = sqrt(1.0 - R^2 - G^2)`. I haven't had time to check how gimp does this.

**Comment by expenses** [comment]
https://developer.nvidia.com/orca/amazon-lumberyard-bistro contains a scene with a large number of DDS textures if you want something to test this on.

**Comment by mmomtchev** [comment]
@expenses, this is a compression scheme that can encode only 2 colors. It's advantage is that these are encoded at almost full precision with only 4 bits per pixel. It is frequently used to encode floating point data such as splatmaps - instead of actual image data. The real question is how are the colors selected if the image is rendered as an image, because I simply take them to be Red and Green - as defined by Microsoft. Could it be that GIMP does something else?

**Comment by mmomtchev** [comment]
There are two encoding schemes, `BC5_UNORM` and `BC5_SNORM` - which are essentially the same - except for the fact that `SNORM` is to be interpreted as `-1.0f` to `1.0f`, while `UNORM` is `0.0f` to `1.0f`. I didn't implement `SNORM` because it didn't make any sense in this context. Maybe I should just treat it as `UNORM` - the other DDS encoders do this.

**Comment by mmomtchev** [comment]
No, in fact this is not true, no DDS codec in ImageMagick supports any `_SNORM` encoding, so this is staying like this.

@express texture opened with Microsoft tools (Visual Studio with DirectX development) is also red/green - AFAIK - there is no color selection information - there are simply two channels and Microsoft refers them as Red and Green.

**Comment by fmw42** [comment]
If you have only two channels of data, then typically the third channel is just set to zero (black).
