### ISSUE TITLE
Image Conversion Fail When Image has chinese layer name

### ISSUE THREAD

**Issue by punitpatel214** [ImageMagick/ImageMagick#6004]
### ImageMagick version

7.1.0-32

### Operating system

MacOS

### Operating system, version and so on

11.6.7

### Description

Image Conversion Fail When the Image has layers and one of the layer's name is in Chinese

 **Convert Command** : ` convert -trim Figure.tif Figure_converted.jpg`
 **Result**: `convert: unable to decompress image Figure.tif @ error/psd.c/ReadPSDChannel/1512.`

The above error was resolved when updating the Chinese layer name in English.

### Steps to Reproduce

- extract this zip file [chinese_layer_figure.zip](https://github.com/ImageMagick/ImageMagick/files/10515862/chinese_layer_figure.zip)
- execute convert command to convert tif file jpg ` convert -trim Figure.tif Figure_converted.jpg`

**Comment by urban-warrior** [comment]
The TIFF image has an embedded Photoshop profile.  ImageMagick thinks its corrupt.  A specific row does not fully expand to the extent of the row width.  @dlemstra can you take a closer look at the issue and determine if the image file is corrupt or there is a bug in the PSD coder?  If it is corrupt,  should we consider keeping the TIFF image as only the embedded profile has issues, not the TIFF image itself.

**Comment by dlemstra** [comment]
The PSD coder is failing to read the layer information due to and issue with the RLE encoding of one of the layers. I think that updating the layer name to English is not what is solving this issue. What happens when you change one of the other layer names to Chinese? Does that also solve your issue?

We did make the change suggested by @urban-warrior so you will be able to read this file in the next release.
