### ISSUE TITLE
fake NEF image read error

### ISSUE THREAD

**Issue by zmdyy0318** [ImageMagick/ImageMagick#6009]
### ImageMagick version

7.1.0-59

### Operating system

Windows

### Operating system, version and so on

11,21h2

### Description

I noticed that IM can automatically identify the image type.
For example, FAKE "jpg.psd" can be correctly recognized as JPG.
But FAKE "jpg.nef" are not correctly recognized as JPG.
Maybe this is a bug.
[fake_images.zip](https://github.com/ImageMagick/ImageMagick/files/10529239/fake_images.zip)

### Steps to Reproduce

`magick.exe identify -verbose path/to/122.jpg.nef `
output error: identify: Unsupported file format or not RAW file `path/to/122.jpg.nef' @ error/dng.c/ReadDNGImage/521.

`magick.exe identify -verbose path/to/122.jpg.psd `
output right

`magick.exe identify -verbose path/to/122.jpg `
output right

**Comment by dlemstra** [comment]
This is by design. For files that have `.nef` as the extensions we will always use the `DNG` coder. This is happening because `.nef` files start with a `TIFF` header. And if we would not force files with a `.nef` extension to the `DNG` coder the `TIFF` coder would try to read it and of course fail to do so.
