### ISSUE TITLE
BMP: "insufficient image data in file" error

### ISSUE THREAD

**Issue by utack** [ImageMagick/ImageMagick#6010]
### ImageMagick version

7.1.0-58 Q16-HDRI x86_64 20802

### Operating system

Linux

### Operating system, version and so on

Arch Linux

### Description

Opening a certain .bmp file with identify or convert results in the error:
`insufficient image data in file `f0275629.bmp' @ error/bmp.c/ReadBMPImage/997.`

The file can be viewed as normal in most software, but ffmpeg has a similar problem:
`[bmp @ 0x5654dfc8c800] not enough data (116158 < 116160)
Error while decoding stream #0:0: Invalid data found when processing input
`

Maybe you can check if this file is corrupted (which is a possibility) or causing an actual bug in some libraries.
Thank you

### Steps to Reproduce

`magick identify f0275629.bmp`

### Images

[f0275629.bmp.zip](https://github.com/ImageMagick/ImageMagick/files/10529576/f0275629.bmp.zip)

**Comment by urban-warrior** [comment]
The image is corrupt.  116160 images bytes are expected, but only 116158 are available in the image files.  ImageMagick errs on the side of caution to prevent processing corrupt or nefarious images to prevent a security issue.  As such, the image is rejected.  If we remove the check, we instead get an `unexpected end-of-file` exception.   Other apps we tried rejected the image as well and as you point our, some accept your corrupt image.

For this issue, rather than patch ImageMagick to read corrupt BMP images, we recommend you use another tool to clone the image and produce a file that meets the requirements of the BMP image specification.

**Comment by utack** [comment]
Thanks for confirming it is corrupt!
