### ISSUE TITLE
unable to open image 'x:root'

### ISSUE THREAD

**Issue by MyUserRainer** [ImageMagick/ImageMagick#6045]
### ImageMagick version

7.1.0-53

### Operating system

Windows

### Operating system, version and so on

10

### Description

Not sure, if this is a real problem in ImageMagick. Apologize.

We use ImageMagick in a X-Windows Virtual Development Environment (VMWare).
X-Windows is installed by OpenText Exceed Version 15.
We also use a third party SW which calls the "convert" service to capture windows.
The convert call is at the beginning: "convert x:root -crop"
The console output is: "convert: unable to open image 'x:root' : no such file or directory @ error/blob.c/OpenBlob/3570."

Note: In a former execution by using Windows 7 and a former OpenText Exceed Version, it works perfect.

We kindly request to investigate our observation and are happy to get a solution.

### Steps to Reproduce

-

### Images

-

**Comment by dlemstra** [comment]
There is no support for `x` on Windows.

**Comment by MyUserRainer** [comment]
Hello, please consider the following statement:
We use OpenText Exceed and:
OpenText Exceed has a long history of working with Microsoft to offer high performance X Window remote access.

**Comment by dlemstra** [comment]
I don't understand what you are trying to tell me?

**Comment by MyUserRainer** [comment]
The window, we like to fetch with ImageMagick is a X Window, provided by OpenText Exceed and displayed by a third party SW tool. Hope this helps for clarification. I will try to send you a screenshot, if it is possible.

**Comment by dlemstra** [comment]
As I said before there is no support for X-Windows on Windows and we are not going to add this.

**Comment by urban-warrior** [comment]
ImageMagick includes X11 support and it used to work with Windows years ago, but we stopped supporting it-- perhaps 15 years ago.   You could certainly built ImageMagick yourself under Windows and enable X11 support provided you have the requisite X11 development libraries.  Otherwise, you could build ImageMagick with X11 support under Windows with Cygwin, MSYS, or Bash.  Install Windows Bash which is Ubuntu-based.  Fire up your X server.  Now try your command.  It should work as long by default or perhaps you will need to adjust your DISPLAY environment variable.
