### ISSUE TITLE
Modulate Image - Make it work like GIMP

### ISSUE THREAD

**Issue by Jyzee** [ImageMagick/ImageMagick#65]
I would like to be able to modulate HSB as I do it in GIMP or Krita. I want to be able to add saturation or brightness without depending on their current value. For example, if saturation is at 0.1, adding 50% should add 0.5, not 0.05.

**Comment by fmw42** [comment]
I do not think IM will change the way -modulate works. It has been this way since the beginning and needs to be this way so that it would not break anyone else's code if changed. 

However the only difference I see (apart from the GIMP unique primary and secondary color modulation) is the offset in IM of 100%.  So if you want GIMP 50% saturation, that would be IM 150 saturation. So just take your GIMP values, add 100 to it and use those values for IM -modulate. You could also write a script to do this for you.  I am working on a bash unix shell script to emulate GIMP and Lightroom so that one can modulate any of the primary or secondary colors in addition to the global image colors.

**Comment by Jyzee** [comment]
Indeed, it works properly. My script was the one having an issue. Thanks !
