### ISSUE TITLE
Add an option to write a TGA footer when writing TGA files

### ISSUE THREAD

**Issue by FUJonathan** [ImageMagick/ImageMagick#6543]
### Is your feature request related to a problem? Please describe.

Our team (game development) uses TGA files for textures. We use ImageMagick to batch convert them from source PSD files.
We recently upgraded from Autodesk MotionBuilder 2018 to 2022 and discovered that the new version wouldn't load our textures. After some trial and error we determined that newer versions of MotionBuilder will no longer accept TGA files without a TGA footer.

### Describe the solution you'd like

Either add a command line switch to add a TGA footer to TGA files when they are written, or write the footer by default and include a switch to explicitly not write it for users who don't want it.

### Describe alternatives you've considered

As a workaround we wrote a simple tool to append the footer to all our TGA files after ImageMagick exports them, but ideally it would be nice if ImageMagick could do that all at once.

(Alternatively, somehow convince Autodesk to not check the footer for TGA files since the spec says it's optional...)

**Comment by dlemstra** [comment]
Where can we find some information about this TGA footer?

**Comment by FUJonathan** [comment]
@dlemstra 

It's described in the Truevision TGA file format specification document, in the "TGA File Footer" section (page 19 of the PDF format). Unfortunately there doesn't seem to be a definitive location for the document, but here are a few places you get it from:

https://www.dca.fee.unicamp.br/~martino/disciplinas/ea978/tgaffs.pdf
https://www.conholdate.app/viewer/view/rVqTeZPLAL/tga-file-format-specifications.pdf?default=view&preview=
https://github.com/DEAKSoftware/Truevision-TGA

It's a very simple blob, just two offset values that can be left zero followed by the identifier string "TRUEVISION-XFILE." We don't need the developer or extension areas so those offsets can be left at zero.

I searched the code and found it mentioned in the TGA reader function here ( https://github.com/ImageMagick/ImageMagick/blob/d551c5ed4fa9c40d9aa22875a56eb104b14fb374/coders/tga.c#L637 ) but nothing in the writer.

**Comment by dlemstra** [comment]
Thanks for the info. Just pushed a patch that writes an empty optional footer.

**Comment by FUJonathan** [comment]
Thanks! I'll check it out as soon as I get the chance!

**Comment by FUJonathan** [comment]
@dlemstra 
Hi again, thanks for the patch! I tested it but there's just one tiny issue - apparently there needs to be a single 0 byte at the very end of the footer, after the period in `TRUEVISION-XFILE.` MotionBuilder won't load the file without it. Sorry if the spec was a little confusing!

Actual:
<img width="446" alt="image" src="https://github.com/ImageMagick/ImageMagick/assets/7123060/8d2b8d82-c72a-44a2-996d-47b270de2bfa">

Expected:
<img width="446" alt="image" src="https://github.com/ImageMagick/ImageMagick/assets/7123060/3f0ee9cb-9538-403c-b8a4-3d09a8e187fd">

**Comment by dlemstra** [comment]
I thought I added this but I did not realize that `WriteBlobString` would ignore that. Will add another patch for this later today.

**Comment by dlemstra** [comment]
I don't mind adding a flag for that. But I don't understand why this is causing issues? Any thoughts for the name of the flag and if this should be an opt-in or an opt-out. What are your thoughts about this @FUJonathan?

**Comment by bztsrc** [comment]
> But I don't understand why this is causing issues?

Because it's an unnecessary overhead that shouldn't be there (one software in particular I'm struggling with is written to decode RLE compressed image data until it gets an EOF, so it tries to decode the footer as RLE and of course fails. Unfortunately I have no access to the source to fix it, so I need TGA files without a footer or any other junk after the real image data. It is unfortunate that this software was written this way, but since the footer is optional according to the TGA spec, I can't say it's wrong).

> Any thoughts for the name of the flag and if this should be an opt-in or an opt-out.

FYI, for me it doesn't matter, as long as footer generation can be controlled from the command line.

**Comment by dlemstra** [comment]
Because it looks like multiple implementation seem to have issues with following the spec of the format we have moved this behind an option @FUJonathan. To write this optional footer you will need to add `-define tga:write-footer=true` to write this optional footer in the output image.

**Comment by bztsrc** [comment]
Thank you very much! I believe now this solution covers both @FUJonathan's and my use case, thanks! With this flag we both can generate a TGA that our 3rd party software expects. As long as I'm concerned, the issue has been resolved!

**Comment by FUJonathan** [comment]
Sorry I didn't see this sooner! 
I should've guessed some software wouldn't work if the footer's there... 
The flag works fine for my use case! Thanks a lot!

**Comment by GwynethLlewelyn** [comment]
For future reference, since this issue is now closed, but Wikipedia mentions the existence of a "Targa 2.0 conformance suite", which can still be found here: https://github.com/image-rs/image/tree/main/tests/images/tga/testsuite — these are examples of images that allegedly should be properly coped with to be fully compliant according to 2.0 specs.

The originals, with a license explanation, and original source code from 1990 (!), used to be available here: [https://web.archive.org/web/20150714161320/http://googlesites.inequation.org/tgautilities](http://googlesites.inequation.org/tgautilities) — that was the latest snapshot I got from the Wayback Machine.
 
Surprisingly, the mentioned `TGAUTILS.ZIP` test suite is still downloadable from the Wayback Machine (or it still was at the time of writing this comment). It includes MS-DOS command-line executables, a file with some explanations on how to run the tests, the above-mentioned test files, and, surprisingly, the original source code for this test suite, in old-style C with _excellent_ comments. Unfortunately, I don't have any way to test any of these tools on my Mac, some of which require external libraries as dependencies; however, I'm pretty sure that these _will_ compile, given the proper nudging, especially the one named `tgadump`, which doesn't require any external dependencies beyond the C standard library.

Because of link & bit rot, it's not guaranteed that this file continues to be available in the future, so I'm uploading it here. Be careful with any code reuse, since the code is fully copyrighted by Truevision — a company which has been acquired by Pinnacle Systems, which was bought in turn by Avid Technologies, which subsequently sold Pinnacle to Corel. The current owner of the copyright is therefore not quite clear, and the above-mentioned `image` toolkit for Rust assumes the copyright has somehow expired; they haven't used any of the C code, anyway.

☞ [TGAUTILS.ZIP](https://github.com/user-attachments/files/15829044/TGAUTILS.ZIP)

(if you're on an Unix machine using the command-line `unzip` to extract the files within, remember that they will be extracted in all uppercase; extract them with `-L` [or even `-LL`] instead)

Naturally enough, this doesn't guarantee that _all_ applications out there reading/writing Targa files are fully compliant as well; I just wanted to point out that such a conformance test _did_ exist.
