### ISSUE TITLE
File saved in RAW format has JPEG data

### ISSUE THREAD

**Issue by audibleptr** [ImageMagick/ImageMagick#6616]
### ImageMagick version

7.1.1.15

### Operating system

Linux

### Operating system, version and so on

ALT Workstation K 10.1

### Description

File saved in RAW format has JPEG data and can't be opened by identify/display.

### Steps to Reproduce

1. `$ display file.jpg`
2. File > Save > Format > RAW > Save

**Actual result:** The file has JPEG data and can't be opened by identify/display:
```
$ file file.raw
file.raw: JPEG image data, JFIF standard 1.01, resolution (DPI), density 300x300, segment length 16, Exif Standard: [TIFF image data, big-endian, direntries=11, manufacturer=NIKON CORPORATION, model=NIKON D3100, orientation=upper-left, xresolution=176, yresolution=184, resolutionunit=2, software=GIMP 2.8.10, datetime=2014:10:06 12:13:58, GPS-Data], baseline, precision 8, 4608x3072, components 3

$ identify file.raw
identify: Unsupported file format or not RAW file `file.raw' @ error/dng.c/ReadDNGImage/539.

$ display file.raw
display: Unsupported file format or not RAW file `file.raw' @ error/dng.c/ReadDNGImage/539
```

**Expected result:** Image is saved in RAW format.

**Comment by snibgo** [comment]
> Unsupported file format or not RAW file `file.raw' @ error/dng.c/ReadDNGImage/539.

Notice that IM is trying to read the file as a DNG image.

The problem is the word "raw". It either means a file with no header at all, just pixel values. Or it means a complex file that comes from a digital camera, containing loads of metadata in a header, and pixel values that come from the digital sensor with minimal processing, ie "raw" sensor values.

IM won't write files in the DNG format, but it can read them.

I suggest using the different extension for your "raw" (headerless) files. Personally, I use ".bin" for those.

**Comment by urban-warrior** [comment]
The RAW image format is ambiguous because it could be a "raw" image or it might be a DNG image.  As such, you must explicitly declare raw images to remove the ambiguity.  In your case: `jpeg:file.raw`.
