### ISSUE TITLE
Image pipe to STDIN are always write disk cache even `MAGICK_DISK_LIMIT=0`

### ISSUE THREAD

**Issue by delhi2050** [ImageMagick/ImageMagick#6957]
### ImageMagick version

7.1.1-18

### Operating system

Windows

### Operating system, version and so on

10

### Description

The external program writes image data through a pipe to the STDIN of `magick.exe`, causing temporary file to be created on `C:/Users/<user>/AppData/Local/Temp/magick-xxxxxxxxxxxxxxxxxxxx`. Even when setting `MAGICK_TEMPORARY_PATH` to a nonexistent path, temp file are still created in the CWD.

### Steps to Reproduce

```
const magick = spawn('magick', [
  '-debug', 'Cache',
  '-',
  'avif:-',
], {env: {'MAGICK_DISK_LIMIT': 0, 'MAGICK_MAP_LIMIT': '128GB', 'MAGICK_AREA_LIMIT': '128GB', 'MAGICK_MEMORY_LIMIT': '128GB'}});
magick.stdin.write(fs.readFileSync('./image.jpg'));
magick.stdin.end();
magick.stderr.on('data', data => process.stderr.write(data));
```

**Comment by snibgo** [comment]
For MAGICK_DISK_LIMIT, MAGICK_MAP_LIMIT and MAGICK_MEMORY_LIMIT etc, see https://imagemagick.org/script/resources.php

If the memory limit would be exceeded, the pixel cache will be mapped up to the map limit, otherwise stored on disk up to the disk limit.

This doesn't prevent other data being written to disk. And perhaps your pixels don't reach the memory limit, so the disk limit is irrelevant.

**Comment by urban-warrior** [comment]
ImageMagick may occasionally save data to disk, even when using standard input and/or output for the infile and outfile. Resource limits typically impact the pixel cache but do not necessarily restrict other components of ImageMagick from utilizing the disk. An instance of this is when the image coder necessitates seeking. Since standard input lacks support for seeking, ImageMagick will duplicate the content from standard input to temporary disk to enable seek operations.

**Comment by urban-warrior** [comment]
ImageMagick is open-source.  Code up your proposal as a Git pull request and we will review for inclusion in the ImageMagick main.  See https://imagemagick.org/script/architecture.php for clarification of our design decisions.
