### ISSUE TITLE
Though the value set to date:modify is not used for png:tIME, setting an invalid timestamp still yields an error

### ISSUE THREAD

**Issue by BlackXStar42** [ImageMagick/ImageMagick#6998]
### ImageMagick version

7.1.1-24

### Operating system

Windows

### Operating system, version and so on

7, 6.1.7601

### Description

When I `-set date:modify` to a valid value, it is not used for `png:tIME`. Instead, `png:tIME` is determined each time a PNG file is written. I believe this is the intentional behavior as it is corresponding to how `date:create` and `date:modify` work, which are determined each time a file is read in turn.

But then, when I `-set date:modify` to an invalid timestamp, IM complains about it and doesn't write the `png:tIME` chunk at all.

I would like to understand:
If `png:tIME` is determined each time a PNG file is written, why does IM complain about an invalid timestamp specified by `date:modify` and why does it not keep determining it in this case?

### Steps to Reproduce

```
>magick convert xc: -set date:modify 2000-01-01T12:00:00Z Valid.png
>magick identify -verbose Valid.png
[...]
    png:tIME: 2024-01-03T12:34:56Z
[...]

>magick convert xc: -set date:modify foo Invalid.png
convert: Invalid date format specified for png:tIME `Invalid.png' (ret=0) @ error/png.c/write_tIME_chunk/7839.
>magick identify -verbose Invalid.png
(png:tIME missing)
```

**Comment by urban-warrior** [comment]
ImgeMagick refers to `png:tIME` property if the image is modified (e.g., resized) otherwise it refers to `date:modify` which is the timestamp captured when the image is first created within ImageMagick.

ImageMagick captures the date you specify for the `date:modify` property and passes it to the `libpng` delegate library.  The library is returning the exception, rightly so as it is an invalid date format.
