### ISSUE TITLE
Reproducible Windows builds

### ISSUE THREAD

**Issue by mmomtchev** [ImageMagick/ImageMagick#7041]
### Is your feature request related to a problem? Please describe.

Currently, VisualMagick does not permit to reproduce a Windows build since `CloneRepositories.sh` always retrieves the latest git checkout.

This means that Windows builds that do not always use the latest ImageMagick version break from time to time - the latest example is the `oss-fuzz` directory in ImageMagick.

### Describe the solution you'd like

`CloneRepositories.sh` should use the date of the latest commit in the `ImageMagick-Windows` repository to retrieve the dependencies up to this point in time.

### Describe alternatives you've considered

I do not see any solution at the moment, besides to always build only the latest Windows version.

### Additional context

`magickwand.js` has the option to be built from source - which few Windows users would use - that currently breaks with each new change in the build process.

**Comment by dlemstra** [comment]
You can re-use our repositories but this comes with no guarantees. It is also possible that we rename a file in the `ImageMagick-Windows` repository causing your build to break. We don't need a reproducible build for our Windows binaries so we will not be going to add this. That is something that you will need to solve yourself in your own build.

**Comment by dlemstra** [comment]
What you are suggesting does not work for us. The commit date of the `ImageMagick-Windows` repository is not what should be used in our build. It is irrelevant because it almost never changes. 

We don't need a reproducible build. And you adding this would require us to maintain it. You will need to create your own version of `CloneRepositories.sh` and use that in your repository.
