### ISSUE TITLE
heic:speed parameter not working

### ISSUE THREAD

**Issue by MimoKar** [ImageMagick/ImageMagick#7137]
### ImageMagick version

7.1.1-29 

### Operating system

Linux

### Operating system, version and so on

ubuntu 22.04 running in WSL2

### Description

When using the parameter "-define heic:speed=0" it throws this error:

Unsupported encoder parameter (5.2005) `000.heic' @ error/heic.c/IsHEIFSuccess/142.

Tried to use it as string, or using placebo string etc., but still same result.
In 7.1.1-28 it was working fine.

### Steps to Reproduce

Execute "magick convert -quality 20 -define heic:speed=0 000.jpg 000.heic" command

**Comment by dlemstra** [comment]
This means that you are using a version of libheif that has no support for this option.

**Comment by MimoKar** [comment]
libheif is1.17.6 installed on 2023-12-21 at 07:48:12 so it is not an issue with lib.
ImageMagick 7.1.1-29 was installed on 2024-02-27 at 09:04:28, so it is issue with ImageMagick...

**Comment by fmw42** [comment]
On IM 7, don't use magick convert.  Just use magick

**Comment by MimoKar** [comment]
Same result.

**Comment by fmw42** [comment]
Sorry, did you see all my comments. I edited my first post.

**Comment by MimoKar** [comment]
> Sorry, did you see all my comments. I edited my first post.

like this?
magick 000.jpg -quality 20 -define heic:speed=0 000.heic

result is same

**Comment by fmw42** [comment]
Do you have libde265 installed and if so what version?

**Comment by MimoKar** [comment]
1.0.15 on 2023-12-21 at 07:48:12

**Comment by dlemstra** [comment]
It might also be because you are passing an option that is not supported by the `heic` encoder. In previous version we had a check for avif but in a recent patch I decided that this should be handled by the user instead. I don't know the details of the `heic` encoder because I don't have this on Windows but I suspect that the `heic:speed` option is not supported and should be removed from your command.
