### ISSUE TITLE
TIFF image is rotated 180 degree

### ISSUE THREAD

**Issue by LyAnhVu** [ImageMagick/ImageMagick#7199]
### ImageMagick version

7.1.1-27

### Operating system

Windows

### Operating system, version and so on

Windows 11

### Description

When I use ImageMagick to convert tiff to tiff attached file, the output file is rotated. I didn't expect it.
With ImageMagick version 7.0.10-35, this doesn't happen.
Please help me investigate and explanation for it. Thank you.
[sample.zip](https://github.com/ImageMagick/ImageMagick/files/14767669/sample.zip)

### Steps to Reproduce

Use `convert.exe <input file> <output file> ` command line.

**Comment by fmw42** [comment]
try

`convert.exe <input file> -auto-orient <output file>`

**Comment by LyAnhVu** [comment]
This problem still occurs by using magick.exe.
I don't want to use the `-auto-orient` option and I want to know more clearly what changes ImageMagick has made that causes the behavior to change like that. Thank you.

**Comment by fmw42** [comment]
The image has a code that tells how the camera was oriented when it takes a picture. If you do not use -auto-orient, then the picture will not show correctly because it just shows the image in the default way it was captured. For example if the camera was rotated 90 deg from its normal orientation, then then image will show 90 deg rotated. The camera records this orientation and puts a code in the header. The -auto-orient command reads the orientation flag in the header and rotates the image so that it shows unrotated.
