### ISSUE TITLE
identify and display command destroys SVG files

### ISSUE THREAD

**Issue by rizalmart** [ImageMagick/ImageMagick#7244]
### ImageMagick version

7.1.1-30

### Operating system

Linux

### Operating system, version and so on

Slackware Current

### Description

See this slackware forum
[https://www.linuxquestions.org/questions/slackware-14/svg-overwritten-by-identify-4175735985/](https://www.linuxquestions.org/questions/slackware-14/svg-overwritten-by-identify-4175735985)

Error message shown

`/tmp/magick-W0ZTRRwTcj6czhomV-9zgZpQS5yVuXfb:1: parser error : Document is empty

^

** (org.inkscape.Inkscape:669): WARNING **: 20:46:12.346: Could not detect file format. Tried to open it as an SVG anyway but this also failed.
/tmp/magick-W0ZTRRwTcj6czhomV-9zgZpQS5yVuXfb:1: parser error : Start tag expected, '<' not found
/tmp/magick-W0ZTRRwTcj6czhomV-9zgZpQS5yVuXfb:1: parser error : Document is empty
^
ink_file_open: '/tmp/magick-W0ZTRRwTcj6czhomV-9zgZpQS5yVuXfb' cannot be opened!
InkscapeApplication::document_open: Failed to open: /tmp/magick-W0ZTRRwTcj6czhomV-9zgZpQS5yVuXfb
ConcreteInkscapeApplication::on_open: failed to create document!`

### Steps to Reproduce

Run the following commands on terminal
`identify <filename.svg>`
`display <filename.svg>`

**Comment by fmw42** [comment]
Post your SVG file.  What version of Inkscape is being used?

**Comment by pc2005cz** [comment]
OP from linuxquestions here ...
The content of SVG doesn't matter at all, identify will overwrite already overwritten error message too. Inkscape is version 1.2.2 (slackware package imagemagick-7.1.1_30-x86_64-1).

The problem seems to be in using older delegates.xml with newer rest of ImageMagick. The commit which updates delegates.xml is ["do not round off density"](https://github.com/ImageMagick/ImageMagick/commit/460ab772adaa6164e2344ea43ab0429d09525f41). 

When I updated delegates.xml to the current version, the overwrites of SVGs stopped. So the bug probably affects just people who modified their delegates.xml and didn't patch the quotes as in the commit. But I'm not certain and the discussion is most likely still live.

**Comment by urban-warrior** [comment]
We're using the latest ImageMagick release, 7.1.1-30, and cannot reproduce this issue.  Let us know if it works for you.
