### ISSUE TITLE
Invalid conversion from large .TIF image to .JPG or .PNG

### ISSUE THREAD

**Issue by ngongocthinh159** [ImageMagick/ImageMagick#7247]
### ImageMagick version

7.1.1-7 Q16 x64 21d049b:20230416

### Operating system

Windows

### Operating system, version and so on

Windows 11 version 23H2 build 22631.3447

### Description

When I try to convert this large .TIF file to .PNG or .JPG file the out_file was washed out (fully white)

### Steps to Reproduce

Convert the original .TIF image with this command:
magick.exe convert -limit area 100MiB -limit memory 1GiB -limit map 3GiB "X2O9Z9.tif" -colorspace "sRGB" -quality 5 -units PixelsPerInch -auto-orient "out_put.jpg"

TIF file: 
https://drive.google.com/file/d/1-AG-NP86-_Z4ckO8VJDYelEK_Zx4rFef/view?usp=sharing

**Comment by dlemstra** [comment]
Why are you setting the quality to `5`?

**Comment by ngongocthinh159** [comment]
> Why are you setting the quality to `5`?

Even if I change the quality to 80 - 90 - 100, the issue is still happened. Full command:
magick.exe convert -limit area 100MiB -limit memory 1GiB -limit map 3GiB "X2O9Z9.tif" -colorspace "sRGB" -quality 80 -units PixelsPerInch -auto-orient "out_put.jpg"

**Comment by dlemstra** [comment]
The problem with your input image is that it contains meta channels but none of them are marked as an alpha channel. If your image had one meta channel you could use `magick -define tiff:assume-alpha=true X2O9Z9.tif output.png` to mark the first meta channel as an alpha channel. But your image contains more than one meta channel so you will need to wait for the next release where we will also allow this when there is more than one meta channel. And when you use `jpg` as the output format your image will still be white because the transparent pixels appear to have a white background.
