### ISSUE TITLE
No rule to make target 'NEWS.txt', needed by 'all-am'.

### ISSUE THREAD

**Issue by rivard2** [ImageMagick/ImageMagick#7249]
### ImageMagick version

7.1.1-30

### Operating system

Linux

### Operating system, version and so on

Ubuntu 22.04.3

### Description

Since the new release 7.1.1-30, my docker container will no longer build.

Here's where it fails.
![image](https://github.com/ImageMagick/ImageMagick/assets/167122224/222dc6e0-fdc9-423e-b15f-969a46f852a3)
And the error message.
![image](https://github.com/ImageMagick/ImageMagick/assets/167122224/ec2052ec-1939-40af-9acb-8e3453be800e)

### Steps to Reproduce

1. git clone https://github.com/ImageMagick/ImageMagick.git
2.  ./configure
3. make

**Comment by dlemstra** [comment]
That is not related to the new release. You seem to be using the development branch of our repository instead of an official release. We don't guarantee a correct build for our main branch. An update was made to some of the `Makefile.am` files and they require an updated of autoconf/automake. Until that was done the build would fail. Those files have been updated so your build should work again. But we would advise you to do a checkout of our release tag instead.
