### ISSUE TITLE
Convert to lower bit depth with dither

### ISSUE THREAD

**Issue by guijan** [ImageMagick/ImageMagick#7569]
### Is your feature request related to a problem? Please describe.

IM lacks an option to convert images from a higher bit depth to a lower bit depth with dither. The only option we have is to add random noise to the image, but random noise dither is less accurate than error diffusion dither. 

This is useful, for instance, to perform high quality scales in 16bpc, then quantize them down to 8bpc with dither for better image quality when viewing using an 8bpc screen or saving to a format that only supports 8bpc like JPEG. Or to convert a 10bpc screenshot to a format that only supports 8bpc.

### Describe the solution you'd like

`-depth` could be changed to dither according to the values of `-dither` and `-quantize`.

### Describe alternatives you've considered

`-posterize` and `-colors` generate colors at the source bit depth, not the target bit depth, so that a 16-bit image that had `-colors 256` applied to it creates a result with 256 total colors where each has 16-bit precision, meaning they will lose meaningful data in the least significant bits when converted to a lower bit depth such as `-depth 8`, such that these operators might even pick several distinct colors in the 256-color 16bpc palette which all become the same color at 8bpc. 

Also, from my experience, these operators have some kind of limit which silently limits the number of colors they output:

```console
$ convert hald:8 -format 'original colors: %k\n' -write info: -colors 16777216 -format 'after -colors 16777216: %k\n' -write info: null:
original colors: 262144
after -colors 16777216: 58856
```

```console
$ convert hald:8 -format 'original colors: %k\n' -write info: -colors 1000000 -format 'after -colors 1000000: %k\n' -write info: null:
original colors: 262144
after -colors 1000000: 58856
```

```console
$ convert hald:8 -format 'original colors: %k\n' -write info: -posterize 256 -format 'after -posterize 256: %k\n' -write info: null:
original colors: 262144
after -posterize 256: 57279
```

```console
$ convert hald:8 -format 'original colors: %k\n' -write info: -posterize 128 -format 'after -posterize 128: %k\n' -write info: null:
original colors: 262144
after -posterize 128: 56092
```

`-remap` + `hald:N` appears to do the right thing, but is horribly inefficient and runs into the colormap size limit:
https://github.com/ImageMagick/ImageMagick/blob/1fac80a83b28cbe8b791dd644c77ae298d70b04d/MagickCore/colormap.c#L118-L124
https://github.com/ImageMagick/ImageMagick/blob/1fac80a83b28cbe8b791dd644c77ae298d70b04d/MagickCore/magick-type.h#L78
```console
$ convert hald:8 -format 'original colors: %k\n' -write info: -remap hald:7 -format 'after -remap hald:7: %k\n' -write info: null:
original colors: 262144
convert: unable to create colormap `8' @ error/colormap.c/AcquireImageColormap/123.
convert: memory allocation failed `8' @ error/quantize.c/SetImageColormap/4007.
after -remap hald:7: 262144
```
It also seems to march on and save the image without remapping after erroring.

**Comment by snibgo** [comment]
`convert` uses the very very old v6 syntax. I suggest using `magick` instead. If your IM is v6, this will need an upgrade to v7. I doubt this makes any difference to your problem.

`-depth N` is a setting, not an operation. An *operation* may change image pixels. A *setting* changes the behaviour of operations and doesn't change pixels. `-depth N` changes the behaviour of writing to files.

Modifying `-depth N` to be an operation that reduced the precision of image pixels would be a major change to IM, and a bad idea. But a new operation could do this. It might be, for example, `-reducedepth N`.

As you say, MaxColormapSize is typically 65536. I have experimented with this. Increasing this number can cause a crash at later processing, and I haven't isolated that problem.

In principle, reducing the precision of image pixels shouldn't need to use a colormap, so MaxColormapSize shouldn't be a problem. Doing this without dithering is trivial. Doing this with dithering would need a new version of IM's dithering code (eg quantize.c `RiemersmaDither()`) because those functions use a colormap `QCube` to find the nearest color. When we are simply reducing the precision, a simple algorithm would give the nearest colour.

If anyone is considering doing this, they might consider also adding more recent dithering methods.

**Comment by urban-warrior** [comment]
We propose a new operation, either `-depth-dither`,  `-precision-dither` or `-jjn-dither`, utilizing Jarvis-Judice-Ninke dithering algorithm. Before we develop the solution, what do you suggest for the operation name, and which dithering algorithm do you prefer?

**Comment by guijan** [comment]
I suggest against `-jjn-dither` because it would bake the name of an algorithm into the name, and the algorithm could be changeable with `-dither`. `-depth-dither` seems like a good name to me, it's the shorter one and it essentially conveys the idea of "the same thing as `-depth` but with dither".

Wikipedia has a good article about dithering algorithms: 
https://en.wikipedia.org/wiki/Dither#Algorithms

At relatively high depths (e.g. 8bpc), pixel densities, and in some kinds of images, none of the dithering algorithms are noticeable, in that case the Mean Average Error between the original and the dithered version matters the most, so at least whichever algorithm scores the best there should be supported. At small bit depths, some algorithms might happen to look more pleasing than others, so perhaps it would be a good idea to also support algorithms that are significantly different from each other. Following `-quantize` is also important for color accuracy.

**Comment by fmw42** [comment]
Looking at that reference, I do not see all that much difference.  Is this really different enough from what we already have currently?
