### ISSUE TITLE
Cropping issue / question

### ISSUE THREAD

**Issue by Steve-Albers** [ImageMagick/ImageMagick#7592]
### ImageMagick version

7.1.1-36 

### Operating system

MacOS

### Operating system, version and so on

14.6.1 Sonoma

### Description

magick image.jpg -crop 100x100 image.jpg image_cropped.jpg produces multiple cropped image instead of a singe image.

Is this to be expected?

### Steps to Reproduce

magick image.jpg -crop 100x100 image.jpg image_cropped.jpg 

### Images

![stevealbers3](https://github.com/user-attachments/assets/883eee82-c0f4-4de0-acd0-4ba15016798e)

**Comment by fmw42** [comment]
You have to specify the top left corner of the crop as -crop WxH+X+Y where X,Y is the top left corner. Otherwise, you get a tile crop for all non-overlapping WxH as you got. See 

https://imagemagick.org/script/command-line-options.php#crop
https://imagemagick.org/Usage/crop/#crop
https://imagemagick.org/Usage/crop/#crop_tile

**Comment by snibgo** [comment]
> Steps to Reproduce
magick image.jpg -crop 100x100 image.jpg image_cropped.jpg

That command contains two input image files and one output file. Both inputs are "image.jpg". Remove the second one.

As fmw42 says, to get just one image from "-crop", you should include "+X+Y" where X and Y are numbers. I suppose you want zero for each. I suggest adding "+repage" after the crop. So:
```
magick image.jpg -crop 100x100+0+0 +repage image_cropped.jpg
```

**Comment by Steve-Albers** [comment]
Thanks for all your very useful comments.
