### ISSUE TITLE
Tables get distorted

### ISSUE THREAD

**Issue by lalitap25** [ImageMagick/ImageMagick#7694]
### ImageMagick version

7.1.1

### Operating system

Windows

### Operating system, version and so on

Windows server 2019

### Description

We are using imagemagick to convert some windows meta files(.wmf) to .png files and it works well with all kind of images except formulas and tables.

the values in table column gets overlapped.

The zip file contains the original file and the converted file.
[Images.zip](https://github.com/user-attachments/files/17381603/Images.zip)

### Steps to Reproduce

unzip the attachment
try to run this command
magick.exe -density 600 C:\visualization\magick-tmp\picture6627189417406342295.wmf -adaptive-resize 785 -gamma 0.9 C:\visualization\magick-tmp\picture6627189417406342295try10.png

### Images

NA

**Comment by dlemstra** [comment]
I am getting a different image on my machine. 

![output](https://github.com/user-attachments/assets/cabf8206-b20b-4e7c-80e5-b8a2b27aef6a)

I suspect that this is working differently for you because you are on Window server 2019 and something is not available on that operating system. Not much we can do about that.

**Comment by dlemstra** [comment]
And next time there is no need to open a new issue when you asked the same question in a discussion.
