### ISSUE TITLE
GIF to WebP conversion fails in ImageMagick 7.1.1 (worked in 7.1.0)

### ISSUE THREAD

**Issue by lovehyunju** [ImageMagick/ImageMagick#7828]
### ImageMagick version

7.1.1

### Operating system

Windows

### Operating system, version and so on

Windows 11

### Description

Hello,

I am experiencing an issue with **ImageMagick 7.1.1** when converting GIF files to WebP format. The same process worked perfectly in **ImageMagick 7.1.0**, but after upgrading to 7.1.1, the conversion either fails or produces a corrupted WebP file.

I would appreciate any help regarding this issue.

Thank you.

### Steps to Reproduce

magick 1.gif 1.webp

### Images

![1](https://github.com/user-attachments/assets/cd9637d0-4f29-464d-9278-789f27f2f87c)
![2](https://github.com/user-attachments/assets/460e5a3d-3b99-4469-b7a6-e8983ce4b918)
![3](https://github.com/user-attachments/assets/e4cb7b1e-6263-4ed3-8600-956d2b6d8011)

**Comment by urban-warrior** [comment]
We can reproduce the issue.  We'll need a few days to analyze the problem and export a patch.  Thanks.

**Comment by urban-warrior** [comment]
Try this command:

```
magick 1.gif -coalesce 1.webp
```

**Comment by dlemstra** [comment]
You should add `-coalesce` now because we removed code that would do that automatically. Doing that automatically could result in incorrect output when the user also did `-coalesce` themselves. We now made this the responsibility of the user. It will only be done automatically when the input image contains frames that have different sizes because this is a requirement of the `webp` encoder.
