### ISSUE TITLE
The height, width and color for the transformed eps to jpg image

### ISSUE THREAD

**Issue by DigneshGoyal** [ImageMagick/ImageMagick#899]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I am converting the EPS file to JPG using ImageMagick.However I see incorrect height,width,color of the transformed jpg file.

Below is the location where file is present

https://drive.google.com/file/d/1Z73NBCYn0sdO7R7dMHZHLE03JvkX66j1/view?usp=sharing 

### Steps to Reproduce
Below are the command line arguments that I am using.
 -flatten -intent relative -quality 95 -colorspace sRGB -auto-orient 

### System Configuration

- ImageMagick version:
Version: ImageMagick 7.0.3-8 Q16 x64 2016-11-24 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2015 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Visual C++: 180040629
Features: Cipher DPC Modules OpenMP
Delegates (built-in): bzlib cairo flif freetype jng jp2 jpeg lcms lqr openexr pangocairo png ps rsvg tiff webp xml zlib

I am also using Ghostscript AGPL 9.2.2  version 64bit

Can anyone please let me know how can i get proper color, height and width for transformed image

**Comment by urban-warrior** [comment]
ImageMagick leverages the Ghostscript delegate library or gs program to render an EPS image file.  Any rendering issues would require a bug report with Ghostscript rather than ImageMagick.  The image includes an ICC profile.  To apply a color transform you need two profiles, the source is associated with the image.  You need the -profile option and a destination color profile to effect a color transformation.

You can improve the quality of the image by supersampling.  Add -density 400% before your EPS image on the command-line and -resize 25% after the EPS image.
