### ISSUE TITLE
ImageMagick CLI ignores Disk limit and creates temporary files

### ISSUE THREAD

**Issue by Alexander--** [ImageMagick/ImageMagick#919]
### System Configuration

- ImageMagick version: current Git HEAD (42d385599)
- Environment (Operating system, version and so on): Linux

### Description

This ticket describes two related bugs:
1. The CLI tool tries to create pixel cache files even when "Disk" limit is set to 0
2. The CLI tool incorrectly handles standard input/output and file descriptor inputs/outputs

Those bugs cause ImageMagick to create unnecessary temporary files and make it unusable without filesystem access.

### Reproduction

````bash
#!/bin/bash
exec 0< foo.png
exec 1> bar.png
# you can replace stdin/stdout with "fd:", the behaviour is same either way
strace -eopen,openat magick convert -limit Disk 0 -limit Memory 9999M - -
````

The trace shows creation of two (!!) temporary files. ImageMagick tries to write to them and fails (because of "Disk" limit).

Temporary files should not be created when "Disk" limit is set to 0. Given enough memory, they should never be necessary when input is seekable (regardless of nature of destination file).

### Analysis

First issue manifests in temporary files being created (and subsequently deleted) under usual circumstances: when input appears to be non-seekable, when memory is insufficient etc. Unfortunately, the files are created even after "Disk" limit is exhausted (or when it was set to 0 to begin with). After remaining disk limit is <= 0, the failure must happen immediately, *before* attempting to create another temporary file. This is a minor issue, but it complicates debugging and obfuscate nature of another issue.

The second issue manifests in creating unnecessary pixel cache files under various circumstances (for example, when input or output are represented by file descriptors). This is caused by multiple bugs and design flaws in ImageMagick:

1. Special treatment of stdin/stdout (filenames are compared to `"-"` all over the place). Standard descriptors should be treated same as other file descriptors on Linux and same as other non-seekable files on Windows;
2. File descriptors (`fd:N`) are [incorrectly assigned][1] `StandardStream` blob type;
3. `StandardStream` is [incorrectly hardcoded][2] as non-seekable within `IsBlobSeekable`;
4. All decoders currently require seekable files (e.g. they have `CoderDecoderSeekableStreamFlag`)
5. SetImageInfo [uses][3] "IsBlobExempt" to decide whether to copy a stream to temp file, which makes zero sense.

### Expected resolution

The way it is now, `StreamType` does not convey any useful information. There are multiple redundant blob types and ImageMagick fails to correctly categorize descriptors/streams. Ideally, it should work like this:

1. Dynamically check if file descriptor is seekable once, by calling `seek` on it.
2. Let custom streams dynamically report if they are seekable (instead of assuming that from type of stream).

[1]: https://github.com/ImageMagick/ImageMagick/blob/0dabf1608be6d0268f58db49b38b53987dac6edb/MagickCore/blob.c#L3108
[2]: https://github.com/ImageMagick/ImageMagick/blob/0dabf1608be6d0268f58db49b38b53987dac6edb/MagickCore/blob.c#L2718
[3]: https://github.com/ImageMagick/ImageMagick/blob/0dabf1608be6d0268f58db49b38b53987dac6edb/MagickCore/image.c#L2858

**Comment by urban-warrior** [comment]
The disk resource limit only affects the creation of the image pixel cache.  If the resource limit is exceeded, a "cache resources exhausted" exception is thrown.  The disk resource limit does not prevent ImageMagick from creating termporary files on disk for a variety of other circumstances.

Commit https://github.com/ImageMagick/ImageMagick/commit/336bb38beecd94390af872fe9c16aa7693a97ac0 attends to some of your concerns:

- files "-" and "fd:" are now a file stream rather than a standard stream
- seekability is determined dynamically
- removed the call to IsBlobExempt() in SetImageInfo()

After reviewing the patch, if you have further suggestions, let us know.

**Comment by Alexander--** [comment]
> The disk resource limit does not prevent ImageMagick from creating termporary files on disk for a variety of other circumstances.

Could you please list those circumstances? Do you at least agree, that this is a bug?

> files "-" and "fd:" are now a file stream rather than a standard stream

Still plenty of checks like [this one](https://github.com/ImageMagick/ImageMagick/blob/master/MagickCore/blob.c#L1341). I assume, that missing those will silently cause descriptor leaks or corruption in `fd:N` case.

> seekability is determined dynamically

It really should be remembered after checking once. I don't think, that there is any standard file type of character device, that changes it's seekability on-fly. In my patch I have done this by assigning different `StreamType` during blob initialization.

Some places, that currently check for "-" should instead use `IsBlolbSeekable`, so doing system calls might be a bad idea.

> if you have further suggestions, let us know.

Still waiting for fix (or rather removal) of `CoderDecoderSeekableStreamFlag`. I am not file format guru, but seeing that browsers do good job at progressive image rendering, most decoders really shouldn't care about seekability — perhaps some transforms may,  but not decoders themselves.

**Comment by urban-warrior** [comment]
In case we forgot-- thank you for your analysis.  The patch we added as a result of your posting was good and necessary fix.

Regard the disk limit.  Its only a bug if you set the disk limit to 0 and an image pixel cache is created on disk.  If you are seeing this behaviour, let us know how to reproduce the problem and we will investigate further.

FileToBlob() does not support files of type fd: so we do not see an opportunity for a descriptor leak.  If we're wrong, let us know how we can reproduce a leak and we will investigate further.

We could check for seekability once and set a boolean value.  However, its likely not necessary since checking for seekability is infrequent.  We will however add some debugging to confirm our suspicions.

The CoderDecoderSeekableStreamFlag is necessary.  Up to 20 image formats do not require a seekable stream.

**Comment by urban-warrior** [comment]
We had to revert the removal of IsBlobExempt() in SetImageInfo().  Without it

`magick logo: miff:- | magick - logo.png`

fails under Windows although the command works fine under Linux.
